### ISSUE TITLE
./configure CFLAGS and --enable-optimzation=no are not being honored during the build process

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#121]
During the build process, make V=1 shows that the CFLAGS and --enable-optimization=no options on a ./configure command during the build process are not added at the end of the generated commands. Rather -Wall and -O3 always come later, thus overriding the former options.

**Comment by Peter-J-Jansen** [comment]
As a circumvention to this problem I've used this ./configure option : 

```
--enable-optimization="-g -g3 -ggdb3 -O0 -Wno-format ..."
```

as these options are added at the very end and can therefore override earlier options like the ones from CFLAGS. Also, this replaces the default optimization options which are typically "-O3 -g -gr -ggdb3", and can therefore be used to change these.  In the above example "-O0" (Oh Zero) disables optimization altogether, and "-Wno-format" overrides an earlier "-Wall"-implied "-Wformat", thus suppressing compiler warning messages for such format errors.

**Comment by Fish-Git** [comment]
@Peter-J-Jansen 

I'm not sure what `-Wall` or `-Wformat` has to do with optimization, _but..._

Should `-Wall` and/or `-Wformat` be _removed_ (or changed to `-Wno-format`) whenever `--enable-optimization=no` is specified? I understand that `-O3` should _not_ be specified, but I'm unclear about `-Wall` and `-Wformat`.

I know what the bug is and how to fix it (see `configure.ac` lines 200-225), but I need to your opinion (and others' too if they're interested in replying) regarding the `-Wall` and `-Wformat` flags.

Thanks!

**Comment by mhoes** [comment]
Hi,

For what it's worth (2$cent ? less ?), I think you should always want to enable '-Wall' (including or perhaps even more so for debug builds), as it enables the display of 'all' diagnostic messages that are assumed to be desirable by 'most' people according to the GCC devs. (except for the additional ones enabled by '-Wextra' and '-Wpedantic', for example. (Not claiming that you should or should not enable those, by the way)).

I think that what was meant above, is that by specifying '-Wall', which includes at least in GCC 8.2.0 [1] a '-Wformat', that gets overriden by specifying an additional '-Wnoformat', when the '-Wformat' is the desired option. So removing the explicit '-Wnoformat' will return the default behavior of '-Wformat' which gets included with '-Wall'.

So no, these options do not (as far as I can tell) have anything to do with optimization (or the lack thereof), but it appears that for both cases ('-O3' vs '-O0', and '-Wall' vs '-fnoformat') it is true that 'something gets overridden by something-else', which is not what one would want.

I'll crawl back under my rock now. ;)


[1]
[https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Warning-Options.html#Warning-Options](url)

**Comment by Peter-J-Jansen** [comment]
Thanks for the feedback !  

Both optimization levels and options like "-Wall" need to end up as compiler options, and the last (rightmost) options override previous (leftmost) ones. The ./configure implementation is such that (1) the options specified through CFLAGS (like a "-Wno-format" option, this was just an example) do not end up as the last (rightmost) one, hence has no effect (as "-Wall" overrides it). And that (2) the ./configure "--enable-optimization=no"  remains without effect as an "-O3" ends up as a later (more to the right) compiler option. The workaround, of only using the other format of --enable-optimization="xxx yyy zzz ...", has the desired result of placing "xxx yyy zzz ..." at the rightmost options in the compiler command.

So the option "-Wall" should remain, just the order of where "CFLAGS" get placed on the compiler command should be corrected by placing it at (or more to) the end of the compiler command. (The regular Hyperion renamed the "CFLAGS" option to "ADD-CFLAGS".) This involves indeed perhaps only ```configure.ac``` line 213 : 

```
CFLAGS="-W -Wall ${CFLAGS}"
```
Lines 215-224 could perhaps be removed altogether, because (1) a user specifying either "-O2" or "-O3" in CFLAGS can be expected to understand the irregularity  he is trying to achieve, and because (2) correcting / overriding these conflicts with possible "--enable-optimization=..." usage or defaults.

**Comment by Fish-Git** [comment]
@Peter-J-Jansen,

I have my changes ready to commit, but before I do so, I would like you to please confirm for me whether or not the following looks correct to you:

```
--enable-optimization="-O2"
--enable-optimization=yes
--enable-optimization=no

CFLAGS="-Wno-format"
```

CFLAGS | opt=xxx | opt=yes | opt=no | EXPECTED results... | ACTUAL results...
-------|---------|---------|--------|---------------------|--------------------
&nbsp;|&nbsp;|&nbsp;|&nbsp;|-O3|-g -g3 -ggdb3 -O3 -march=native -fomit-frame-pointer -Wall -W -pthread -D_GNU_SOURCE
&nbsp;|&nbsp;|=yes|&nbsp;|-O3|-g -g3 -ggdb3 -O3 -march=native -fomit-frame-pointer -Wall -W -pthread -D_GNU_SOURCE
YES|&nbsp;|&nbsp;|&nbsp;|-O3 -Wno-format|-g -g3 -ggdb3 -O3 -march=native -fomit-frame-pointer -Wall -W -pthread -D_GNU_SOURCE -Wno-format
YES|&nbsp;|=yes|&nbsp;|-O3 -Wno-format|-g -g3 -ggdb3 -O3 -march=native -fomit-frame-pointer -Wall -W -pthread -D_GNU_SOURCE -Wno-format
&nbsp;|="-O2"|&nbsp;|&nbsp;|-O2|-O2 -Wall -W -pthread -D_GNU_SOURCE
&nbsp;|&nbsp;|&nbsp;|=no|&nbsp;|-Wall -W -pthread -D_GNU_SOURCE
YES|="-O2"|&nbsp;|&nbsp;|-O2 -Wno-format|-O2 -Wall -W -pthread -D_GNU_SOURCE -Wno-format
YES|&nbsp;|&nbsp;|=no|-Wno-format|-Wall -W -pthread -D_GNU_SOURCE -Wno-format

&nbsp;
The above illustrates the tests I did to ensure both `--enable-optimization=no` is always honored as well as any `CFLAGS="xxx"` value that might also be specified on the `./configure` command.  Please take a look at the above chart and tell me if it looks okay to you.

The change I have ready to commit ensures whatever `CFLAGS` values Hercules adds are always added _before_ any existing `CFLAGS` value, such that _your_ (the user's) specified `CFLAGS` value always comes _last_ on the command line, thus allowing _you_ (the user) to easily override whatever `CFLAGS` value(s) Hercules might decide to use.

The same idea applies to `--enable-optimization` too: whatever optimization flags that Hercules decides should be used (whether as a result of auto-optimization logic or due to the user specifying their own optimization flags (or requesting no optimization _at all_ via `--enable-optimization=no`)) is always inserted _before_ the `CFLAGS` value on the command line. (The bug preventing `--enable-optimization=no` from working was also fixed of course.)

If everything looks correct to you, please let me know, and I will go ahead and commit the change.

Thanks.

**Comment by Peter-J-Jansen** [comment]
Fish,

This is just perfect ! Thanks for all your efforts.

Cheers,

Peter

**Comment by Fish-Git** [comment]
Closed by commit 25b0adeb8c62c33f5ae17478aa4b22f7aac43aa6 and 773033af2c2ee15312f6931f7220cec18a540639

**Comment by Peter-J-Jansen** [comment]
Hi Fish,

I just wanted to let you know that I've now tested your fix and all is working perfectly now.  The ./configure on  MacOS, if one wants to avoid the rare (and probably z/VM SIE - only) bug, should include "--enable-optimization=no".  (The same is true for the other Herculeses.)

Thanks,

Peter

**Comment by ivan-w** [comment]
Great to hear (although it is still VERY speculative that your DMSFRE issue is an actual SIE issue... I conjectured it.. it may be bogus) !

**Comment by ivan-w** [comment]
For Information : 
Just got hit with a 
`DMSFRR161E Invalid free storage release call from 01135FFE, error code 6`
While running SDL hyperion with a Linux CLANG
