### ISSUE TITLE
SPKA insruction generating Protection exception 

### ISSUE THREAD

**Issue by YossiReichman** [SDL-Hercules-390/hyperion#138]
Hi

I am getting a protection exception on SPKA instruction is this possible ? the Pops books says only  Privileged operation exception the first two bytes of the PSW are 0754 which means bit 15 is 0 which means I am in Supervisor State regardless the inst is SPKA X'50'(0) which means I am trying to set the PSW key to 5 that should be good even in problem state

Thanks

**Comment by ivan-w** [comment]
Is it possible the change in the PSW key has made the fetching of the next instruction impossible ?

**Comment by YossiReichman** [comment]
I thought any when an abend was displayed with an instruction the offending instruction is displayed 
okay thanks

**Comment by ivan-w** [comment]
When a protection exception occurs during instruction fetching, the instruction is nullified but the ILC is unpredictable (and probably contains 2 - meaning 4 bytes - thus pointing back to the SPKA instruction). The POP doesn't list protection exception as a possible program interrupt because the protection exception is *indirectly* caused by SPKA.
