### ISSUE TITLE
use open object rexx installed in a non standard location

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#147]
done, tested
almost ready for a pull request
cheers
e

**Comment by Fish-Git** [comment]
????

Could you provide more detail please? What is the problem?

(If such cryptic issue creation keeps up I'm just going to start deleting them!)

**Comment by herc4mac** [comment]
a standard location for me is usr/local
since I have about three  different version of open object rexx 
installed in different directories and NOT in /usr/local
i thought about sharing what I have done

but Your repo, Your Rules

free to delete all the issues, ( more like suggestions really ) 

and even to cancel the pull request for the external packages and the apple issue

goodbye all

**Comment by Fish-Git** [comment]
For crying out loud, Enrico! I just asked for more detail!

A problem description of "done, tested almost ready for a pull request cheers e" is hardly a very descriptive problem report! Nor is the issue title by itself either!

You didn't have to be a baby and go away in a huff! Sheesh!

Can't we just get along for crying out loud? Why are behaving this way? Why are you being so hostile towards me? What did I ever do to you?&nbsp;`:(`
