### ISSUE TITLE
Unable to build on Linux (arm64/aarch64)

### ISSUE THREAD

**Issue by mgrossmann** [SDL-Hercules-390/hyperion#161]
I tried to compile Hercules on my Odroid C2 _(arm64 / aarch64)_.

First, configure complained that my system couldn't be guessed.  _(config.guess doesn't know arm64 or aarch64)_ &nbsp; Then I tried: 

    ./configure ... --host=aarch64-linux-gnu host_alias=aarch64-linux-gnu --build=aarch64-linuc-gnu

So configure was satisfied for the time being.

But now I run into a compiler error:

```
aarch64-linux-gnu-ar: 'u' modifier ignored since 'D' is the default (see 'U')
  CC       cckdcdsk.o
  CCLD     cckdcdsk
./.libs/libhercu.a(version.o): In function 'display_extpkg_vers':
/root/mainframe/git/SDL-hyperion/version.c:841: undefined reference to 'decnumber_version'
/root/mainframe/git/SDL-hyperion/version.c:842: undefined reference to 'softfloat_version'
/root/mainframe/git/SDL-hyperion/version.c:843: undefined reference to 'telnet_version'
collect2: error: ld returned 1 exit status
Makefile:1894: recipe for target 'cckdcdsk' failed
make[2]: *** [cckdcdsk] Error 1
make[2]: Leaving directory '/root/mainframe/git/SDL-hyperion'
Makefile:2279: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mainframe/git/SDL-hyperion'
Makefile:1647: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mettlerr** [comment]
Having similar problems compiling on a Raspberry Pi3 Model B, architecture arm7l. For 'make' I get:

`gcc: error: unrecognized argument in option '-mcpu=armv7l'`
`gcc: error: unrecognized argument in option '-mtune=armv7l`

and if correcting with `./configure --enable-optimization="-mcpu=arm7"` I get the following make errors:

`gcc: error: ./crypto/lib/arm/libcrypto32.a: No such file or directory
gcc: error: ./decNumber/lib/arm/libdecNumber32.a: No such file or directory
gcc: error: ./SoftFloat/lib/arm/libSoftFloat32.a: No such file or directory
gcc: error: ./telnet/lib/arm/libtelnet32.a: No such file or directory`

Tried substituting the libraries which are in the lib directories, but they seem to be for x86, and produce a _"not executable"_ error in make.

**Comment by wably** [comment]
@mettlerr  below is the optimization string that I use for a Raspberry Pi 3B for ./configure :

      --enable-optimization="-O3 -pipe -mcpu=cortex-a8 -mfpu=neon-vfpv4 -mfloat-abi=hard"

Some fixes were committed to correct the build process for SDL Hyperion on Raspberry Pi a few months ago, so be sure you have a recent copy of the repository.  You will likely receive some warnings about shared libraries; these can be ignored.

**Comment by mettlerr** [comment]
@wably hmmmmm.... still same. Git-cloned if freshly, applied your optimizations, but still make reports:

```
*** Warning: Linking the shared library libhercu.la against the
*** static library ./crypto/lib/arm/libcrypto32.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./decNumber/lib/arm/libdecNumber32.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./SoftFloat/lib/arm/libSoftFloat32.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./telnet/lib/arm/libtelnet32.a is not portable!
gcc: error: ./crypto/lib/arm/libcrypto32.a: No such file or directory
gcc: error: ./decNumber/lib/arm/libdecNumber32.a: No such file or directory
gcc: error: ./SoftFloat/lib/arm/libSoftFloat32.a: No such file or directory
gcc: error: ./telnet/lib/arm/libtelnet32.a: No such file or directory
Makefile:1842: recipe for target 'libhercu.la' failed
make[2]: *** [libhercu.la] Error 1
make[2]: Leaving directory '/srv/source/hyperion'
Makefile:2279: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/srv/source/hyperion'
Makefile:1647: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wably** [comment]
Did you build the external packages first, per the instructions in README.EXTPKGS  ?

**Comment by wably** [comment]
@mgrossmann  I am hoping that @Fish-Git can weigh in on your issue.  I do not know what to tell you for your type of hardware.

**Comment by mettlerr** [comment]
@mgrossmann Sorry, thought I had a similar problem, as it's also ARM architecture... Will try the external packages process, and report back. Didn't do that yet, as I definitively overlooked the part of the instructions.

**Comment by mgrossmann** [comment]
I‘m just kidding

**Comment by mettlerr** [comment]
... aaaaaaand works! Was the external packages.

**Comment by Fish-Git** [comment]
> I built the external packages with the following parameters:
> 
> ```
> --all --install ~/mainframe/git/SDL-extpkgs
> ```

Did you specify the `--cpu xxxx` parameter?  If so, then that's your first problem.

> Then I moved all libraries from `~/mainframe/git/SDL-extpkgs/lib/` to `~/mainframe/git/SDL-extpkgs/arm/`.

Which you should _not_ have had to do. Rather, you should have simply:

* Specified the `--enable-extpkgs=~/mainframe/git/SDL-extpkgs` option on your Hercules `./configure` command,

_--or--_

* Pointed your 'LIBRARY_PATH' and 'CPATH' environment variables to the appropriate subdirectory of your `SDL-extpkgs` directory (e.g. `~/mainframe/git/SDL-extpkgs/lib` and `~/mainframe/git/SDL-extpkgs/include`) before configuring/building Hercules.

This is all explained in the [README.EXTPKGS](https://github.com/sdl-hercules-390/hyperion/blob/master/README.EXTPKG) document that [Bob already mentioned](https://github.com/SDL-Hercules-390/hyperion/issues/161#issuecomment-449018111) that is also clearly mentioned on SDL Hyperion's **"[Building and Installing](https://sdl-hercules-390.github.io/html/hercinst.html)"** document.

___
p.s. If you download and use the `ExtPkgs.sh` shell script to automatically clone, build and install your external packages _(recommended!)_, be sure to update the `ExtPkg.sh.ini` initialization file's `cpu = ...` statement with the proper value for your CPU before issuing your `ExtPkgs.sh` command.

**Comment by Fish-Git** [comment]
I'm labeling this as a "DOC Bug" since it might be that our documentation (web pages) are not clear enough regarding how to properly build SDL Hyperion.

I'm thinking _maybe_ we should split the main "Installation and Operation" web page into two separate "Building and Installing" and "Operating Instructions" web pages, and then split the new "Building and Installing" web page into two separate "Building and Installing on Windows" and "Building and installing on Linux" web pages. But I'm open to suggestions.

I just want the procedure to be not only as _clear_ and as _easy to follow_ as possible, but also as easy to _find_ as possible too. My concern is people transitioning from Hercules 3.x or Hyperion 4.0 over to SDL Hyperion 4.x are being mistakenly led to believe  that the build process is the same as it has always been, which is obviously not true. So I'm scratching my head as to how to best go about fixing that.

Suggestions -- especially from people who have had problems with it in the past -- would be greatly appreciated. Thanks.

p.s. I'm also marking this issue "Close Pending" until such time as the OP (@mgrossmann) reports back that his problem has been resolved.

**Comment by mgrossmann** [comment]
Hello, Fish,

Thank you very much for your detailed answer. But I think we talk a bit past each other. The problem is that the arm64 aka aarch64 architecture is neither recognized by CMake (for the extpkgs) nor by configure (Hercules). 

What I have done so far:

I started everything all over again. This time I used the extpkgs.sh you mentioned. I have to use "unknown" as CPU, otherwise, the packages don't build.
I set the environment variables as you suggested.

A call to configure then leads to:

```
root@DietPi:~/mainframe/hercules# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/root/mainframe/hercules/autoconf/missing: Unknown '--is-lightweight' option
Try '/root/mainframe/hercules/autoconf/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... autoconf/config.guess: unable to guess system type

This script, last modified 2003-07-02, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (autoconf/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2003-07-02

uname -m = aarch64
uname -r = 3.16.57+
uname -s = Linux
uname -v = #1 SMP PREEMPT Sun Aug 19 15:27:56 CEST 2018

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.16.57+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Sun Aug 19 15:27:56 CEST 2018
configure: error: cannot guess build type; you must specify one
```

Then I tried to specify a build type.

```
root@DietPi:~/mainframe/hercules# ./configure --build=aarch64-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/root/mainframe/hercules/autoconf/missing: Unknown '--is-lightweight' option
Try `/root/mainframe/hercules/autoconf/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... Invalid configuration `aarch64-linux-gnu': machine 'aarch64' not recognized
configure: error: /bin/bash autoconf/config.sub aarch64-linux-gnu failed
```

Next I have installed newer versions of config.guess and config.sub, configure then runs successfully.
```./configure --enable-extpkgs=/root/mainframe/extpkgs --prefix=/usr/local --enable-optimization="-O3 -pipe -march=armv8-a+fp+simd+crc -mtune=cortex-a53"```

But make failed again:

```
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       cckdcdsk.o
  CCLD     cckdcdsk
./.libs/libhercu.a(version.o): In function `display_extpkg_vers':
version.c:(.text+0x448): undefined reference to `decnumber_version'
version.c:(.text+0x494): undefined reference to `softfloat_version'
version.c:(.text+0x4d0): undefined reference to `telnet_version'
version.c:(.text+0x538): undefined reference to `softfloat_version'
version.c:(.text+0x574): undefined reference to `telnet_version'
version.c:(.text+0x624): undefined reference to `softfloat_version'
version.c:(.text+0x6e4): undefined reference to `telnet_version'
version.c:(.text+0x754): undefined reference to `telnet_version'
version.c:(.text+0x7b0): undefined reference to `telnet_version'
collect2: error: ld returned 1 exit status
Makefile:1894: recipe for target 'cckdcdsk' failed
make[2]: *** [cckdcdsk] Error 1
make[2]: Leaving directory '/root/mainframe/hercules'
Makefile:2279: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mainframe/hercules'
Makefile:1647: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Fish-Git** [comment]
> The problem is that the arm64 aka aarch64 architecture is neither recognized by CMake (for the extpkgs) nor by configure (Hercules).

Oh! My apologies for my misunderstanding, Mike!

I guess this problem is _not_ resolved then, and isn't a documentation bug either!&nbsp;`:(`

OK... Based on what you've written above, here is my suggested course of action:

**Building the External Packages:** use the `ExtPkgs.sh` script to rebuild ALL of your external packages, being sure to specify "cpu = unknown" in your `ExtPkgs.sh.ini` file. (It sounds like you've already done this but it wouldn't hurt to do it again just to be sure.)

**Building Hercules:** setting the LIBRARY_PATH and CPATH variables as you have already done, _should_ work. But if it doesn't, then manually specifying the `--enable-extpkgs=/root/mainframe/extpkgs` configure option certainly shouldn't hurt either. Both methods _should_ end up accomplishing the very same thing.

Where _I think_ you may have gone wrong was in your failure to specify the `--build=aarch64-linux-gnu` option on your ./configure command. (Or maybe all three like you originally tried? i.e. `--host=aarch64-linux-gnu host_alias=aarch64-linux-gnu --build=aarch64-linuc-gnu`)

Specifying those configure options _**should**_ (I think!) _(I hope!)_ trigger Hercules's configure.ac logic to look for the external package static libs in the 'unknown' subdirectory (which, if you built your external packages like I suggested just above, _should_ be where they actually will be!).

Try that. Based on what you've written, it sounds like that _should_ work for you. Please let me know if it doesn't.

And as far as newer versions of config.guess and config.sub are concerned, my Linux skills are remarkably weak. (I'm not a Linux person!) Is that something the _user_ needs to do? (just as you have done?) Or is that a change (update) that I need to make to Hercules? Thanks!

(And sorry about the misunderstanding. I've removed "Doc bug" and "Pending close" from the GitHub Issue status and have restored the original "Bug" status for now until this issue is properly resolved.)

p.s. to my fellow team members: HELP!&nbsp;`:)`

**Comment by mgrossmann** [comment]
Is there anything new to report here?

**Comment by Juergen-Git** [comment]
Added build support for aarch64. Note: External packages need to be built manually until equivalent changes are made in extpkgs.sh and cmake files. See commit [a5221f1](https://github.com/SDL-Hercules-390/hyperion/commit/a5221f14c15449822e332c6404a90fa5f9cd0309)

**Comment by Fish-Git** [comment]
_**FYI:**_ &nbsp; @mgrossmann &nbsp; @Juergen-Git 

the "gists" repo (containing the `extpkgs.sh` and `ExtPkgs.cmd` scripts) and all External Package repos (crypto, decNumber, SoftFloat, and telnet) have now been updated to _(hopefuly!)_ support `aarch` cpu:

* [SDL-Hercules-390](https://github.com/SDL-Hercules-390)

I did _not_ change anything related to cmake itself, as I believe [Mike's comment](https://github.com/SDL-Hercules-390/hyperion/issues/161#issuecomment-449358642) regarding cmake was actually describing a `extpkgs.sh` problem, not a cmake problem.

(p.s. _**THANK YOU** Jürgen for the SDL Hyperion fix for this issue!!_)

**Comment by mgrossmann** [comment]
ty Juergen and Fish
