### ISSUE TITLE
File Set Via HERCULES_RC Environment Variable No Longer Found

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#178]
The SDL-Hercules log now shows :

```
16:49:00 HHC01405E Script file  not found
16:49:00 HHC00007I Previous message from function 'process_script_file' at script.c(845)
```

Could this be caused by the recent changes re. "getenv" ? I looked at the code changes, but could not find why this would have caused it.

Thanks,

Peter

**Comment by Fish-Git** [comment]
Yep! Yet _more_ fallout from my issue #21 "Replace 'getenv' calls with 'get_symbol' calls instead"  commit! (SIGH!)&nbsp;`:(`

Root cause is a bug (poor design?) of @ivan-w Ivan's DEFSYM package: the `get_symbol` function isn't thread safe! It's returning a static buffer! (which is a _huge_ no-no!)

I'm working on it!

**Comment by Fish-Git** [comment]
Resolvced by commit f6923d8302b34c804c1445d0ff8088ca93e042e9.
