### ISSUE TITLE
Presence of hercules.rc not honored, need -r option

### ISSUE THREAD

**Issue by FanDjango** [SDL-Hercules-390/hyperion#179]
SDL-Hyperion 31.01.2019

-r option needed for hercules.rc to be executed on hercules start, but it should use an existing hercules.rc if present in the working directory even if the -r is not specified. 

Although the current SLD documentation does not explicitely specify this behaviour, previous hercules versions behaved that way.

Low prio, but annoying as I often change versions on the fly and need to modify the hercules start script to handle this (or to make the start script "smarter" and check the hercules version).

Since there was some work in a related area (#178) , it could be a simple bug so I am reporting it here.

**Comment by Fish-Git** [comment]
> SDL-Hyperion 31.01.2019

FYI: that's not a valid version string. A valid version string looks like this:

    HHC01413I Hercules version 4.2.0.9534-SDL-g7de109f1 (4.2.0.9534)

If the Hercules `version` command does not report a version similar to the above, it might be because you manually built your Hercules from the downloaded source instead of from a git clone of the repository. The string `g7de109f1` tells us _exactly_ what version of Hercules you are using, whereas `31.01.2019` does not.

> `-r` option needed for `hercules.rc` to be executed on hercules start, but it should use an existing `hercules.rc` if present in the working directory, even if the `-r` is not specified.

Correct. This is definitely a **bug** (a regression) that was introduced into the Hyperion 4.x series approximately 3 years ago by apparently the following commit:

        Revision: 79a0a17354d9f5ca9ce6032d3448aad3fca59ce2
        Author: John P. Hartmann <jphartmann@gmail.com>
        Date: 11/24/2015 4:34:35 AM
        Message:
        Fix impl.c to process arguments early so that flags are set correctly.
        This implements daemon mode as it should be.

        Still a number of problems (sigsevs), but it is unclear which are due
        to this fix and what if due to my environment, so we stash this for now.
        ----
        Modified: bldcfg.c
        Modified: hexterns.h
        Modified: impl.c
        Modified: msgenu.h
        Modified: script.c
        Modified: tests/runtest

and was unfortunately carried over into SDL-Hyperion as well.

I'll see what I can do to get it fixed for you...

**Comment by Fish-Git** [comment]
Fixed by commit 971a8645922c483d36c62e8214bafa5cf94f0d14.
