### ISSUE TITLE
Reliability of CTCx adapters

### ISSUE THREAD

**Issue by bluecmd** [SDL-Hercules-390/hyperion#191]
Hi,

I'm running 2 Hyperions that have a CTCE connection to each other like this:

Instance 1:
```
41A0 CTCE 30810 127.0.0.1 30820
41A1 CTCE 30812 127.0.0.1 30822
```

Instance 2:
```
42A0 CTCE 30820 127.0.0.1 30810
42A1 CTCE 30822 127.0.0.1 30812
```

I run under Debian 9 currently at revision 6b2dccfc. When shutting down one instance using `quit` and then taking it up again it's not uncommon for the states of the CTCE adapter of the other instance to become invalid:

```
HHC05079I 0:41A0 CTCE: <- 0:42A0 #0003 cmd=WRT=01 xy=aW<-aa l=0047 k=717A74CA         CC=1 WAIT ATTN->NONE Busy_Waits=4
HHC05079I 0:41A0 CTCE: <- 0:42A0 #0017 cmd=WRT=21 xy=aW<-aa l=1112 k=A58BA559 Stat=80 CC=0 WAIT ATTN->RC=0 Busy_Waits=7
HHC00721I 0:0A10 Shared: connected to file 127.0.0.1:3390:0A10
HHC05076I 0:41A0 CTCE: Connection closed; 0 MB received in 353 packets from 0:42A0=127.0.0.1:30820
HHC05076I 0:41A1 CTCE: Connection closed; 0 MB received in 341 packets from 0:42A1=127.0.0.1:30822
HHC05072E 0:41A1 CTCE: Not all sockets connected: send=34, receive=-1
HHC05072E 0:41A0 CTCE: Not all sockets connected: send=33, receive=-1
HHC05070E 0:41A0 CTCE: Accepted inbound connection :30811 <- 127.0.0.1:30820 (bufsize=61592,12)
HHC05070E 0:41A1 CTCE: Accepted inbound connection :30813 <- 127.0.0.1:30822 (bufsize=61592,12)
HHC05074E 0:41A1 CTCE: Error writing to 0:42A1=127.0.0.1:30822: Broken pipe
HHC05074E 0:41A0 CTCE: Error writing to 0:42A0=127.0.0.1:30820: Broken pipe
HHC05074E 0:41A1 CTCE: Error writing to 0:42A1=127.0.0.1:30822: Broken pipe
HHC05074E 0:41A0 CTCE: Error writing to 0:42A0=127.0.0.1:30820: Broken pipe
HHC05074E 0:41A1 CTCE: Error writing to 0:42A1=127.0.0.1:30822: Broken pipe
```

This will not recover by itself and I find myself restarting both instances. It's possible I could detach the device and re-add it to re-init it, but that's more a workaround than a solution I feel.

I have also ended up in a case where Hyperion got into a state where errors were printed many many times a second and nothing really worked well. I regret to not having saved the logs on that occasion but it further shows that taking a look at how the CTCE (and possibly the others depending on how much code is shared) handles disconnects and resets would be beneficial.

I will gladly own the issue to investigate and propose fixes unless there is a better candidate that wants to do so :-).

**Comment by Peter-J-Jansen** [comment]
Christian,

Thanks for this information. The poor recoverability or CTCE connections, including the inability to restart them, is currently indeed the state of affairs; it is the main topic I have been working on the last few months. Enhancements in this area are forthcoming, but I'm afraid this will still take a some time. This is due to the need to test various CTCA connections, e.g. z/VM SSI ISL's, VTAM CTCA's (MPC and non-MPC), z/OS XCF and GRS, etc. Also, all my testing includes Windows, Linux, and MacOS.

The best results one can achieve today is by ensuring that _all_ Hercules instances with CTCE connections between them are properly started _before_ any operating system is IPL'd. This has proven to work well in various environments. However, as stated, as soon as one looses a CTCE connection, this wil not be recoverable. Currently, the only option is to bring everything down, and then restart it all afresh.

I am sorry that right now that's the state of affairs. Please bear with me, I'm working on improving this.

Cheers,

Peter

**Comment by bluecmd** [comment]
@Peter-J-Jansen No worries at all! Right now I'm running everything on one machine but in the summer I'm expecting to run two cluster members on two physically separate machines for redundancy, at which point it would great if something like this recovered by itself.

If there is anything I can do to help your work in this area Peter, including testing etc, let me know.

**Comment by Fish-Git** [comment]
> Please bear with me, I'm working on improving this.

I hope my recent Shared Device Server changes hasn't negatively impacted your efforts!

**Comment by Peter-J-Jansen** [comment]
No, it's just me trying to get my CTCE improvements also working using UDP (in addition to TCP); I might have to give up on that idea.

**Comment by Fish-Git** [comment]
Just checking for a status update: Is this issue still a problem?

**Comment by Fish-Git** [comment]
Closing due to lack of progress/interest.
