### ISSUE TITLE
Hercules has crashed - commit 3f22b48

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#207]
Crash occurs on both Windows 10 virtual machine and Fedora 29 host. The attached log and dump are from one of the Windows 10 crashes. The executable was created with the usual Rebuild Solution in Visual Studio 2017. The config and disk images have existed for several years.
[Hercules.zip](https://github.com/SDL-Hercules-390/hyperion/files/3137513/Hercules.zip)

**Comment by Fish-Git** [comment]
HOLY CRAP! I'm seeing the same thing! The CPU thread is taking a wild branch to location 0x0000000000000000! No stack backtrace, so I don't know where it came from. I don't know what function it was in before it got to where it crashed. NOTHING!

Not good! Not good!

Let me try to look into this ASAP!

And FWIW, _**yes*_ I did test my last change! But _obviously_ not thoroughly enough! (Duh!) I ran my set of "runtests" (i.e. 'make check') both with and without facility 53 enabled, and it ran fine, but I never bothered to actually IPL an actual guest o/s because I honestly thought the change, the addition of facility 53 support, was largely uncontroversial, and since as I said it worked fine as a standalone runtest, why _wouldn't_ it work when a guest o/s was IPLed?! Obviously I was wrong! Let me look into this ASAP and I'll get back to you. It's probably something silly/stupid.

Sorry about this!&nbsp;`:(`

(BAD Fish! Naughty Fish! Bad, bad naughty, naughty Fish!)

**Comment by Fish-Git** [comment]
(Temporarily?) Fixed by commit f5e12b4aec3b0e3a82011d37a1c67ad16e31dffc.

I'm having trouble figuring out Bernard's weird E3 instruction optimization implementation, which even _he_ admits is "complex". It appears to only be for the LG and STG instructions, and looking at the difference between how his optimized version compares with the unoptimized version, it doesn't look like it would actually help all that much anyway (_maybe_ a teensy-tiny amount, but not very fricking much on the grand scheme of things).

So since it's causing trouble with the replace opcode function I've decided to just disable instruction optimization altogether for the E3 instructions (which as I said was only for LG and STG anyway).

Once (and _**IF**_) I ever figure it out I'll remove the temporary workaround, but for now compile time constant `OPTION_NO_E3_OPTINST` will remain the default. (Note: `OPTION_OPTINST` will remain enabled by default just as before, so all _other_ instruction optimizations will remain in effect (will still be optimized), just not the "E3XX" LG and STG instructions. They're the only ones that won't be.)

Please rebuild and try again.

Thanks.

(and sorry about all this!)
