### ISSUE TITLE
VIPA handling in QETH (OSA) driver

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#209]
I've opened a new issue which follows on from #204, as I am experiencing different results to those reported in #204. Firstly a couple of quotes from #204:-

> ..., when more than one VIPA interface (DEFINE VIRTUAL) is defined, only the last one seems to work.

My z/OS isn't modern enough to support INTERFACE statements for IPv4, I have to use DEVICE/LINK for IPv4 VIRTUALs, but no matter how many VIRTUALs I define, none of them work.

> This is a user error, not a Hercules bug!

Disagree, it is not a user error, it is a Hercules bug.

My Hercules (and z/OS) has 3 PTPs, 3 QETHs and 1 LCS. Generally only one PTP device is started, used for IPv4 and IPv6. My TCP/IP profile has a variety of DEVICE/LINK and INTERFACE statements for the other devices, plus DEVICE/LINK statements for VIRTUAL devices and INTERFACE statements for VIRTUAL6 devices. 

When I issue a start for the IPv4 QETH, z/OS correctly issues 8 SETIP commands, 1 with `ipa_sip->data.ip4.flags == IPA_SIP_DEFAULT`, the other 7 with `ipa_sip->data.ip4.flags == IPA_SIP_VIPA`.The SETIP commands with IPA_SIP_DEFAULT is for the QETHs home IPv4 address, and results in a "Register guest IP address" message from Hercules. The SETIP commands with IPA_SIP_VIPA are for the home IPv4 addresses of the PTPs, the other QETH, the LCS and the VIRTUALs. The PTPs, the other QETH, the LCS and 1 of the VIRTUALs are all on separate and different subnets, the other VIRTUAL is on the same subnet as the started QETH.

qeth.c only calls `register_ipv4` for SETIP commands with `IPA_SIP_DEFAULT`.

Also, qeth.c only calls `register_ipv6` for IPv6 SETIP commands with `IPA_SIP_DEFAULT`. However, all IPv6 SETIP commands seem to have IPA_SIP_DEFAULT, irrespective of whether the IPv6 address is for a VIRTUAL6 interface or not. Also, my z/OS only issues SETIP commands for the IPv6 address(es) from the first VIRTUAL6 interface that is defined.

**Comment by Fish-Git** [comment]
> ..., when more than one VIPA interface (DEFINE VIRTUAL) is defined, only the last one seems to work.

Which, you are correct, is _wrong_.

Please see the final followup comment that I just recently made in the  issue 204 thread:

* https://github.com/SDL-Hercules-390/hyperion/issues/204#issuecomment-492396565

Multiple VIPAs _are_ valid and allowed.


> > This is a user error, not a Hercules bug!
> 
> Disagree, it is not a user error, it is a Hercules bug.

> qeth.c only calls `register_ipv4` for SETIP commands with IPA_SIP_DEFAULT.

Hmmm... Okay... That _does_ sound like a potential (likely) bug.

So, what then? We just need need to `call register_ipv4`, etc, for `IPA_SIP_VIPA` too? Is that the fix?

**Comment by rgschmi** [comment]
I just tried the new qeth fix, and I see all but one of my VIPA addresses being registered.  However, one VIPA (10.0.0.23) was not registered, even though it is in my home list.  It is a bit special because it is shared across LPARS, but I believe it should still have been registered.  I did a dynamic add of a virtual interface, 10.0.0.24 just to make sure that still worked, and it was successful.  This is not a critical issue for me as it works on linux with LCS.

I can include a copy of my profile if needed, but here are the important lines:

PORT
3023 TCP TN3270A   SHAREPORTWLM BIND 10.0.0.23 ;BIND PORT 

 VIPADYNAMIC                                             
    VIPADEFINE       255.255.255.0   10.0.0.23                    
    VIPADIST DEFINE DISTM ROUNDROBIN 10.0.0.23 PORT 3023 
        DESTIP ALL                                       
 ENDVIPADYNAMIC  

OSA support is looking better all the time!

Here is my home list and the Hercules panel.

 ----------      --------        ----     ------ ------
 Default         192.168.20.100  LNK3000  1500   <none>
 Default         192.168.20.100  LNK3004  1500   <none>
 10.0.0.2        <direct>        VLINK1   65535   HOST 
 10.0.0.23       <direct>        VIPL0A00 1500    HOST 
 127.0.0.1       <direct>        LOOPBACK 65535   HOST 
 172.16.0.20     <direct>        EZASAMEM 65535   HOST 
 192.168.20.0    <direct>        LNK3000  1500   <none>
 192.168.20.10   <direct>        VLINK10  65535   HOST 
 192.168.20.12   <direct>        LNK3000  1500    HOST 
 192.168.20.13   <direct>        LNK3004  0       HOST 

HHC03997I 0:3001 OSA: tun0: using drive MAC address 96:7a:59:e5:d2:bf
HHC03997I 0:3001 OSA: tun0: using drive IP address fe80::967a:59ff:fee5:d2bf
HHC03805I 0:3001 OSA: tun0: Register guest IP address 192.168.20.12
HHC03805I 0:3001 OSA: tun0: Register guest IP address 172.16.0.20
HHC03805I 0:3001 OSA: tun0: Register guest IP address 10.0.0.2
HHC03805I 0:3001 OSA: tun0: Register guest IP address 192.168.20.10
HHC03805I 0:3001 OSA: tun0: Register guest IP address 192.168.20.13
HHC03805I 0:3001 OSA: tun0: Register guest IP address 10.0.0.24

**Comment by mcisho** [comment]
Qeth registers IP addresses that are said to be default or vipa, I wonder if dynamic vipa is said to be something else? The next time you IPL your guest, can you issue a Hercules 'qeth debug on all updown' command before the IPL and attach the output, please.

**Comment by rgschmi** [comment]
Sorry for the delay in responding.

I did a slight modification of my TCPIP profile to eliminate any possible sysplex related issues.  Now when I start TN3270A, 10.0.0.23 gets created and 

when I stop TN3270A, 10.0.0.23 gets deleted.

  3023 TCP TN3270A   SHAREPORTWLM BIND 10.0.0.23 ;BIND PORT    


 VIPADYNAMIC                                              
    VIPARANGE        255.255.255.255 10.0.0.23            
;   VIPADEFINE       255.255.255.0   10.0.0.23            
;   VIPADIST DEFINE DISTM ROUNDROBIN 10.0.0.23 PORT 3023  
;       DESTIP ALL                                        
 ENDVIPADYNAMIC                                           


I've attached the Hercules log and a snippet from the TCPIP log showing 10.0.0.23 being created and deleted.  I can see in the Hercules log that there 

was an unsupported request to register 10.0.0.23:

10:22:30 HHC03991D 0:3001 OSA: RRH_TYPE_IPA: IPA_CMD_SETASSPARMS (IPv4): NOT SUPPORTED (0x0204): Request
10:22:30 HHC03981D 0:3001 OSA: TH : +0000< 00E00000 00000014 00000014 0000009C  ................  .\..............
10:22:30 HHC03981D 0:3000 OSA: TH : +0010> 0FFC0001                             ....              ....            
10:22:30 HHC03981D 0:3001 OSA: TH : +0010< 10000001                             ....              ....            
10:22:30 HHC03981D 0:3000 OSA: RRH: +0000> 00000000 C17E0001 00000000 00000000  .....~..........  ....A=..........
10:22:30 HHC03981D 0:3001 OSA: RRH: +0000< 00000000 C1030001 00000000 00000000  ................  ....A...........
10:22:30 HHC03981D 0:3000 OSA: RRH: +0010> 0024005C 00005C05 0001010B 00000000  .$.\..\.........  ...*..*.........
10:22:30 HHC03981D 0:3001 OSA: RRH: +0010< 0024005C 00005C05 D8C5E3F5 00000000  .$.\..\.........  ...*..*.QET5....
10:22:30 HHC03981D 0:3000 OSA: RRH: +0020> 00000000                             ....              ....            
10:22:30 HHC03981D 0:3001 OSA: RRH: +0020< 00000000                             ....              ....            
10:22:30 HHC03981D 0:3000 OSA: PH : +0000> 0100005C 00000040                    ...\...@          ...*...         
10:22:30 HHC03981D 0:3001 OSA: PH : +0000< 0100005C 00000040                    ...\...@          ...*...         
10:22:30 HHC03981D 0:3000 OSA: IPA: +0000> B100000D 00000100 01010004 00005D71  ..............]q  ..............).
10:22:30 HHC03981D 0:3001 OSA: IPA: +0000< B300000E 00000100 01010004 00000000  ................  ................
10:22:30 HHC03981D 0:3000 OSA: IPA: +0010> 00000451                             ...Q              ....            
10:22:30 HHC03981D 0:3001 OSA: IPA: +0010< 00000000                             ....              ....            
10:22:30 HHC03981D 0:3000 OSA: Cmd: +0000> 0A000017 FF000000 00000002 00000000  ................  ................
10:22:30 HHC03981D 0:3001 OSA: Cmd: +0000< 00000001 00440204 00000000 001F0000  .....D..........  ................
10:22:30 HHC03981D 0:3000 OSA: Cmd: +0010> 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3001 OSA: Cmd: +0010< 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3000 OSA: Cmd: +0020> 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3001 OSA: Cmd: +0020< 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3001 OSA: Cmd: +0030< 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3000 OSA: Cmd: +0030> 00000000 00000000 00000000 00000000  ................  ................
10:22:30 HHC03981D 0:3001 OSA: Cmd: +0040< 00000000 00000000                    ........          ........        
10:22:30 HHC03981D 0:3000 OSA: Cmd: +0040> 00000000 00000000                    ........          ........        

  TCPIP LOG:

09.22.28 STC00015  EZD1205I DYNAMIC VIPA 10.0.0.23 WAS CREATED USING BIND BY TN3270A ON TCPIP             
09.22.33 STC00015  S FTPD                                                                                 
09.22.33 STC00015  S PORTMAP                                                                              
09.22.33 STC00015  S OMPROUTE                                                                             
09.22.41 STC00015  EZZ7475I ICMP WILL IGNORE REDIRECTS DUE TO ROUTING APPLICATION BEING ACTIVE            
09.24.39 STC00015  EZD0101I NETSTAT CS V2R1 TCPIP 975   975                                               
   975             HOME ADDRESS LIST:                                                                     
   975             LINKNAME:   EZASAMEMVS                                                                 
   975               ADDRESS:  172.16.0.20                                                                
   975                 FLAGS:                                                                             
   975             LINKNAME:   VIPL0A000017                                                               
   975               ADDRESS:  10.0.0.23                                                                  
   975                 FLAGS:                                                                             
   975             LINKNAME:   LOOPBACK                                                                   
   975               ADDRESS:  127.0.0.1                                                                  
   975                 FLAGS:                                                                             
   975             INTFNAME:   VLINK1                                                                     
   975               ADDRESS:  10.0.0.2                                                                   
   975                 FLAGS:  PRIMARY                                                                    
   975             INTFNAME:   VLINK10                                                                    
   975               ADDRESS:  192.168.20.10                                                              
   975                 FLAGS:                                                                             
   975             INTFNAME:   VLINK10                                                                 
   975               ADDRESS:  192.168.20.10                                                           
   975                 FLAGS:                                                                          
   975             INTFNAME:   LNK3000                                                                 
   975               ADDRESS:  192.168.20.12                                                           
   975                 FLAGS:                                                                          
   975             INTFNAME:   LNK3004                                                                 
   975               ADDRESS:  192.168.20.13                                                           
   975                 FLAGS:                                                                          
   975             INTFNAME:   LOOPBACK6                                                               
   975               ADDRESS:  ::1                                                                     
   975                 TYPE:   LOOPBACK                                                                
   975                 FLAGS:                                                                          
   975             8 OF 8 RECORDS DISPLAYED                                                            
   975             END OF THE REPORT                                                                   
09.25.01 STC00015  EZD1298I DYNAMIC VIPA 10.0.0.23 DELETED FROM TCPIP                                  
09.25.01 STC00015  EZD1207I DYNAMIC VIPA 10.0.0.23 WAS DELETED USING CLOSE API BY TN3270A ON TCPIP     
09.25.19 STC00015  EZD1205I DYNAMIC VIPA 10.0.0.23 WAS CREATED USING BIND BY TN3270A ON TCPIP          
[herclog.txt](https://github.com/SDL-Hercules-390/hyperion/files/3243936/herclog.txt)

**Comment by mcisho** [comment]
The IP address 10.0.0.23 was registered with the following IPA_CMD_SETIP request (superflous stuff removed):-
IPA: +0000< B100000D 00000100 01010004 00000000
IPA: +0010< 00000000
Cmd: +0000< 0A000017 FF000000 00000002
The Cmd line contains the IP address, the subnet mask and the command type. The Linux source code defines the command type QETH_IPA_SETIP_TAKEOVER_FLAG = 0x02L, which QETH currently doesn't handle. Due to an oversight QETH returned an OK return code, making z/OS think the IP address had been successfully registered.

I am about to disappear for a month, so won't be fixing this 'til I return, unless someone else wants to do the fix in the meantime.

QETH doesn't support ARP or anything to do with ARP. The IPA_CMD_SETASSPARMS (IPv4): NOT SUPPORTED (0x0204): is (using the Linux source name) an IPA_CMD_ASS_ARP_QUERY_STATS request, which is issued by z/OS at regular intervals (every 30 seconds if I remember correctly).

**Comment by Fish-Git** [comment]
> I am about to disappear for a month, so won't be fixing this 'til I return, unless someone else wants to do the fix in the meantime.

I will _try_ to look into this while you are gone, but no guarantees.

To expedite things, can you (if you know) point me to the approximate spot (line number) in QETH code where you believe the problem is?

Great work, Ian! Thanks!

**Comment by rgschmi** [comment]
Thanks for the quick response.  As you can tell by how long it took me to gather documentation, I'm not desperate for a fix, but am willing to test as soon as one is available.

**Comment by mcisho** [comment]
Fish, the change is actually quite simple. Line 1730 of qeth.c currently says:-

if (flags == IPA_SIP_DEFAULT || flags == IPA_SIP_VIPA)

but it needs to say:-

if (flags == IPA_SIP_DEFAULT || flags == IPA_SIP_VIPA || flags == IPA_SIP_TAKEOVER)

And that's it. An else that sets a not OK return code would be nice, but not essential. IPA_RC_UNSUPPORTED_SUBCMD seems appropriate.

**Comment by rgschmi** [comment]
I just patched qeth.c with mcisho's fix and it works!  I can now ping 10.0.0.23!

Thanks, guys.

**Comment by Fish-Git** [comment]
> Fish, the change is actually quite simple ...

Thanks, Ian!

Your recommended fix has been committed (0cb7ae037ff232503ba2b5296a6838e1d7f86c27). (I gave you credit for it; even though it was _committed_ by me, it shows _you_ as the author.)

I believe this successfully closes this GitHub issue.

Thanks, guys!
