### ISSUE TITLE
HHC00399I CCKD file: internal cckd trace   

### ISSUE THREAD

**Issue by werner02815** [SDL-Hercules-390/hyperion#213]
Running following hercules version:

```
HHC01413I Hercules version 4.2.0.9614-SDL-g39ae7078 (4.2.0.9614)
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and other
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar 23 2019 at 14:25:51
```

After running hercules for some hours with a heavy zOS process i got millions of lines like:

```
HHC00399I CCKD file: internal cckd trace
HHC00398I 17:29:56.636462 0:310A> cckd64_write_trkimg(2701): file[0] trk
HHC00398I 17:29:56.636466 0:310A> cckd64_get_space(1492): get_space len
HHC00398I 17:29:56.636470 0:310A> cckd64_get_space(1520): get_space aten
HHC00398I 17:29:56.636474 0:310A> cckd64_write(468): file[0] fd[237] wri
HHC00398I 17:29:56.636634 0:310A> cckd64_write_l2ent(2597): file[0] l2[2
...
```

I had to hard stop hercules (power off) because logfile filled up to 10GB and my hard disk space exhausted. After powering on hercules I got some space map errors which were corrected automatically and started same process again and it succeed.

Nevertheless I kindly ask to check what is causing this issue.

* [log.txt](https://github.com/SDL-Hercules-390/hyperion/files/3247258/log.txt)

**Comment by werner02815** [comment]
[log.txt](https://github.com/SDL-Hercules-390/hyperion/files/3247258/log.txt)

**Comment by werner02815** [comment]
same issue 2 times again. But no idea on how to recreate. What i am seeing that CCK64 devices are quite filled (about 10GB).

**Comment by Fish-Git** [comment]
It appears existing CCKD code will, under certain circumstances, automatically create (and print, obviously!) internal trace table entries upon detecting certain errors. It appears to do this in many different places throughout CCKD code, so it's difficult (if not impossible) to tell precisely what CCKD is complaining about. But one thing is very clear: _it **IS** complaining about something!_ &nbsp; (i.e. there _is_ some type of CCKD related "file damage" with the dasd image file(s) in question.)

> HHC01413I Hercules version 4.2.0.9614-SDL-g39ae7078 (4.2.0.9614)
> ...
> HHC01415I Build date: Mar 23 2019 at 14:25:51

This _might_ not be a good version of SDL Hyperion to be testing with. I can see according to the commit log that several changes/fixes have been made since then related to dasd/cckd handling that _might_ be related to whatever CCKD is currently complaining about regarding your dasd images. I might need to build you a newer snapshot (test version).

**Comment by werner02815** [comment]
I have now converted all my disks to CCKD64 format (only to have all in a common format). Afterwards i run cckdcdsk64 -3 on all devices. It reported/corrected some freespace errors. 

running with level -4 i see millions of messages in form of 
....
HHC00372I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: trk[12164] recovered offset 0x0000000007934AAF len 121
HHC00372I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: trk[12165] recovered offset 0x0000000007934B28 len 63
HHC00373I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: 11003 trk images recovered
HHC00377I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: free space rebuilt
HHC00380W 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: cckdcdsk64 level 4 complete; rc=1
HHC00007I Previous message from function 'main' at cckdcdsk64.c(161)

Running same check again i get all these messages again. So i think this level 4 check is either incorrect or does not really do any update. Could you please confirm.

Nevertheless: best we can do is that you create a new snapshot so i can rerun this whole process (running some days)

**Comment by Fish-Git** [comment]
> Afterwards I run `cckdcdsk64 -3` on all devices. It reported/corrected some freespace errors.

Yes, I believe that was one of the problems was recently fixed. I will need to build you a new snapshot to test with.  Give me a few minutes(?)...

> Running with level -4 I see millions of messages in form of:
> Running same check again I get all these messages again.

I would recommend against ever running a level -4 ckdsk. Level -4 is meant only for the most extreme of circumstances. Stick with level -3 instead.  (But wait until I build you a new pre-built to test with!)

> Could you please confirm?

I converted _**ALL**_ of my dasd images for _**ALL**_ of my Hercules guests over to CCKD64 format _months and months_ ago (i.e. when I first released cckd64!) and have been using cckd64 _exclusively_ ever since, and have experienced virtually no problems whatsoever (and I run tests using z/OS 1.10, z/OS 2.1, z/OS 2.3, z/VM 6.3, DOS/VS, VM370, etc) _all_ the freaking time, i.e. _constantly_).

Not long ago I also re-converted all of my original 32-bit CCKD dasds (which I still have) to CCKD64 format (both base images as well as all shadow files) using convto64, and then tested again with those new cckd64 images (as well as running `cckdcdsk64 -3`) just to make sure nothing was damaged, etc, and everything looks rock solid to me. &lt;shrug&gt;

I will build you a new snapshot of the latest and greatest soon-to-be-release version 4.2 of SDL Hyperion to test with. But like I said, give me a few minutes...

**Comment by Fish-Git** [comment]
New 4.2 snapshot:

* [Hercules-4.2.0.9686-SDL-g0cb7ae03-x64.zip](https://github.com/SDL-Hercules-390/hyperion/files/3263663/Hercules-4.2.0.9686-SDL-g0cb7ae03-x64.zip)

_Please re-convert **all** of your dasd images using this new version!_

That is to say, use the `convto64` utility (recommended) from the above snapshot to convert all of your existing 32-bit CCKD dasd images to the new 64-bit CCKD64 format (both your base images as well as any shadow files you might have), and use those new converted images to test with.

You can (may) use the `dasdcopy64` utility (the _new_ one!) instead if you wish, but in my experience `convto64` does a better job. (It's much faster; `dasdcopy` is _very slow_ in my experience, and `convto64`  does the same job(*) but much faster.)

Once you have converted all of your dasds to CCKD64 format (using the new snapshot above), re-run all of your tests again and let me know immediately if you experience any problems. (You shouldn't!)

Thanks.

___
(*) The only difference (from a user perspective) between dasdcopy and convto64 is, dasdcopy: 1) automatically merges any existing shadow file data into the resulting output image file so that when you're done, the new image can be (_must_ be) used _without_ any shadow file (although you can create a new fresh one afterwards if you wish), and 2) it uses Hercules's existing CCKD/CCKD dasd code to perform the convesion (which is why it is so slow).

The `convto64` utility however, 1) performs the conversion _directly_ and is therefore _much_ faster, and 2) does _not_ support merging of shadow file data. Instead, `convto64` converts either base dasd images _**OR**_ shadow file images _directly_ to the new CCKD64 format, so if you had a base image and, say for example, two shadow files (shadow 1 and shadow 2) before the conversion, then you have to convert all three images (base and both shadows) using convto64 so that when you're done, you still have a base image and two shadow files but they're all in the new CCKD64 file format.

Given how slow/clunky dasdcopy is, I personally recommend using the convto64 utility instead, but the choice is up to you.

Let mw know how it goes.

**Comment by werner02815** [comment]
i will perform all these actions and come back with results, but this will take some days.
thanks for your support !

**Comment by werner02815** [comment]
Unfortunately i am coming back again with bad new earlier than expected. I have run following procedure:
- perform convto64 for all devices (no error reported)
- run cckdcdsk64 -3 for all converted devices. some of them reported rc=1 like:
_U:\Hercules\SDM23\Disk>C:\hercules\Hercules-4.2.0.9686\cckdcdsk64.exe -3 U:/Hercules/SDM23/Disk/CICS/H5CI00 
HHC02499I Hercules utility cckdcdsk64 - CCKD64 dasd image verification - version 4.2.0.9686-SDL-g0cb7ae03
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jun  6 2019 at 14:53:49
HHC00379I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: starting cckdcdsk64 level 3...
HHC00363W 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: cdevhdr inconsistencies found, code 0001
HHC00007I Previous message from function 'cckd64_chkdsk' at cckdutil64.c(1246)
HHC00368W 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: free space errors detected
HHC00007I Previous message from function 'cckd64_chkdsk' at cckdutil64.c(1697)
HHC00377I 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: free space rebuilt
HHC00380W 0:0000 CCKD file U:/Hercules/SDM23/Disk/CICS/H5CI00: cckdcdsk64 level 3 complete; rc=1
HHC00007I Previous message from function 'main' at cckdcdsk64.c(161)_
- after this i run cckdcdsk64 -3 again for all devices. all checks ended with rc=0
- finally i started my long running zOS process again and once again got error. Nevertheless trace output looks quite different (see attached extract)
[log.txt](https://github.com/SDL-Hercules-390/hyperion/files/3268442/log.txt)

I will keep system down at the moment. Unfortunately reported device has a size of about 11GB. So it will not be possible to send this to you. But if you give me some instructions on what to check please let me know. I will save this image for additional analysis

Thanks,

**Comment by Fish-Git** [comment]
> * Perform convto64 for all devices (no error reported)
> * Run cckdcdsk64 -3 for all converted devices. some of them reported rc=1 like:

Okay, this is my bad. I probably didn't provide clear enough step by step instructions. I apologize for that. You _should_ have run a `cckdcdsk64 -3` (using the _new_ version!) _before_ running your `convto64`. This ensures that you existing 32-bit CCKD dasd images are in a consistent (good/valid) state _before_ `convto64` attempts to convert them to the new 64-bit CCKD64 format.

If your 32-bit CCKD dasd images are already in an inconsistent (damaged) state, then `convto64` will end up converting the image to an inconsistent (damaged) 64-bit CCKD64 format! (Which is why the `cckdcdsk64 -3` that you ran afterwards showed errors.)

Please try again being sure to run a `cckdcdsk64 -3` (using the _new_ `cckdcdsk64`!) _**before**_ performing the initial `convto64` conversion. (Then of course run another `cckdcdsk64 -3` afterwards like you did, but this time it should hopefully report no errors.)

> Unfortunately reported device has a size of about 11GB, so it will not be possible to send this to you.

It _should_ be possible to upload it to my web FTP site. I believe I have enough room. _HOWEVER_... do not bother to do that with the image you've already saved since it was done wrong (due to my bad instructions! Sorry!).

If the results of the above corrected procedure still results in errors however, _then_ you can FTP upload your dasd image to my web site.

Thanks.

(and sorry about that!)

**Comment by Fish-Git** [comment]
_**\*\*\* CORRECTION! \*\*\***_

The cckdcdsk -3 that you should run on your existing 32-bit CCKD dasd images before doing the convto64 should of course be `cckdcdsk -3` (_not cckdcdsk**64**_ -3!).

That is to say, you need to run the plain 32-bit `cckdcdsk` on your existing 32-bit CCKD dasd images before doing the convto64.

Then _afterwards_, once your've converted them to the new 64-bit CCKD64 format, you should of course use _cckdcdsk**64**_ (the 64-bit version of cckdcdsk) to verify everything is still okay.

**Comment by Fish-Git** [comment]
P.S. It wouldn't hurt to maybe try compressing your existing 32-bit CCKD dasd images beforehand, to eliminate free space (since that seems to be where you problem is), but this is entirely optional.

If you decide to do it, do so _after_ running cckdcdsk to fix any existing inconsistencies:

1. Run `cckdcdsk -3` on all of your existing 32-bit CCKD dasd images to fix any existing problems.

2. Run `cckdcomp` on all of your existing 32-bit CCKD dasd images to remove free space. _(Optional)_

3. Run `cckdcdsk -3` again, to verify cckdcomp worked okay. _(Optional)_

4. Run `convto64` to convert your images to the new CCKD64 format.

5. Run _cckdcdsk**64** -3_ on all of your new CCKD64 images to verify convto64 worked okay. _(Optional)_

6. Run your test again.

**Comment by werner02815** [comment]
thanks for your detailed instructions - i will do all this, but it will take some time.
Nevertheless one question: maybe i have run convto64 for some of my CCKD64 (because i used a common procedure and have not carefully checked before). I have not seen any error, but is it possible that this has caused errors ?

**Comment by Fish-Git** [comment]
> Thanks for your detailed instructions

You're very welcome.

> I will do all this, but it will take some time.

Understood.


> ... question: maybe I have run convto64 for some of my CCKD64 [...]. ... is it possible that this has caused errors?

_Possibly_, but only if you used the old version.

The new version of convto64 is CCKD/CCKD64 agnostic however, so running it again on an image that is already in CCKD64 format should _not (*)_ cause a problem. You will simply end up with the exact same image again(**):

```C
/*-------------------------------------------------------------------*/
/*   This program copies a 32-bit cckd or 64-bit cckd64 base image   */
/*   or shadow file to the new cckd64 format.  The input file must   */
/*   be either a compressed 32-bit cckd format base or shadow file   */
/*   or a compressed 64-bit cckd64 format base or shadow file, and   */
/*   the resulting output will always be a compressed cckd64 format  */
/*   base or shadow file.                                            */
/*                                                                   */
/*   The reason we support converting cckd64 to cckd64 is because    */
/*   a convenient side effect of our conversion is the resulting     */
/*   file ends up being completely compressed, with all of its L2    */
/*   tables in their preferred location.                             */
/*                                                                   */
/*   Another reason is to allow re-running the conversion again      */
/*   in case a newer version of ourselves does something different   */
/*   that the older version didn't and only cckd64 input happens     */
/*   to be available (because you deleted the original 32-bit cckd   */
/*   files after doing your original conversion the first time with  */
/*   the older version of this program).                             */
/*                                                                   */
/*      Usage:  convto64  [-r] [-c] [-q] [-v]  infile  outfile       */
/*                                                                   */
/*   PLEASE NOTE HOWEVER that this is a ONE-WAY CONVERSION! It can   */
/*   only convert 32-bit cckd format or 64-bit cckd64 format dasds   */
/*   to the new cckd64 format, but it CANNOT convert any new cckd64  */
/*   format dasds back to their original 32-bit cckd format!         */
/*-------------------------------------------------------------------*/
```

___
(*)  Presuming of course that the image you're converting is one that was converted with the _same **new** version_ of convto64 that you used before. If you do convto64 using an _older_ version of convto64, and then do it again using a _newer_ version of convto64, then all bets are off!

(**) Ibid.

**Comment by werner02815** [comment]
hopefully my issue is fixed now !
I have successfully run my process 2 times without any issue. It seems that running cckdcomp fixed the problem. In a first step i run procedure without this optional step and i have seen once again all this messages. After this i run cckdcomp and finally performed procedure 2 times without any problem.

For me i looks like cckdcomp has fixed (?) the problem. I have seen a lot of space released for some volumes (also for volume which has reported all these trace entries). So either cckdcomp fixed the problem (caused by any previous release) or data is now rearranged and we no longer come to this place. Please note: my process has created a lot of files on DASD volumes, afterwards i restarted the process which first (logical) deletes these datasets and finally creates them again. It seems that this process creates a lot of free space elements and some logic failed on this.

What is really important for me is that now the problem is fixed for me (or no longer can be recreated).
Thanks for your support

**Comment by Fish-Git** [comment]
> My issue _appears_ to be fixed now!

[...]

> The only important thing for me is that the problem appears to now be fixed. I can no longer recreate the original problem.
> 
> Thanks for your support!

Thank you for the confirmation. Am closing this issue.
