### ISSUE TITLE
Building Hyperion on Linux_s390x

### ISSUE THREAD

**Issue by MaximumJam** [SDL-Hercules-390/hyperion#225]
We are trying to build Hercules Hyperion 4.x source code by several days under a Linux s390x OS, but we encountered many different problems without any significative progress on the various building attempt.

Is there any particular option we should use while configuring to successfully conclude the building of the source code of Hercules Hyperion 4.x on an Ubuntu Linux  18.04.2 LTS (Bionic Beaver) - Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:54:05 UTC 2019 s390x s390x s390x GNU/Linux , 
or the source code is not usable anyway under a zLinux OS?

**Comment by ivan-w** [comment]
> encountered many different problems

Can we have more detail on what "many different problems" is ? hercules should build and work fine on z/linux (s390x).. If it doesn't, it's a bug and should be fixed.

Ps : I just updated config.guess and config.sub so we may want to give it another try

**Comment by Fish-Git** [comment]
@MaximumJam 

Did you see Ivan's question?:

> > ... we encountered many different problems ...
> 
> Can we have more detail on what "many different problems" is? Hercules should build and work fine on z/linux (s390x). If it doesn't, it's a bug and should be fixed.
> 
> ps: I just updated `config.guess` and `config.sub` so you may want to give it another try.

Bottom line:

1. Due to Ivan's update of `config.guess` and `config.sub`, you should re-clone your SDL-Hyperion repository clone and try again.

2. If that doesn't work, then we need **more details** regarding the _specific_ problems you are encountering. As Ivan said, Hercules _should_ build and run just fine on z/Linux (s390x).

If we don't hear back from you (if you don't respond), then we are going to close your issue since there is nothing more we can do to help you resolve it without more detailed information.

Thanks.

**Comment by Fish-Git** [comment]
User failed to respond. Closing.
