### ISSUE TITLE
Use of "extpkg" no longer allows cross compilation and arbitrary architectures

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#257]
It used to be possible to cross compile/build hercules for arbitrary architectures if the libraries and compilers were available.

With the "extpkg" system this has become impossible. The build scripts are now restricted to a closed hardcoded set of cpus and architectures (why ?).. If it is a native build, the CPU can be determined dynamically, if it's a cross build, any arbitrary string should be valid (if it's wrong, the build will fail, but that's all)

For example I can no longer build hercules for... s390x!

And why are these "external" packages. These package have NO other use than for hercules... Therefore I believe they should be put directly in the hercules source tree.

**Comment by Fish-Git** [comment]
> And why are these "external" packages. These package have NO other use than for hercules... Therefore I believe they should be put directly in the hercules source tree.

As to the reason why:

https://github.com/SDL-Hercules-390/hyperion/issues/76 `(https://github.com/SDL-Hercules-390/hyperion/issues/76)`:

> The overall long term goal is to eventually reduce Hercules to just the "engine" responsible for all of the architectural emulation side of things. Everything else would be external to Hercules-proper. This allows new emulators to be more easily written by simply linking the existing Hercules engine with a different set of external components (as well as for each external component to "evolve" separately on their own).

**Comment by Fish-Git** [comment]
> The build scripts are now restricted to a closed hardcoded set of cpus and architectures (why ?)..

Because I screwed up in my design? _&nbsp; &lt;me: sheepish grin&gt;_

At the time the [External Packages concept](https://github.com/SDL-Hercules-390/hyperion/issues/76) was developed I didn't know how to make it work for any arbitrary cpu/architecture/string.

If you know how to do that with CMake, please let me know and I'll adjust our ExtPkg build design to allow for that!

(Is CMake supported on s390x?)

**Comment by ivan-w** [comment]
Oh yes, CMake works on linux on s390x ! I've compiled and run (native and cross compiled) several CMake based projects with a s390x target (for example, LWIP that gives me an IP stack on VM/370).

I believe CMake has all the infrastructure (and I believe it is one of the intrinsic goals of CMake) to determine the target architecture so I believe we should let it decide what to do by itself (basically do nothing for a native build and set CC environment variable if you are doing a cross build or using the non default compiler for your distribution or system).

I therefore believe it is probably a mistake to coerce CMake into using this or that architecture ;)

Just my $0.02 !

**Comment by Fish-Git** [comment]
ADDITIONAL INFORMATION:

> The build scripts are now restricted to a closed hardcoded set of cpus and architectures (why ?)..

Thinking about this some more I think I now remember why I may have designed it that way.

One of my goals with the External Packages design was to have the Hercules repository contain a set of default static libs that it could link with (the crypto/lib, decNumber/lib, SoftFloat/lib and telnet/lib repository subdirectories). These default static libs would be for the most common (popular) architecture (x86_64) so that _most_ of our users would be able to build Hercules _without_ having to build the External Packages for themselves. The repository, as delivered, would contain everything they needed so they would just build Hercules just like normal. No muss. No fuss.

But in order to also support other architectures I needed a way of directing the Hercules build process to _not_ link with the default set of static libraries and to instead link with the static libraries for this other [non-stand, non-typical] architecture, and to do so _without_ "overlaying" (modifying) the existing as-delivered repository defaults. Thus I decided to support "architecturally named" _sub-directories_ that Hercules's build process would link with instead (e.g. crypto/lib/<arch>, decNumber/lib/<arch>, SoftFloat/lib/<arch> and telnet/lib/<arch>).

Thus the build scripts that build the External Package libraries (static libs) as well as the build script that build Hercules itself, needs to know the name of the sub-directory that it needs to link with.

Does that make sense?

**Comment by ivan-w** [comment]
The thing is IMHO, is that a library that is both specific to the engine and required for the engine *IS* de-facto part of the engine. Putting them into separate repositories doesn't make them external packages, it just make it more complicated to build.

Also, on any modern systems in a streamed build system (config/make or cmake or nmake/VS) would only add a couple of seconds of compile time overall to build those.

Having them as static libraries only means that it is possible there may be in the end multiple copies of the same code in other executables while shared libraries/DLLs ensure there is only one copy loaded.

Furthermore, having pre-built binary archives means that add more and more binaries into the hercules source repository... (did I say *SOURCE* ????)

If someone is building hercules from source, I don't think they care about the additional couple of seconds of compilation.

I think separating "utility" functions from "engine" functions could be performed differently. The hercules project overall should at the end be split into specific directories (say as an example : cpu, devices/ (devices/dasd, devices/dasd/ccw, devices/dasd/cckd... etc... you get the idea)) but they shouldn't be in specific github repositories with ad-hoc build instructions. The build process should be integrated and compatible with hercules' own build process. Whether at the end it is CMAKE or automake/autoconf, I don't know (I certainly have nothing against CMAKE)

Thinking out loud here ;)

**Comment by ivan-w** [comment]
Think : 
cf/ (containing impl.c, ipl.c, panel.c, etc..)
cpu/ (containing cpu.c, generalX.c, control.c, etc..)
io/ (containing channel.c)
devices/
    32xx/ containing console.c (327x and 3215 code)
    32xx/telnet/ containing the tn3270 code
   dasd/
       dasd/CKD
       dasd/CCKD
      ..etc..
..etc..
/include (the include files needed by all)
You get the idea !

**Comment by Fish-Git** [comment]
I believe this conversation is getting off track. The original problem report (_this_ issue) has to do with the current inability to build the External Packages for architectures that are not currently "known" (directly supported) by any of the external packages. That is a valid concern and one which needs to be addressed.

_HERE_.

In _this_ GitHub issue.

_**However**_ ... The merits of the current External Package design with respect to _how best to achieve the goal of separating out Hercules's emulation of the architecture from its other non-architectural-related components_ (e.g. the panel presentation layer, etc) should be discussed in [**GitHub Issue #76: "Externalize non-engine related Hercules components"**](https://github.com/SDL-Hercules-390/hyperion/issues/76), _**and not here.**_

What you've [written](https://github.com/SDL-Hercules-390/hyperion/issues/257#issuecomment-533880219) [above](https://github.com/SDL-Hercules-390/hyperion/issues/257#issuecomment-533880755) really belongs in issue 76, not here.

**Comment by Fish-Git** [comment]
@ivan-w, please also see [David's comment in pull request #197 **"Make console more faithful"**](https://github.com/SDL-Hercules-390/hyperion/pull/197#issuecomment-477879615).

**Comment by ivan-w** [comment]
I understand.. The fix was good. a telnet library is fine. But this telnet library has only ONE purpose - to work in hercules. You cannot build hercules WITHOUT this library and this library has no purpose OUTSIDE of hercules. So it is not really external in any sense other that it uses a different build procedure and resides in a different repository.

**Comment by ivan-w** [comment]
If we had an "OEM" interface, of course we could have external packages - with different "vendors" proposing various implementation of control units or auxiliary processors and whatnot. But we do not have that. There is no published interface - all implementations are ad-hoc. So the notion of external packages is moot.

**Comment by Fish-Git** [comment]
> But this telnet library has only ONE purpose: to work in hercules.

So?

> You cannot build hercules WITHOUT this library and this library has no purpose OUTSIDE of hercules.

So?

> So it is not really external in any sense ...

Semantics.

> ... resides in a different repository.

Which is the whole point of the External Package design!

Should someone create/invent a better mouse trap (e.g. a completely different emulated dasd design or a completely different way of displaying Hercules messages or a completely different way of implementing the channel subsystem, etc), then they could easily do so without having to deal with the closely integrated spaghetti code that is our current Channel Subsystem design, Panel design, etc! As long as they adhere to what API we come up with for how the emulator-proper communicates with that component, then they are free to design/code their external component however they want! (Possibly in a completely different programming language!)

That's the _whole point_ of the External Package design!

**Comment by ivan-w** [comment]
But it doesn't add any value - it just makes thing harder to build and brings no benefit

**Comment by ivan-w** [comment]
We FIRST define the APIs and define Interfaces and THEN we externalize... Not the other way around !

**Comment by ivan-w** [comment]
For the "telnet" library, there shouldn't be an API.. we should have an OEM channel API that allows one to create a 3x74 Control unit using CCW/CSW/Data Transfer passing emulating a BLKMPX/ESCON/FICON channel using some defined data transfer method and protocol... That's how I/O should have been done from the get go. (It would also solve a couple of architecture errors, but that's another story)

**Comment by ivan-w** [comment]
If the 3174 emulation is already in hercules, the telnet library should ALSO be integrated.

**Comment by Fish-Git** [comment]
> We FIRST define the APIs and define Interfaces and THEN we externalize... Not the other way around !

Without an externalized component there would be no NEED to define an API/Interface - which is exactly where we are today! Each of our "components" is free to directly call into/access any other part of Hercules, resulting in a tightly integrated convoluted mess! I'm trying to break out of that vicious cycle.

**Comment by ivan-w** [comment]
But if a component is *REQUIRED* to build it is NO longer an external component. It is becomes a pre-requisite which is an ad-hoc component. So it is NOT an external component. It is a required component that is only used for the build of the product which has no alternative.

**Comment by Fish-Git** [comment]
> If the 3174 emulation is already in hercules, the telnet library should ALSO be integrated.

One thing at a time!&nbsp;`;-)`

All device emulation ("device handlers", including 3174, etc) should _also_ be externalized. This would make it much easier for others to contribute code that supports new hardware devices that Hercules currently does not support.

Right now our device handler design _SUCKS_ because it is so closely/tightly integrated into Hercules (DEVBLK, etc). I want to _fix_ that!

**Comment by Fish-Git** [comment]
> But if a component is _REQUIRED_ to build it is NO longer an external component. It is becomes a pre-requisite which is an ad-hoc component. So it is NOT an external component. It is a required component that is only used for the build of the product which has no alternative.

Again, semantics!

**Comment by ivan-w** [comment]
Nope.. Operational issue. NOT semantics ! I Can no longer build and I have to jump through hoops to do something that was VERY easy prior to the structural design.

**Comment by ivan-w** [comment]
Before : 
git clone...
sh autogen.sh
configure
make
make install
...
All done...

Now: 
git clone
sh autogen.sh
git clone the external packages into various directories
Build the external packages using some newer version of cmake which I also have to build and which requires some strange flags which depend on the system I am running on, the architecture I am running on which I have to guess through some arcane magic.
configure using some extra flag to indicate packages are
make
make install

**Comment by Fish-Git** [comment]
> I can no longer build

Which is what we need to fix.

> and I have to jump through hoops

Building the "external packages" (let's not get into the name thing, please!) is hardly "jumping through hoops" IMO.

**Comment by Fish-Git** [comment]
> git clone the external packages into various directories
> Build the external packages using some newer version of cmake which I also have to build and which requires some strange flags which depend on the system I am running on, the architecture I am running on which I have to guess through some arcane magic.
> configure using some extra flag to indicate where the packages I have built in the previous steps are

Which you only need to do ONCE AND NEVER AGAIN.

**Comment by ivan-w** [comment]
I say - put those "external" libraries back into hercules, build them when doing a "make" without any extra step needed. When an API is properly defined and there are alternatives then YES - Let's have a possibility for alternative packages.

**Comment by Fish-Git** [comment]
> Which you only need to do ONCE AND NEVER AGAIN.

Once the external libraries are built, from then on the build process IS IDENTICAL TO WHAT IT WAS BEFORE:

* git clone...
* sh autogen.sh
* configure
* make
* make install

(And you don't even need to do all that either! Only make and make install are really needed if no build options are being changed!)

**Comment by ivan-w** [comment]
But I *WANT* to build those libraries with MY own flags, for my OWN architecture... with my own compiler...

**Comment by ivan-w** [comment]
the telnet library is REQUIRED and is an AD-HOC library... it is therefore part of hercules ! It is part of my build.. I want to use MY FLAGS and MY architecture

**Comment by Fish-Git** [comment]
> I say - put those "external" libraries back into hercules, build them when doing a "make" without any extra step needed. When an API is properly defined and there are alternatives then YES - Let's have a possibility for alternative packages.

Okay, NOW you're making sense!  That's a good idea.  NOW I'm beginning to see why you suggested using subdirectories, etc. Your suggestion makes sense now. Thanks!

**Comment by ivan-w** [comment]
Let's cool down ;) I am sorry.. you know how hotblooded I can get ;)

**Comment by Fish-Git** [comment]
> Let's cool down ;) I am sorry.. you know how hotblooded I can get ;)

Me too! :)

**Comment by ivan-w** [comment]
Ideally (for I/O anyway) would be to have a generic Channel subsystems, Control Units which drive devices.. But this means having to implement some form of UCWs for S/370 and IOCP/IOCDS for ESA and above.. I have been dreaming about this for the last 15 years (well, ever since I discovered hercules)

**Comment by Fish-Git** [comment]
I admit my current design may not be the best (I'm open to suggestions!), but I hope you at least appreciate its overall _goal!_

**Comment by Fish-Git** [comment]
> Ideally (for I/O anyway) would be to have a generic Channel subsystems, Control Units which drive devices.. But this means having to implement some form of UCWs for S/370 and IOCP/IOCDS for ESA and above.. I have been dreaming about this for the last 15 years (well, ever since I discovered hercules)

I may not have been dreaming about it for quite as long as you, but yes, I have been wanting to do something like that for a _very long_ time now too! The current "External Packages" concept was my first step experiment of starting on that path.

**Comment by ivan-w** [comment]
I think at one point, a decade ago, I starting looking into a generic channel implementation that involved a completely externalized I/O subsystem (the channel is still internal, it's part of the architecture - but once you go out, it's OEM - basically one can build its own drivers and implementations).. think ACTUAL BUS-TAG/ESCON/FICON or some out of its mind person creating a crazy control unit (Maybe create a 3705/3720/3725/3745 emulator and load an NCP into it)... But in the end, the regular out of the mill hercules should be able to run by a single pull/build/run (IMHO)

**Comment by Fish-Git** [comment]
@ivan-w 

Ivan,

I have committed a fix(?) to all 4 External Packages to provide s390x support. Please retry and let me know whether it works(*) or not. Thanks!

(*) I don't know how to test it! If you can maybe send me some information OFFLINE on how to do whatever it is you're trying to do, then I _might_ be able to test it for myself! Thanks!

**Comment by ivan-w** [comment]
Nothing secret ! Just trying to run hercules under z/linux under hercules (or qemu-tcg) (for no other purpose than I should be able to do it)

**Comment by Fish-Git** [comment]
> ... Hercules under z/Linux under Hercules ...

Hmm... Okay. I don't think I have a z/Linux Hercules yet. I'll have to give a try doing that. Any hints or suggestions you want to pass along before I try? Like where to get the install media, suggested install options, etc?

Thanks!

**Comment by Fish-Git** [comment]
p.s. You keep weird hours! Almost as bad as me! :)

**Comment by ivan-w** [comment]
Ah ah.. 7:30 AM here ;) Had to make some coffee for my dear wife who is having an early start today.

Running z/Linux under hercules isn't that hard... You can get a debian version from debian.org (you only need 3 files : kernel.debian, parmfile.debian, initrd.debian) - set up a Layer 2 QETH using tap and optionally a bridge (linux host) OR let your OS handle it (Windows host), create one or more 3390 files, create an OMA tape using the 3 files above, IPL it and off you go. I guess I should make a howto on that !

The install takes a bit of time (about 1 hour or so).

The procedure with qemu-tcg (TCG is a z/Arch only emulator but being a JIT compiler is about 2 to 3 times faster than herc but can only run z/Linux - no z/VM, z/OS or whatnot) is slightly different (no CKD support; no QETH support - just para-virtualized devices) but in the end - the results are the same.

**Comment by ivan-w** [comment]
Oh.. And last thing. What I would *really* like (but it's only a wish) is that hardcoded architectural modes just disappear.. cmake is very capable of making the determination on its own. Those packages are pure C and should be perfectly portable to ANY old, current and future architectures for which a C compiler exists - and this should also allow cross compilation even across architectures and OSes.

**Comment by Fish-Git** [comment]
> ... hardcoded architectural modes just disappear.

The only reason it has hardcoded architectures today is because I didn't fully think things out when I was designing it. I wanted the default static libs for the most common Hercules architecture (32/64-bit Intel) to be part of the repository so that _most_ users only had to clone the Herc repo and they would have everything they needed to then build and go, _without_ having to mess with any of the External Packages crap _at all_. Only if a user wanted to build Herc for a "non-standard" (less common) host architecture would they then need to have a non-repo directory where to place their external package libs into so that Herc could then link with that directory instead of the distributed repo default.

But I didn't stop to think that this "non-standard" architecture non-default directory (containing the foreign architecture external package static libs that Herc should instead link with) could have _any_ name at all (e.g. `xxx`) and be placed _anywhere_ too. At the time I designed it, my mind was stuck thinking it had to have the same name as the architecture. I don't know why I was thinking that (I think I might have seen some Linux kernel `#include` libs or some compiler link libs with architectural names or something), but that's the reason for having the hardcoded architectures: because that's what I used as the directory name that Herc should link with instead of its x86 default.

Stupid I know, but that's where my mind was at when I designed it.

Hindsight is always 20-20 as they say.

Iy might not be _too_ difficult for me to fix that, so that we support just "two" architectures: our default x86 Intel and "anything else". That should eliminate today's hardcoded architectures and fix your issue too, allowing users to build Herc for _any_ architecture that currently exists, existed in the past, or might exist in the future.

Let me think about that...

**Comment by Fish-Git** [comment]
> create an OMA tape using the 3 files above

How? I know what an OMA tape is and can easily create one, but which file comes first, second, third? And should there be any tapemarks between them? Etc! Just "create an OMA tape with those 3 files" isn't enough information!

**Comment by ivan-w** [comment]
Something like that :
...
@TDF
/home/ivan/hercules/systems/DEB001/kernel.debian FIXED RECSIZE 80
/home/ivan/hercules/systems/DEB001/parmfile.debian TEXT
/home/ivan/hercules/systems/DEB001/initrd.debian FIXED RECSIZE 80
...
Adjust as needed ;)

**Comment by Fish-Git** [comment]
> I guess I should make a HOWTO on that!

Found the following two URLs in one of my old archive folders:

* [Installing Debian GNU/Linux under the Hercules emulator](http://stevesdebianstuff.org/hercules.htm)
* [Installing Debian under Hercules](http://www.josefsipek.net/docs/s390-linux/hercules-s390.html)

They look a bit dated (documenting the procedure using a much older version of Hercules), but I'm sure they're both accurate enough that any reasonably intelligent person should have no problems following it.

If you want to create yet another one, have at it!&nbsp;`:)`

_(Hmmm... maybe we should document the URLs for such helpful HOWTOs by our users in our documentation somewhere? Maybe in F.A.Q. question 2.08?

* [2.08 Where can I obtain Linux/390 ?](https://sdl-hercules-390.github.io/html/hercfaq.html#2.08)

**Comment by Fish-Git** [comment]
@ivan-w 

FYI: I have recently committed some missing fixes for s390x support to the `extpkgs.sh` script (in the "gists" repository, used to build the external packages) and to Hercules's `configure.ac` as well that now allows Hercules to be successfully built for s390x architecture.

I am going to close this issue at this time since your inability to build Hercules for s390x was the _primary_ (main) reason for creating this GitHub Issue.

We can argue about the merits of the current "External Packages" design some other day and in some other place.

Cool?
