### ISSUE TITLE
Shared DASD failure if server is downlevel

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#266]
I just upgraded to **4.3.999.0-SDL-ge7354375-modified** and now have problems accessing my shared disk, which resides on a Raspberry pi 3 running OPENSUSE and **Hercules 3.11**.  I suspect there has been a change that makes the two releases incompatible. 

Hercules error messages are:

<pre>
HHC00726E 0:8007 Shared: remote <b>error F0-Eb: invalid query request</b>
HHC0007I Previous message from function 'clientRecv' at shared.c(1442)
HHC00716S 0:8007 Shared: <b>error retrieving serial number</b>
HHC0007I Previous message from function 'shared_ckd_init' at shared.c(286)
HHC00401E 0:8007 CKD file 192.168.1.10::8007: open error: not found
HHC0007I Previous message from function 'ckd_dasd_init_handler' at chkdasd.c(249)
HHC01463E 0:8007 device initialization failed
</pre>

**Comment by Fish-Git** [comment]
Thank you for reporting this, Bob!

Commit df0f6d26725236bcd9ef254a2d11b48232c1d3b3 accidentally introduced an incompatibility with older shared dasd servers (e.g. shared dasd servers older than version 0.2, such as e.g. Hercules 3.11 running shared dasd server version 0.1, etc) wherein if the server was 0.1 (e.g. Hercules 3.11) but the client was 0.2 (e.g. SDL Hyperion 4.x), the opening of dasds would fail because the 0.2 client (herc 4.x) was sending a "query serial number" request to the 0.1 server (Herc 3.11) which the 0.1 server (Herc 3.11) didn't understand.

The fix is to simply adjust the 0.2 client (SDL Hyperion 4.x) to _**not**_send queries for the serial number to servers older than 0.2.

This has been fixed in commit 55d369c86771cd9299a01672115798bf67ce51b4. Please do a pull (or re-clone) for your 4.3.999.0-SDL client, rebuild and retry. It should work fine now.

Closing.

**Comment by rgschmi** [comment]
It works! Life is good! Thanks!
