### ISSUE TITLE
dev->hnd->halt in CSCH functionality not called for CTCE devices

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#273]
I believe the CSCH instruction fails to call `dev->hnd->halt` in channel.c when the device is neither busy nor startpending. With the following temporary changes, problems I encountered with the "reset" functionality for CTCE devices completely disappeared : 

```diff
--- /home/hercules/Qsync/Source/Originals/SDL-hyperion/channel.c	2019-12-06 12:53:48.000000000 +0100
+++ /home/hercules/SDL-hyperion/channel.c	2019-12-30 18:24:46.294069001 +0100
@@ -1735,8 +1735,11 @@
     UNREFERENCED( regs );
 
     if (CCW_TRACE_OR_STEP( dev ))
+#define HHC91331 "%1d:%04X CHAN: clear subchannel; BUSY=%d STARTPENDING=%d SCSW3_AC_SUSP=%d"
         // "%1d:%04X CHAN: clear subchannel"
-        WRMSG( HHC01331, "I", LCSS_DEVNUM );
+        WRMSG( HHC91331, "I", LCSS_DEVNUM
+        , dev->busy, dev->startpending, (dev->scsw.flag3 & SCSW3_AC_SUSP)
+                                          );
 
 #if defined( _FEATURE_IO_ASSIST )
     if (1
@@ -1759,6 +1762,7 @@
 #if defined( OPTION_SHARED_DEVICES )
         && dev->shioactive == DEV_SYS_LOCAL
 #endif
+    ) || ( dev->devtype == 0x3088 /* CTCE devices always need dev->hnd->halt  @PJJ */
     ) || dev->startpending)
     {
         /* Set clear pending condition */
```
Without the above CTCE-device-only correction for CTCA emulation, under certain reproducible conditions VTAM was found to be looping after IPL.

What I do not know is whether such fix should also be present for non-CTCA devices. Help would be appreciated here! In case of doubt, I propose to only enable the additional `dev->hnd->halt` calls for 3088 devices, as shown above.

Thanks,

Peter

**Comment by Fish-Git** [comment]
For the record, here's the pertinent `channel.c` code that Peter is proposing to change:

https://github.com/SDL-Hercules-390/hyperion/blob/0912933aad590767fee63f3708a1a31ec5a0bbcc/channel.c#L1757-L1763

**Which leaves me wondering why the `dev->busy` flag isn't being set!** _(for your CTCE device)_

If the `dev->busy` flag were set _(shouldn't that normally be the case?)_, then the `if` condition would be true, and the `dev->hnd->halt` function would get called like normal and your problem would then not occur! Yes? Or am I missing something? `(*)`

Regardless, unless you haven't done so already, your change definitely needs to be tested to verify it's not going to break the other non-CTCE devices, i.e. CTCT, CTCI, LCS, PTP and OSA, which are also device type 0x3088 too.

(Unless you can tweak your proposed fix to apply _only_ to CTCE devices and not any other 0x3088 devices? Is that possible? Have your tried that yet?)

In the mean time, I'll _**try**_ _(but no promises!)_ myself to do some tests of your proposed change for OSA and LCS, but it might be a short while yet before I can get to it. I'm still pretty busy at the moment reviewing [Bob's proposed Transactional-Execution Facility implementation](https://github.com/SDL-Hercules-390/hyperion/issues/263), so I don't know when I'll be able to do so.

(Have _you_ done any testing on your own yet to verify that your change doesn't break any of the other CTCA devices?)

_____
`(*)` And _actually,_ after checking the Principles of Operation manual on the subject, a valid(?) argument could be raised that the entire `if` condition itself is a bug and should be removed so that the code is _always_ (i.e. unconditionally) executed, since the manual says nothing about the Clear function not being issued if/when the device is busy. That is to say, according to the manual, the Clear function should pretty much _always_ be done (except under certain specific unusual situation which I believe do not apply in the Hercules case), _regardless_ of whether or not the device is busy.

Mark (@dasdman) might want to check me on that however.

**Comment by Peter-J-Jansen** [comment]
I have observed that existing, current CTCA CCW programs (e.g. z/VM SSI ISCF links) will issue CHSC instructions during recovery also at times when the device is neither busy nor suspended. They do this to perform a (selective) `reset` e.g. as described in both SA22-7203-00 and SA22-7091-01. In order to allow the CTCE device driver to react correctly to this, it relies on `dev->hnd->halt` being invoked. Prior to my proposed change, I tried to discover a `reset` by recognizing other typical CTCA CCW commands immediately following such `reset`, but that proved finally to not be possible in all cases.

Whether the entire `if` section could be removed is a valid question, but I also see `schedule_ioq` in that section, hence that I would not dare such more drastic change. However, your remark that performing the `dev->hnd->halt` action for all 0x3088 devices could lead to other non-expected side-effects is a very valid one. The solution I have come up with is the following : 
```diff
hercules@pjjs12:~/SDL-hyperion$ diff -u5 ~/Qsync/Source/Originals/SDL-hyperion/channel.c     ~/SDL-hyperion/channel.c
--- /home/hercules/Qsync/Source/Originals/SDL-hyperion/channel.c	2019-12-06 12:53:48.000000000 +0100
+++ /home/hercules/SDL-hyperion/channel.c	2019-12-31 11:08:44.618131846 +0100
@@ -1757,10 +1757,13 @@
     /* If the device is busy then signal the device to clear */
     if ((dev->busy
 #if defined( OPTION_SHARED_DEVICES )
         && dev->shioactive == DEV_SYS_LOCAL
 #endif
+    /* Only CTCE devices (0x3088) have dev->hnd->halt != NULL,   @PJJ */
+    /* and they always need dev->hnd->halt invoked.              @PJJ */
+    ) || ( dev->devtype == 0x3088 && dev->hnd->used != NULL   /* @PJJ */
     ) || dev->startpending)
     {
         /* Set clear pending condition */
         dev->scsw.flag2 |= SCSW2_FC_CLEAR | SCSW2_AC_CLEAR;
 
hercules@pjjs12:~/SDL-hyperion$
```
This relies on me adding a dummy `dev->hnd->used` routine merely returning a -1, as this "Device Query used" routine is only ever used in DASD-style device handlers. I found this to be the easiest (and most performant) way to mark the CTCE 0x3088 device handler as CTCE and not CTCT, CTCI, LCS, PTP or OSA device handlers.

I keep on being very interested in your excellent feedback Fish, thanks a lot for your help in this !

Cheers,

Peter

P.S.: Regarding your closing and questions re. Issues #191 and #269 : me finding this `reset` issue will now finally allow me to move forward on my CTCE recovery and reliability improvements. Having the unfinished version of this in my development repo (https://github.com/Peter-J-Jansen/SDL-hyperion) allowed others to do some tests ahead of its finalization.  And yes, as soon as ready next month, I will of course merge it all in the official SDL-Hyperion repo !

**Comment by Fish-Git** [comment]
> The solution I have come up with is the following:

> This relies on me adding a dummy `dev->hnd->used` routine merely returning a -1, as this "Device Query used" routine is only ever used in DASD-style device handlers. I found this to be the easiest (and most performant) way to mark the CTCE 0x3088 device handler as CTCE and not CTCT, CTCI, LCS, PTP or OSA device handlers.

Wouldn't something along the lines of the following be even better? &nbsp; `;-)`

```diff
--- a/channel.c
+++ b/channel.c
@@ -1755,11 +1755,18 @@ void clear_subchan( REGS* regs, DEVBLK* dev )
     obtain_lock( &dev->lock );
 
     /* If the device is busy then signal the device to clear */
-    if ((dev->busy
+    if (0
+        || (dev->busy
 #if defined( OPTION_SHARED_DEVICES )
         && dev->shioactive == DEV_SYS_LOCAL
 #endif
-    ) || dev->startpending)
+           )
+        || dev->startpending
+        /* CTCE devices need dev->hnd->halt to always be called
+           even when not busy or startpending!
+        */
+        || dev->ctctype == CTC_CTCE
+    )
     {
         /* Set clear pending condition */
         dev->scsw.flag2 |= SCSW2_FC_CLEAR | SCSW2_AC_CLEAR;
```

&nbsp;
> I keep on being very interested in your excellent feedback Fish, thanks a lot for your help in this!

You're very welcome, Peter! You do good work! (as does virtually everyone else of the team too!)

> And yes, as soon as ready next month, I will of course merge it all in the official SDL-Hyperion repo!

I look forward to seeing it. &nbsp; `:)`

Take care my friend.

**Comment by Peter-J-Jansen** [comment]
Dear Fish,

Yes, but of course, that is **the** solution ! How could I have missed the existence of dev->ctctype !

Actually I now need to adapt a bit more of my CTCE code that needs to search the CTCE device list.

Glad you pointed this out to me Fish ! Thanks a million !

Cheers,

Peter

**Comment by dasdman** [comment]
Fish wrote:

(*) And actually, after checking the Principles of Operation manual on the subject, a valid(?) argument could be raised that the entire if condition itself is a bug and should be removed so that the code is always (i.e. unconditionally) executed, since the manual says nothing about the Clear function not being issued if/when the device is busy. That is to say, according to the manual, the Clear function should pretty much always be done (except under certain specific unusual situation which I believe do not apply in the Hercules case), regardless of whether or not the device is busy.

This is correct. I did not remove the test, however, at the time as there was at least one device driver at the time that was not playing by the rules. dev->busy is supposed to be a device function and the clear is a channel function to the device. dev->busy should never be interpreted as channel or CU busy.

 

Mark

**Comment by dasdman** [comment]
The clear routine needs to be called REGARDLESS, and the device dependent code removed from the channel. ALL devices MUST have a dev->hnd->halt routine, it needs to be an architectural (Hercules) requirement, as the device routines second as the CU for the device.
 
-        /* CTCE devices need dev->hnd->halt to always be called
-           even when not busy or startpending!
-        */
-        || dev->ctctype == CTC_CTCE
 
The proper fix is to correct the device handlers and for Hercules to call dev->hnd->halt regardless. On the real hardware, the CSCH instruction issues a SELECTIVE RESET to the CU.
 
Mark

**Comment by dasdman** [comment]
*I* wrote:

This is correct. I did not remove the test, however, at the time as there was at least one device driver at the time that was not playing by the rules. dev->busy is supposed to be a device function and the clear is a channel function to the device. dev->busy should never be interpreted as channel or CU busy.

 

Forgot the second part of the explanation…

 

However, in Hercules, dev->busy is also used (incorrectly) as subchannel busy. The proper change to the device drivers was not done at the time of the channel rewrite as to properly separate the dual functions of the flag (device busy and subchannel busy) was beyond the scope of the initial rewrite.

 

Regardless, in channel.c, there should be no device specific cod. Even though it can be argued that CTCE is part of channel communications, as there are two parts to the actual, there are the channel communications and the channel device emulation. As such, the CTCE driver is the channel device emulation and checks for CTCE in the channel code itself should not be present.

 

Mark

**Comment by Fish-Git** [comment]
Mark wrote:
> Fish wrote:
>
> > `(*)` And _actually,_ after checking the Principles of Operation manual on the subject, a valid(?) argument could be raised that the entire `if` condition itself is a bug and should be removed so that the code is _always_ (i.e. unconditionally) executed, since the manual says nothing about the Clear function not being issued if/when the device is busy.
>
> This is correct. I did not remove the test, however, at the time as there was at least one device driver at the time that was not playing by the rules. `dev->busy` is supposed to be a device function and the clear is a channel function to the device. `dev->busy` should never be interpreted as channel or CU busy.

I thought so. Thanks for the confirmation Mark.

**Comment by Fish-Git** [comment]
FYI to Mark (@dasdman):

[I would personally _prefer_ that you reply to github issue comments _directly_ via their web interface, _not_ by email.](https://github.com/SDL-Hercules-390/hyperion/issues/203#issuecomment-488819595)

This is just an FYI regarding a personal preference. It is _not_ a demand nor even a polite request to do things "my way". It is just information. It is entirely up to you whether or not you want to bother changing the way you do things based on that information. If you do, great. If you don't, that's fine too.

**Comment by Peter-J-Jansen** [comment]
My [CTCE development repo](https://github.com/Peter-J-Jansen/SDL-hyperion) already contains the fix thanks to also Fish's assistance. This development work is now ready for testing by interested users, and offers a number of important bug fixes and improvements, especially when recovering or restarting CTCE connections. If all goes well, this work will soon be committed to this repo.

Cheers,

Peter

**Comment by Fish-Git** [comment]
Thanks for the update, Peter! That's fantastic news! I look forward to your commit!

**Comment by Peter-J-Jansen** [comment]
This was correct in commit 8ac28ed and can thus be closed.

Cheers,

Peter

**Comment by dasdman** [comment]
Peter:

Please re-read prior comments. There should be **_NO DEVICE SPECIFIC CODE_** channel.c. For example:

``        /* CTCE devices need dev->hnd->halt to always be called``
``           even when not busy!``
``        */``
``        || dev->ctctype == CTC_CTCE)            /* @PJJ */``

Violates this rule directly. The **_correct_** update should always call the dev->hnd->halt routine and code added to any of the individual device drivers that do not have a dev->hnd->halt routine. This also keeps channel.c CLEAN for upcoming and future enhancements.

In addition, please reconsider how and where INTLOCK is being obtained and freed; it is taking a hammer to channel performance for DASD as it is obtained before it is even known if it will be needed in the update.

Mark

**Comment by ivan-w** [comment]
I concur with Mark. The I/O - Channel "EOM" code should not depend on the backing Control Unit definition. (Well it should since you should be able to declare a CU to be shared or non-shared.. but that's another story - but not something as specific as relating to channel signaling).

**Comment by Fish-Git** [comment]
CC: Peter, Mark, Ivan (@Peter-J-Jansen, @dasdman, @ivan-w):

Mark Gaubatz wrote:

> Peter:
> 
> Please re-read prior comments. There should be **_NO DEVICE SPECIFIC CODE_** in channel.c. For example:
> 
> ` /* CTCE devices need dev->hnd->halt to always be called`
> ` even when not busy!`
> ` */`
> ` || dev->ctctype == CTC_CTCE) /* @PJJ */`
> 
> Violates this rule directly. &nbsp; ...

_**FYI:**_ That was _my fault_ guys, not Peter's.

**[I was the one that suggested that code](https://github.com/SDL-Hercules-390/hyperion/issues/273#issuecomment-569923466),** not Peter.

So yell at _**me,**_ not him. &nbsp; `:(`

And for the record, yes, you are of course _(once again!)_ correct, Mark. In fact, Peter's original suggestion would probably have been a better fix than what I suggested.

What I suggested was/is certainly _easiest_ (simplest and most straightforward) fix, but as you pointed out, it's unfortunately not the _correct_ fix.

My apologies to everyone. &nbsp; I will try to do better next time. &nbsp; `:(`

**Comment by ivan-w** [comment]
We're not yelling :P Just expressing our opinion ! (You know me)

**Comment by Fish-Git** [comment]
> We're not yelling.   `:P`   Just expressing our opinion!

Okay, maybe my use of the word "yelling" wasn't the best choice.

> (You know me)

All too well! &nbsp; `;-)`

> I believe Mark's 'bold' marking were not yelling but putting emphasis on the specific problem at hand.

Got that.

But his bolding coupled with his wording made it seem to me like his criticism _(is that a better word?)_ was being directed towards Peter, as if he was blaming Peter for the bad code, when in fact I'm the one that should be taking the blame since it was my _(bad)_ suggestion.

I just don't like blame being directed at the wrong person, that's all. Peter is innocent. _I'm_ the one who's guilty.

**Comment by ivan-w** [comment]
There is no guilt. Only those who do not do anything can never be wrong !

Now back to the task at hand ;)

Channel signaling is a pain in the neck with the current channel subsystem implementation... the question is : How do we address it to be able to have conforming, clean, portable, extensible CU (And Device) handlers ?

**Comment by Fish-Git** [comment]
CC: Mark and Peter ( @dasdman @Peter-J-Jansen )

Mark Gaubatz wrote:

> In addition, please reconsider how and where INTLOCK is being obtained and freed; it is taking a hammer to channel performance for DASD as it is obtained before it is even known if it will be needed in the update.

That is _also_ my doing. &nbsp; `:(`

Although given the way it was previously written it's a definite improvement! &nbsp; `;-)`

If you look at the way Peter had it coded _previously_, he was acquiring the locks in the incorrect order, causing a potential deadlock (which, as it turns out, [actually _does_ occur in some circumstances](https://github.com/SDL-Hercules-390/hyperion/issues/277#issuecomment-581400522) (*)).

Your original code was doing things correctly, but the temporary releasing of dev->lock in order to acquire INTLOCK first, was causing a problem for Peter.

So in order to not break Peter's fix while at the same time not violating lock acquisition hierarchy rules regarding INTLOCK and dev->lock, I suggested simply obtaining INTLOCK from the get-go since it was very likely going to be needed anyway in order to queue the attention interrupt. &nbsp; _&lt;shrug&gt;_

_____
(*) Why it doesn't seem to occur in non-370 mode I have no freaking clue. Peter's bad code has been in Hercules since 2016, and it was only recently (issue #277) that it finally bit us.

**Comment by Fish-Git** [comment]
> Only those who do not do anything can never be wrong!

Quite true. &nbsp; `:)`

Or put another way, those who make the fewest mistakes is either because they're doing the least amount of work (or no work at all) or else because they just happen to be very, very good at what they do, whereas those who make the most mistakes is because either they're doing most of the work or else they're incompetent.

> Channel signaling is a pain in the neck with the current channel subsystem implementation...

No argument there.

> The question is: How do we address it to be able to have conforming, clean, portable, extensible CU (And Device) handlers?

A _**very** good_ question, and one which I do not have a ready answer to, unfortunately.

Maybe I/we should work a little harder at trying to split off our channel code into a separate "External Package" maybe? Would that help?

That would at least allow Mark's channel effort to likely proceed at a faster (and probably much easier) pace, than leaving it so closely tied to (integrated into) Hercules like it is right now.

And if we did, we could all then contribute to the overall effort by trying to split the code for each of our existing drivers into their more proper separate control unit and device handling pieces.

But as far as what we can do right _now?_ 

I haven't the faintest. &nbsp; `:(`

Got any ideas?

**Comment by Peter-J-Jansen** [comment]
Mark, Ivan, Fish,

Thanks for your feedback.

If I understand Mark's comments regarding my last CTCE commits correctly, two items should need to be addressed :

1.  No device specific code in channel.c

In principle I agree with this.  However, there are already at least three other violations of the rule against device specific code in channel.c : two tests for dev->ctctype==CTC_LCS and one for dev->devtype==0x2703.  My two new tests for dev->ctctype==CTC_CTCE were only added because channel.c was NOT calling the dev->hnd->halt(dev) when the device was busy or startpending, which both Mark and Fish agreed to be wrong.  This is confirmed reading the various POP's; a few days ago I checked GA22-7000-4 for the S/370 case for HIO after Bob Polmanter had reported CTCA problems for VTAM 3 CTCA links. The code listed by Mark in his reply fixed that problem.
 
A simple remedy to avoid this device dependency in channel.c would be to ALWAYS call dev->hnd->halt(dev) for devices that have it defined. However, such a change could possible have unpredictable effects on ALL device drivers that have a device halt routine defined. If we think that this is nevertheless what we should do, then that's fine by me, but I lack the knowledge and experience to start debugging the halt routines in all these other drivers. I therefore agreed with what Fish proposed as the safer and non-intrusive way forward, which was to correct the calling of the dev-hnd-halt(dev) routine only for the CTCE device driver that really needs it.

The current list of device drivers, other than CTCE, that implement a device halt routine are : comm3705.c, commadpt.c, console.c, ctc_ctci.c, ctc_lcs.c, ctc_ptp, qeth.c and zfcp.c.  All of these would need to be verified that an unconditional (i.e. also when not busy or startpending) calling of dev->hnd->halt(dev) would not hurt.  Any volunteers :-) ?

2. INTLOCK being obtained unconditionally in the device_attention routine

This is actually the result of a correction Fish proposed for a bad fix of mine in 2016 to solve an easily reproducible bug : when performing large enough RSCS file transfers over an NJE link VM abended IQM002.  This original problem was cuased by a obtain-release of the device lock prior to obtaining the INTLOCK needed to perform the actual device atention.  Which was then immediately followed by re-obtaining the device lock.  With that initial device lock being held it was verified that the device was not busy. When that was indeed not the case, the device lock was being released, then INTLOCK obtained, then the device lock being obtained again. This is clearly a bug, as in between the device lock being released and the INTLOCK and device lock being obtained again, the device can become busy ! CCW programs requiring massive numbers of device attentions succeeded in that happening, resulting in the IQM002.  Removing the release + (re-)obtaining of the device lock around the INTLOCK, solved the IQM002 problem, but, as documented in Issue #277, created another bug because of my fix not adhering to the correct locking hierarchy.

The current code in device_attention is correct, and I agree with Fish it is the best solution right now, fixing both the IQM002 and Issue #277 problem.  If I interpret Mark's comment correctly, then he is not so happy with the situation that a system-wide (i.e. not device-only) INTLOCK is being obtained in cases where it is not needed, which applies when the device would be busy (or not existing, ut I think we can ignore that case).  Mark comment implies that this would severly impact DASD performance.  Is my understanding correct mark ?

This morning I saw that Issue #277 was circumvented differently, without awaiting me applying Fish's fix for my bad IQM002 fix of 2016, so we could revert to this bad fix,thus violating the locking hierarchy.  I would propose to not do that, and leave it as it now stands.  How bad is the DASD penalty doing unnecessary INLOCK's for cases where the device to be attentioned is busy ?

The only other option would be a re-design and implementation of the device_attention mechanism.  But here I understand to little of the relationships and hierarchy around the locks involved. It just seems unfortunate that in order to create an unsollicited attention for a single device, a system-wide INTLOCK appears to be needed.  I'd love to read someone explaining it to me.


Thanks again for the comments, and please do not worry about being critical about my code. I only joind this wonderful Hercules project quite late, so I miss all of the important insights and knowledge that most of you already had years and years before I joined.

Cheers,

Peter

**Comment by Peter-J-Jansen** [comment]
I quickly checked what would have to be done to allow channel.c to always call dev->hnd->halt(dev) for ALL devices that have such routine defined, and actually, that is not so difficult at all.  Just seven routines, each of which has less than 10 lines of code, would have to be modified, in that that code would have to be made conditional on the device being busy or startpending.  After that, channel.c could be modified so that dev->hnd->halt(dev) is always called, and thus not needing to test for dev->ctctype==CTC_CTCE. Please let me know if I should proceed with this.  The seven routines are :

```
   constty_halt_or_clear   in console.c
   loc3270_halt_or_clear   in console.c
   ctc_halt_or_clear       in ctc_ctci.c
   lcs_halt_or_clear       in ctc_lcs.c
   ptp_halt_or_clear       in ctc_ptp.c
   qeth_halt_or_clear      in qeth.c
   zfcp_halt_or_clear      in zfcp.c
```

Reworking stuff to remove the other device specific code in channel.c I would leave to others.

Thanks,

Peter

**Comment by Fish-Git** [comment]
(_A thousand pardons_ for taking so long to respond! I became sidetracked with something else and then this coronavirus thing hit (along with the threat of homelessness) and I kind of lost track of things and am only now trying to get caught up.)

> **Please let me know if I should proceed with this.**

My opinion is doing so is a good step in the right direction, so _**yes**, please do proceed with that!_

I would like to close this issue, but do not feel comfortable doing so until you, Peter, agree that your reported issue has now been successfully resolved.

As always, if there's anything I can do to help, please let me know.

Thanks.

**Comment by Fish-Git** [comment]
> I would like to close this issue, but do not feel comfortable doing so until you, Peter, agree that your reported issue has now been successfully resolved.

Peter? (@Peter-J-Jansen)

What's the status of this issue? (Just asking!)

**Comment by Peter-J-Jansen** [comment]
I was awaiting further suggestions or comments on the two issues mentioned, but none arrived so far. As the current CTCE implementation by now has been more stable than ever before (including the ability to automatically recover from some TCP/IP communication interruptions), and because I don't see how to address the issues (which some might consider cosmetic) in any easy and risk-free manner, I would propose that we close this issue.

Thanks,

Peter

**Comment by Fish-Git** [comment]
> ... I would propose that we close this issue.

As you wish!
