### ISSUE TITLE
Nasty errors with SYSGEN MVS STAGE1

### ISSUE THREAD

**Issue by GerardWassink** [SDL-Hercules-390/hyperion#274]
Hi guys, 

I'm using this version of Hyperion:

> HHC01027I Hercules version 4.3.9999.0-SDL-g28aa15bd-modified, built onan 18 2020 16:04:42
HHC01031I Running on galileo (Linux-4.19.66-v7+.#1253 SMP Thu Aug 15 149:46 BST 2019 armv7l MP=4)

Compiled it from source on my Raspberry Pi 3B. Here are the parameters I used for the configure:

> ./configure --enable-optimization="-mcpu=cortex-a53 -mtune=arm8 -mfpu=neon-vfpv4 -frename-registers" --prefix=$HOME/.localSDL --enable-extpkgs=$HOME/git/extpkgs --enable-setuid-hercifc=yes --disable-regina-rexx --disable-object-rexx

The installed VM/370 seems to work fine, but I am trying to perform a SYSGEN Moseley describes on his website, this SYSGEN really garbles up things. I'm running into these errors:

> HHC00801I Processor CP00: Addressing exception code 0005  ilc 2
> HHC02324I PSW=00000005600620D0 INST=0E46         MVCL  4,6
> HHC02326I R:00FFF000: Translation exception 0005
> HHC02326I R:00000000:K:06=040E0000 0001AB6E 00000000 00000000  .......
> HHC02269I GR00=00000000 GR01=00000800 GR02=00FFF000 GR03=0001BBA8
> HHC02269I GR04=00FFF000 GR05=00001000 GR06=00000000 GR07=00000000
> HHC02269I GR08=40061D96 GR09=00062D95 GR10=000643CA GR11=00063D94
> HHC02269I GR12=00064820 GR13=0006485C GR14=90062044 GR15=007FFFFF

Do you guys have an idea about what's happening here please?

Gerard Wassink (Netherlands)

**Comment by GerardWassink** [comment]
Tried the same on this (cloud) computer, running Debian Buster Lite:

>           Icon name: computer-vm
>                Chassis: vm
>          Machine ID: d58e7f4adfbb440fab585ed6f9b8d644
>                Boot ID: f7f131aa0bf8443ea2bda694979f541f
>        Virtualization: kvm
>Operating System: Debian GNU/Linux 10 (buster)
>                  Kernel: Linux 4.19.0-6-amd64
>         Architecture: x86-64
> 
Same result, Addressing and Translation exceptions.

**Comment by wably** [comment]
Hi Gerard,

Can you post the hercules configuration file that you are using when this error occurs?

Also, can you answer these questions:
1. I assume you are referring to MVS 3.8 J, is that correct?
2. Is the error occurring during IPL of MVS or during the execution of the sysgen jobs?  If a job, which one exactly?  If IPLing, can you also post some of the recent messages on the MVS console just prior to the failure?

The particular program check error you posted appears to be attempting to clear to zeros the last page frame in a 16 MB storage.  Since the program check is 0005, that means the address referenced doesn't exist, in other words, something less than 16MB is defined in the Hercules configuration.  MVS can handle less than 16MB of course.  We really need to see your configuration and messages.

I am using MVS 3.8 on both a RPI 3 and RPI 4 using SDL Hyperion and it is working fine.

Regards,
Bob

**Comment by GerardWassink** [comment]
Hi Bob, 

1. Yes, I am referring to building MVS 3.8J TK4- (I am following this cookbook with the ffiles that Moseley supplies: http://www.jaymoseley.com/hercules/installMVS/install.htm)

2. The error occurs mainly during IPL (and multiple times when it does - at least three screens full)

During this installation processof MVS from tapes there are several config files involved. In step 1 (building the MVS starter system) it is this one:

**ibcdmprs.cnf**

> ARCHMODE  S/370
> CPUSERIAL 000611
> CPUMODEL  0148
> MAINSIZE  8
> XPNDSIZE  0
> CNSLPORT  3270
> NUMCPU    1
> LOADPARM  ........
> 
> # .-----------------------------Device number
> # |     .-----------------------Device type
> # |     |       .---------------File name
> # |     |       |
> # V     V       V
> #---    ----    --------------------
> 0009    1052
> 000C    1442    sajobs/instart1.sajob
> 000D    1442    sajobs/rsstart1.sajob
> 000E    1442    sajobs/inspool0.sajob
> 000F    1442    sajobs/rsspool0.sajob
> 0150    3330    dasd/start1.3330
> 0151    3330    dasd/spool0.3330
> 0280    3420    tape/vs2start.het
> 0281    3420    tape/vs2spool.het

**NOTE:** While I'm pasting this I see that in all the config files it says 'MAINSIZE 8'. Changed all of these to 'MAINSIZE 16', and the message did indeed not appear again.

**Comment by wably** [comment]
Gerard,

It seems that you have resolved the issue yourself by changing the MAINSIZE parameter.

As to why the addressing exception occurred, I cannot say.  It would be very common for any standalone utility to loop through memory until it reaches the end of what is addressable, in order to determine what the memory size is.  This would generate a PIC 0005 addressing exception for any MAINSIZE under 16.  But the utilities should continue working after that with whatever size they find, unless of course it is way too small of a size.

What is also curious is that bit 5 in the PSW is set on; this is the DAT bit.  The standalone utilities generally are not in the habit of creating and using virtual storage in my experience so this seems a bit odd.

In any case, it seems like you can now move forward by using a MAINSIZE of 16.  There really is no reason to use less.  If you are satisfied that it is working now, you can close this issue.

A long time ago I did a sysgen of MVS 3.8 but I did not use the standalone utilities and build a starter system.  I just used another copy of a pre-built MVS 3.8 to be 'the starter system'.  It is just a lot easier that way.  In the end, I arrived at the same goal (a sysgenned system set up the way I wanted) without the pain of standalone and starter system builds.

Regards,
Bob
