### ISSUE TITLE
CTCE v2: Problem changing buffer size

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#283]
The default buffer size is not large enough. I need a buffer size of 62552 or Enterprise Extender fails.

I tried the new CTCE format, where I coded:

```
0E40  CTCE  0E40=192.168.40.1  62552
```

but 62552 is recognized as the remote port number, not the buffer size.

Is there any way to code buffer size without having to code the remote port number?  None of the samples show changing the buffer size.

BTW, release 2 so far looks to be a big improvement!

**Comment by Peter-J-Jansen** [comment]
Bob,

Thanks for your nice words re. the CTCE v2 improvements.

If you want to alter the default buffer size right now then one has to code the default remote listening port number _rport_, which is 3088, just in front of that altered buffer size, e.g. : 

```
0E40 CTCE 0E40=192.168.40.1 3088 62552
```
But I will increase the buffer size default to your 62552, because my intent was to have that default to the largest required value ever encountered. I will let you know when that change has been committed.

Which brings me to another point, as I too use Enterprise Extender (EE), but without CTCE involvement, as I just use EE over LCS. I'd be interested to know how CTCE gets involved with CTCE devices. 

Thanks again,

Peter

**Comment by rgschmi** [comment]
Peter,

I was running a two LPAR sysplex when I ran into the issue.  I had already established  XCF connectivity, both SNA and TCPIP when I decided to also bring up EE.  Though I didn't prove it, I believe the EE session tried to establish over the IP XCF connection when I got the error message that I had to increase the buffer size to at least 62552 from 62548.  I also had LCS connectivity between the two LPARs as I have never been able to get QETH to work on OPENsuse.  I think I have an OPENsuse TUN configuration issue due to my ignorance of linux.  I do have a copy of an email you sent to Fish and copied me describing your QETH configurations, which has been a great help (I am also learning zVM!).

I am still playing with getting CTCE connectivity to all four of my LPARS and with the new formats for CTCE.  Before this release, I was never able to get more than three LPARS connected without getting some sort of connectivity issue no matter how careful I was. Now it's not a problem

Thanks again for all the work you and others do!

Bob

**Comment by Peter-J-Jansen** [comment]
Bob,

Thanks for the nice encouraging words ! I'm also still working on a specific problem (VTAM 3 related), and also on a spinhawk backport.

Cheers,

Peter

**Comment by Peter-J-Jansen** [comment]
Commit 5080ee8 has increased the default CTCE buffer size to 62552, and the HTML help has been updated, also with the comment that if the buffer size needs to be increased again, the default rport number (which defaults to 3088) needs to be specified.

I think issue #283 can therefore be closed.

Cheers,

Peter
