### ISSUE TITLE
Suspected printer support regression in recent Hercules 4.x

### ISSUE THREAD

**Issue by Jim-F** [SDL-Hercules-390/hyperion#285]
I thought I'd take the opportunity to report what looks like a regression in Hercules 4.x.

It occurs in the course of IPLing a somewhat obscure System/370 OS: **Rodolfo Cozzi's OS/VS1** distribution, that was briefly available some years ago before the Hercules community noticed and complained about the fact that it contains licensed products.

This configuration contains two 3211 printers: one at `00E` (for general output) and the other at `07F` (for the system log). For each printer, the operating system asks for the character set (UCS) and forms control (FCB) information:

```
*02 IEC123D 00E SPECIFY UCS PARAMETER
r 02,QN
*03 IEC123D 07F SPECIFY UCS PARAMETER
r 03,QN
*04 IEC129D 00E SPECIFY FCB PARAMETER
r 04,STD2
*05 IEC129D 07F SPECIFY FCB PARAMETER
r 05,STD2
```

With Hercules 4.00.0.8775 and earlier (and also with Hercules 3.13), the printers come up as expected and are usable by the system.

With Hercules 4.00.0.8845 and later (up through 4.2.1.9826), the process involved in installing the printer character set crashes, and the printers are not available.

I've attached four text files to document this: one for Hercules 4.00.0.8845 (a 3215 console session that shows the crashes), and three for Hercules 4.00.0.8775 (the 3215 console session and the printer `00E` output and `07F` log for a normal startup, job run, and shutdown).

If you have any interest in pursuing this, or would like to reproduce the problem for yourself, I have the entire **OS/VS1** system zipped up on an ftp server. If you want to grab this, let me know (jfehlinger @ comcast.net) and I'll open up my firewall and give you an IP address to point your ftp client at.

* [os_vs1__3215__hercules_4.00.0.8845_64.txt](https://github.com/SDL-Hercules-390/hyperion/files/4271967/os_vs1__3215__hercules_4.00.0.8845_64.txt)
* [os_vs1__3215__hercules_4.00.0.8775_64.txt](https://github.com/SDL-Hercules-390/hyperion/files/4271969/os_vs1__3215__hercules_4.00.0.8775_64.txt)
* [os_vs1__prt00e_output__hercules_4.00.0.8775_64.txt](https://github.com/SDL-Hercules-390/hyperion/files/4271971/os_vs1__prt00e_output__hercules_4.00.0.8775_64.txt)
* [os_vs1__prt07f_log__hercules_4.00.0.8775_64.txt](https://github.com/SDL-Hercules-390/hyperion/files/4271972/os_vs1__prt07f_log__hercules_4.00.0.8775_64.txt)

**Comment by Fish-Git** [comment]
1. The documents you attached above, while _somewhat_ helpful, are not as helpful as seeing your actual _**Hercules**_ logfile would be. _(If you do not know what I am referring to, let me know and I'll explain.)_

2. Please attach your Hercules _configuration_ file. I would like to see how you have your printer devices defined to Hercules as well as all of your other Hercules configuration settings.

3. Please run your test again, but with CCW tracing enabled beforehand: enter the Hercules commands `t+00e` and `t+07f` before starting your test.

4. After running the above test (with CCW tracing enabled), please attach your resulting Hercules log.

Thanks.

**Comment by Fish-Git** [comment]
p.s. Can you build Hercules from source? Have you tried the current git version yet? There was a printer fix that I made fairly recently (Feb 2, 2020) that fixed a printer problem that someone else was having. Maybe it's the same bug that's now biting you? _&nbsp;&lt;shrug&gt;_

In any case, the stuff I mentioned in my previous comment (Herc config file, ccw trace + Herc log file) will help the most.

Thanks.

**Comment by Jim-F** [comment]
>After running the above test (with CCW tracing enabled), please attach your resulting Hercules log[s].

OK, same tests as before with same versions of Hercules 4, CCW tracing enabled, logs
(and configuration file) attached.

> p.s. Can you build Hercules from source?

If you decide you really need me to do this, yes, I can install Visual Studio.
I'd rather not, but if it's necessary. . .   ;->

[Hercules_4.00.0.8845_64_Logfile.txt](https://github.com/SDL-Hercules-390/hyperion/files/4278216/Hercules_4.00.0.8845_64_Logfile.txt)

[vs1.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/4278221/vs1.cnf.txt)

[Hercules_4.00.0.8775_64_Logfile.txt](https://github.com/SDL-Hercules-390/hyperion/files/4278194/Hercules_4.00.0.8775_64_Logfile.txt)

**Comment by Fish-Git** [comment]
This looks like a user error.

You config file has your printers defined as 3211 devices, but according to your own comments, they are actually be 3203 devices:

```
#  Line Printers

#  (00F is actually supposed to be a 3262;
#   the rest are actually 3203s.)

000E    3211    D:/vs1/prt/prt00e.txt crlf
000F    3211    D:/vs1/prt/prt00f.txt crlf
004E    3211    D:/vs1/prt/prt04e.txt crlf
004F    3211    D:/vs1/prt/prt04f.txt crlf
007E    3211    D:/vs1/prt/prt07e.txt crlf
007F    3211    D:/vs1/prt/prt07f.txt crlf
008E    3211    D:/vs1/prt/prt08e.txt crlf
009E    3211    D:/vs1/prt/prt09e.txt crlf
```

If they're configured to OS/VS1 as 3203 devices then you should define them to Hercules as 3203 devices.

As far as `00F` is concerned (which according to your comments is defined to OS/VS1 as a 3262 device), since Hercules does not appear to support 3262 devices I think you might be out of luck. Nevertheless, you might try defining it to Hercules as a 3203 device as well.

Closing this issue as "Invalid" (user error).

**Comment by Jim-F** [comment]
> This looks like a user error. . .
>
> If they're configured to OS/VS1 as 3203 devices then you should
> define them to Hercules as 3203 devices.

Well, of course that doesn't work, in any version of Hercules
(including the latest 4.2.1.9826):

19:30:29.478 00000920 HHC01462E 0:000E devtype 3203 not recognized
19:30:29.478 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.479 00000920 HHC01462E 0:000F devtype 3203 not recognized
19:30:29.479 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.480 00000920 HHC01462E 0:004E devtype 3203 not recognized
19:30:29.480 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.482 00000920 HHC01462E 0:004F devtype 3203 not recognized
19:30:29.482 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.483 00000920 HHC01462E 0:007E devtype 3203 not recognized
19:30:29.483 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.484 00000920 HHC01462E 0:007F devtype 3203 not recognized
19:30:29.484 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.485 00000920 HHC01462E 0:008E devtype 3203 not recognized
19:30:29.485 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
19:30:29.486 00000920 HHC01462E 0:009E devtype 3203 not recognized
19:30:29.486 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)

I thought that perhaps the fact that Hercules 3.13 and earlier 4.x (up through 4.00.0.8775)
were satisfied to have these printers attached as (supported) 3211s was exposing
a regression that had been introduced somewhere between 4.00.0.8775 and 4.00.0.8845.

However, if the official position is "this doesn't work now because it should
never have worked in the first place", well -- then so be it.

Sorry to have bothered you.

**Comment by Fish-Git** [comment]
Jim (@Jim-F),

> > This looks like a user error. . .
> > 
> > If they're configured to OS/VS1 as 3203 devices then you should define them to Hercules as 3203 devices.
> 
> Well, of course that doesn't work, in any version of Hercules (including the latest 4.2.1.9826):
> 
> ```
> 19:30:29.478 00000920 HHC01462E 0:000E devtype 3203 not recognized
> 19:30:29.478 00000920 HHC00007I Previous message from function 'attach_device' at config.c(1290)
> ```

_(Doh!)_

My sincerest apologies, Jim!

I completely forgot that the 3203 device equate bug was something that only "recently" fixed in SDL Hyperion (Sept 2019):

* [What's new in Hercules](https://sdl-hercules-390.github.io/html/hercnew.html)

Notice the second item listed in the "What's New" list for version 4.3 (still under development):

* Add missing 3203 printer to DEVEQU table (**#250**)

So you are indeed correct that none of the currently released versions of Hercules properly _recognize_ device type 3203.

Support for 3203 printer devices _does_ exist however, in the latest 4.2.1.9826 version.

The trick of course, is getting it to _recognize_ that particular device type! &nbsp; `;-)`

If you give GitHub Issue #250 a quick peek ("[Line Printer class 3203 not recognized](https://github.com/SDL-Hercules-390/hyperion/issues/250)"), you might notice that 3203 printers _are_ recognized -- _as long as there is at least one 3211 device preceding it in your configuration file._ (*)

So simply add a "dummy" 3211 device to your configuration file (e.g.  `0001 3211 dummy`) anywhere _before_ (preceding) your existing printer device definitions, and the latest 4.2.1.9826 SDL Hyperion will then recognize device type 3203.

While device types 1403 and 3211 have been extensively (quite thoroughly) tested, 3203 devices have not, so you are in a good position to help us verify that our existing 3203 support is indeed working correctly. Given that, with very few exceptions, 3203 devices are, as I recall, virtually identical to 3211 devices however, I of course have a very high degree of confidence that our 3203 support is indeed correct. But you can help to further verify that with the OS/VS1 you're using.

So stick that dummy 3211 statement in there (ahead of your 3203 statements) and give 4.2.1.9826 a try, and let us know if you have any problems.

Thanks!

(and sorry about forgetting about the DEVEQU thing!)
___
(*) This was the bug that was fixed. You shouldn't need to do that of course, and once version 4.3 is officially released, you won't. But until then however, you need to.

**Comment by Jim-F** [comment]
> [A]dd a "dummy" 3211 device to your configuration file (e.g. 0001 3211 dummy)
> anywhere before (preceding) your existing printer device definitions, and
> the latest 4.2.1.9826 SDL Hyperion will then recognize device type 3203.
>
> I of course have a very high degree of confidence that our 3203 support
> is indeed correct. But you can help to further verify that with the OS/VS1
> you're using.

Yes that works.  Printer 00E (the printer actually configured in the OS
as a 3203) initializes (with character set and forms buffer) and functions
correctly.  Also, printer 07F (which is configured in the OS as
a 3262) initializes and functions correctly when listed in the Hercules
configuration file as a 3203.

Thanks!

**Comment by Fish-Git** [comment]
> Yes that works.

Great! Thanks for the conformation.

> Thanks!

You are very welcome, Jim.

And again, sorry about the mixup.

Enjoy your personal mainframe. &nbsp; `:)`
