### ISSUE TITLE
Raspbian build error

### ISSUE THREAD

**Issue by m4galaxor** [SDL-Hercules-390/hyperion#305]
```
  CC       hsys.lo
gcc: error: unrecognized argument in option '-mcpu=armv7l'
gcc: note: valid arguments to '-mcpu=' are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m3 cortex-m4 cortex-m7 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 ep9312 exynos-m1 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native qdf24xx strongarm strongarm110 strongarm1100 strongarm1110 xgene1 xscale
gcc: error: unrecognized argument in option '-mtune=armv7l'
gcc: note: valid arguments to '-mtune=' are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m3 cortex-m4 cortex-m7 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 ep9312 exynos-m1 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native qdf24xx strongarm strongarm110 strongarm1100 strongarm1110 xgene1 xscale
Makefile:2343: recipe for target 'hsys.lo' failed
make[2]: *** [hsys.lo] Error 1
make[2]: Leaving directory '/share/mainframe/resorces/hyperion'
Makefile:2393: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/share/mainframe/resorces/hyperion'
Makefile:1739: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Fish-Git** [comment]
> ```
> gcc: error: unrecognized argument in option '-mcpu=armv7l'
> gcc: note: valid arguments to '-mcpu=' are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m3 cortex-m4 cortex-m7 cortex-r4 cortex-r4f cortex-r5 cortex-r7 cortex-r8 ep9312 exynos-m1 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native qdf24xx strongarm strongarm110 strongarm1100 strongarm1110 xgene1 xscale
> ```

This is not a Hercules problem.

This is a problem with your GCC installation: it is not recognizing your `-mcpu` value. You might have to install special support for that. I don't know. I'm not familiar with Linux.

Closing issue as "Invalid; User Error".

**Comment by wrljet** [comment]
That's a gcc version problem.  They changed the set of supported ARM processors (and the names) at some point.

**Comment by m4galaxor** [comment]
> 
> 
> That's a gcc version problem. They changed the set of supported ARM processors (and the names) at some point.

Don't you think that GCC has stronger position to dictate changes than SDL-Hercules has?

**Comment by wrljet** [comment]
I didn't mean that it was a bug in gcc.  More of a mismatch between gcc and configure, and possibly mistakes in your build process.

This is a good write-up about how to build on the Pi.

I use different options for configure related to the ARM, for a Pi 4:

`--enable-optimization="-O2 -pipe -mcpu=cortex-a8 -mfpu=neon-vfpv4 -mfloat-abi=hard"`

I just now ran through the entire process myself on a Pi 4 and it worked with gcc 8.3.0.

/Bill

**Comment by m4galaxor** [comment]
Hi Bill Yes, you are right with all . I compiled it sucessfully and it runs. I did some test, please see below findings if you think that it will be useful for soemthing: MVS 3.8 started with new Hercules, anyway i found some problem with my installation: MSV starts , but I have a filling it works a bit slower than with orginal TK4- binaries, to test I run compilation of Frotran I have obsesion to run, but not succeed with- SPICE circuit symulator, compilation and linking took almost two times slower than with old Hercules, over  to 250 sec comparing to ca. 70 sec with old softwareFORTAN and assembler code is here https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/spice/index.htmI am not sending my JCL cards becuase I did not get it running, so a bit shame on me to send them to you JCL. I did some other testing with tools and DASD created by this commanddasdinit -a pub014.243 3350 PUB14was reportd as not recognized format by  cckdcdsk -4  -f  Best regards Od: Bill LewisWysłano: piątek, 29 maja 2020 16:40Do: SDL-Hercules-390/hyperionDW: m4galaxor; AuthorTemat: Re: [SDL-Hercules-390/hyperion] Raspbian build error (#305) I didn't mean that it was a bug in gcc. More of a mismatch between gcc and configure, and possibly mistakes in your build process.This is a good write-up about how to build on the Pi.I use different options for configure related to the ARM, for a Pi 4:--enable-optimization="-O2 -pipe -mcpu=cortex-a8 -mfpu=neon-vfpv4 -mfloat-abi=hard"I just now ran through the entire process myself on a Pi 4 and it worked with gcc 8.3.0./Bill—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Fish-Git** [comment]
@m4galaxor 

Your message was deleted due to formatting issues. (It was all garbled and impossible to read!)

Please do NOT reply to GitHub Issues via email. Rather, please logon to GitHub and enter your message from there instead. Thanks.

I will TRY to retype your message for you this time, but NEXT time, PLEASE do not use email to reply to a GitHub Issue. Instead, please logon to GitHub and enter your reply from their user interface. Thanks!

**Comment by Fish-Git** [comment]
_(EDIT: this was a message originally sent by email from **m4galaxor**. I have manually retyped it below so that it can be better formatted for easier readability. Thanks. Fish)_

Hi Bill

Yes, you are right with all. I compiled it successfully and it runs. I did some test. Please see below findings. If you think that it will be useful for something: MVS 3.8 started with new Hercules.

Anyway, I found some problem with my installation: MSV starts, but I have a feeling it works a bit slower than with original TK4- binaries. To test, I run compilation of FORTRAN I have obsession to run, but not succeed with: SPICE circuit simulator. Compilation and linking took almost two times slower than with old Hercules: over  to 250 sec comparing to ca. 70 sec with old software FORTRAN and assembler code is here:

* https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/spice/index.htm

I am not sending my JCL cards because I did not get it running, so a bit shame on me to send them to you JCL. I did some other testing with tools and DASD created by this command:

```
dasdinit -a pub014.243 3350 PUB14
```

but was reported as not recognized format by  `cckdcdsk -4  -f`.

Best regards

**Comment by Fish-Git** [comment]
m4galaxor,

The likely reason your SDL Hyperion is running slower is probably because it was not properly optimized. The optimization flags used during the build are very important to provide good performance. To confirm, please show us your `./configure` output.

The reason your `cckdcdsk` complained about an unrecognized format is because the dasd you created with your `dasdinit` command is a regular format CKD dasd and not a compressed format CCKD dasd. The `cckdcdsk` utility only works with CCKD (compress CKD) format dasd.

To create a compressed CCKD dasd, you need to specify the `-z` or `-bz2` or `-0` option:

<pre>
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.3.9999.10143-SDL-g9ceed2cc
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: May 29 2020 at 14:27:40
HHC02448I Usage: dasdinit [-options] filename devtype[-model] [volser] [size]
HHC02448I Builds an empty dasd image file
HHC02448I options:
HHC02448I
HHC02448I   <b><i>-z        build compressed dasd image file using zlib</i></b>
HHC02448I   <b><i>-bz2      build compressed dasd image file using bzip2</i></b>
HHC02448I   <b><i>-0        build compressed dasd image file with no compression</i></b>
HHC02448I   -lfs      build a large (uncompressed) dasd file (if supported)
HHC02448I   -a        build dasd image file that includes alternate cylinders
HHC02448I             (option ignored if size is manually specified)
HHC02448I   -r        build 'raw' dasd image file
HHC02448I             (no VOL1 or IPL track)
HHC02448I   -b        make wait PSW in IPL1 record a BC-mode PSW
HHC02448I             (default is EC-mode PSW)
HHC02448I   -m        enable wait PSW in IPL1 record for machine checks
HHC02448I             (default is disabled for machine checks)
HHC02448I   -linux    null track images will look like Linux dasdfmt'ed images
HHC02448I             (3390 device type only)
HHC02448I
HHC02448I   filename  name of dasd image file to be created
HHC02448I   devtype   CKD: 2305, 2311, 2314, 3330, 3340, 3350, 3375, 3380, 3390, 9345
HHC02448I             FBA: 0671, 3310, 3370, 9313, 9332, 9335, 9336
HHC02448I
HHC02448I   model     device model (implies size) (opt)
HHC02448I   volser    volume serial number (1-6 characters)
HHC02448I             (specified only if '-r' option not used)
HHC02448I   size      number of CKD cylinders or 512-byte FBA sectors
HHC02448I             (required if model not specified else optional)
</pre>

All of the Hercules utilities that begin with the characters `cckd`:

```
cckd2ckd
cckd642ckd
cckdcdsk
cckdcdsk64
cckdcomp
cckdcomp64
cckddiag
cckddiag64
cckdmap
cckdswap
cckdswap64
```

only work with _**compressed**_ CCKD dasd. They do _**not**_ work with regular CKD dasd.

To convert your dasd from CKD format to CCKD format, use the `dasdcopy` command, being careful to specify the `-o` (output format) option as `CCKD`.

Or, you can create your dasd again using the correct options:
<pre>
dasdinit <b><i>-z</i></b> -a pub014.243 3350 PUB14
</pre>

Finally, I personally would _**never**_ do a level cckdcdsk -4. I myself would _only_ ever do a level 3.

Level 4 is _very risky_ IMO, and was only ever designed to be used as a very last resort. _(in fact, an argument could be made that the option should not even exist at all!)_

Always, always, ALWAYS try a level 3 _first_, and then and then _only_ if the level 3 fails, should you then _**MAYBE**_ consider doing a level 4.

cckdcdsk level 4 considers virtually _everything_ that it sees as "an error" by default, and then proceeds to try and "recover" from that error by trying to locate whatever track data it can find that appears like it might _maybe_ be the correct data for that track. It might not be the correct data though. Maybe it is, but maybe it isn't. There's no way for it to know for certain.

This is because of the way level 4 was purposely designed: it purposely does not trust anything that it sees as legitimate, and instead considers everything it sees as an error (something it cannot trust), and as a result, attempts to "recover" the track's data by trying to find anything that looks like it _might_ be valid track data, and then rebuilds the track from that. _**Very dangerous**_ IMHO!!

Always _only_ do a cckdcdsk -3. If it doesn't work, then I personally would restore your dasd from backup because it is too damaged. You can try a cckdcdsk -4, but the results cannot be trusted IMHO.

Hope that helps!
