### ISSUE TITLE
Displayed S/370 BC mode PSW does not match actual PSW loaded by LPSW instruction.

### ISSUE THREAD

**Issue by wably** [SDL-Hercules-390/hyperion#325]
Hey @Fish-Git,

As the title says, an `LPSW` instruction is trying to load a disabled wait PSW of **X'00020000-00000000'** and instead what gets loaded is **X'00020000-80000000'**.

Besides the fact that it is simply not accurate and doing what it is supposed to do, it is preventing me from completing a test script (using runtest) because runtest isn't recognizing the disabled wait PSW with bit 33 set.  (I think runtest should recognize _any_ disabled wait, but that's another issue).  Thus runtest sits there until it times out even though the CPU is in fact in a disabled wait, albeit with this slightly incorrect PSW.

I tried to look at the LPSW code in `control.c` and see if I could find a problem, but unfortunately the actual code to perform an LPSW is everywhere else but in control.c.  I'm simply not versed enough in Hercules internals to track all this down.

This LPSW incorrectly loaded value does not occur in archlvl z/Arch; only in S/370.  And I need to be in S/370 mode because the test script is for an assist instruction that has a bug.  I'll be committing a fix for that assist soon enough, but of course I want the the standalone test case to go with it.

This is super easy to recreate.  At a minimum, place an LPSW instruction in memory and a disabled wait PSW that it can load in some doubleword.  Use the restart new PSW to point to the LPSW and issue restart.   I've also attached the full log of the recreation, and a .conf file so it can be recreated at will.

As an aside, I also found that this error occurs on a SDL 4.3 clone from approximately May 14th on a Raspberry PI too, so this doesn't seem to be a Windows cause or anything like that.

Here are the files (hrc.txt is the full log; lpsw1.txt is the .conf file to recreate):

* [hrc.txt](https://github.com/SDL-Hercules-390/hyperion/files/5322207/hrc.txt)
* [lpsw1.txt](https://github.com/SDL-Hercules-390/hyperion/files/5322210/lpsw1.txt)

Also, note that I turned on instruction trace (`t+`) in the attached log, and the trace shows the correct PSW in storage, but that isn't exactly what gets loaded!

Regards,
Bob

**Comment by Fish-Git** [comment]
Hi Bob!

I'm sorry to have to say this to you, _but ..._ &nbsp; _**[PEBKAC!](https://en.wikipedia.org/wiki/User_error#Acronyms_and_other_names)**_ &nbsp; `;-)`

Your restart PSW is an EC mode PSW (0008 bit is on), but the PSW that the `LPSW` instruction ends up loading is a BC mode PSW (0008 bit is off). Thus bit 32 (not 33) is set because bits 32-33 of a BC mode PSW is the ILC (Instruction Length Code) field, and the `LPSW` instruction that you executed to load that PSW was 4 bytes long.

There is no problem. Hercules is behaving correctly.

**Comment by Fish-Git** [comment]
p.s. I am unable to download your attached "lpsw1.txt" file. &nbsp;Either GitHub is messing up or else something else weird is going on. I downloaded your "hrc.txt" attachment just fine, but I'm unable to download the "lpsw1.txt" file. Clicking the link accomplishes nothing.

**Comment by Fish-Git** [comment]
Fish wrote:

> p.s. I am unable to download your attached "lpsw1.txt" file. [...]

NEVER MIND! It must have been a problem with Chrome. I cleared my cache and tried again, and now both links work just fine. Sorry!

**Comment by Fish-Git** [comment]
p.p.s. &nbsp; My '\@' isn't "\@fish", it's "\@Fish-Git". &nbsp; &nbsp; "\@fish" is completely different person:

(this is someone else, NOT me):

* https://github.com/fish

(THIS is me):

* https://github.com/Fish-Git

**Comment by wably** [comment]
Fish,

I changed the PSW at location 210 to be 000A0000 in the first word, thus it is now an EC-mode disabled wait, and indeed the bogus bit is no longer turned on.  I can live with that.

But, I still don't think it should be turned on anyway; a wait PSW is loaded and no ILC should be set in a BC PSW.   Unfortunately, the S/370 POP is a little ambiguous on the situation.  First of all, it says:

> The current PSW is replaced
contents of the doubleword
location designated by the
operand address.

Which tells me I get to choose _all 64 bits_ that I want, even if they are incorrect.  And then it says:

> If the new PSW specifies the BC mode,
information in **bit positions 16-33** of
the new PSW is not retained as the PSW
is loaded. When the PSW is subsequently
stored, these bit positions contain the
new interruption code and the
instruction-length code.

Well, my 'new' ILC is 00 (as in, both bits off).  It does not come out and say that the LPSW instruction's length is the new ILC.  Again, a bit ambiguous.

For what it is worth, a S/370 virtual machine does not turn on bit 32 when loading a disabled wait 00020000 PSW.

Sigh.  In any case, I'll just use an EC disabled wait and move on.  Thanks for looking at it.

Regards,
Bob

**Comment by Fish-Git** [comment]
Hmmmm... What you say does make sense: if you load a PSW that has the two ILC bits specified as 00, then that is what the PSW should be set to!

The problem (bug? debatable!) is apparently with how Hercules handles the loading and storing/displaying of the PSW.

The loading of the PSW is done by the `ARCH_DEP(load_psw)` function (line 182 of cpu.c). Line 321 is where message `HHC00800I` is issued (_"loaded wait state PSW"_), which calls function `str_psw` which calls `str_arch_psw` which calls `copy_psw` to get an architecturally accurate(?) copy of the current PSW that is can then print.

The `copy_psw` function simply does a call to `ARCH_DEP(store_psw)`, which is how the ILC field of the PSW got set the way it did, since it came directly from our `PSW` struct's `ilc` field, which itself got set to the value '4' as a result of the execution of the `LPSW` instruction.

Now whether all of that is "right" or "wrong" is somewhat debatable. I fully understand that it is somewhat confusing in that the PSW that is displayed by messages `HHC00800I` and `HHC00809I` are not what you expect, but that's just the way Hercules has worked since probably forever. As far as I know none of that code has ever been modified, so the behavior you're seeing is the same behavior that Hercules has been exhibiting since forever.

Now whether our current behavior can be called "correct" or not is certainly debatable!

But is it really worth the effort and extra complication to fix it?

IMHO it is not.

If you want to give it a go, feel free! But me? I personally don't feel it's worth the effort.

**Comment by wably** [comment]
No, I don't feel it is worth the effort either.  I wouldn't have even noticed it except that 'runtest' wont accept it; as I said earlier I think runtest should accept any disabled wait value, because differing values can be used as a means to identify success or fail in a test routine.  In other words, I think runtest should key off the of the 'disabled psw' text words in the Hercules message and not the actual value of the PSW itself.

However, runtest does work if I make the disabled wait an EC 000A0000 PSW, so I will just go with that.  

Thanks,
Bob

**Comment by ivan-w** [comment]
Page 6.35 of GA22-7000-10 says (I quote) : "In the BC mode, the instruction-length code in the PSW is unpredictable"

**Comment by Fish-Git** [comment]
> _"In the BC mode, the instruction-length code in the PSW is unpredictable."_

Not only that, but for the `LPSW` instruction (page 10-20) it also says:

> _"If the new PSW specifies the BC mode, information in bit positions 16-33 of the new PSW is not retained as the PSW is loaded. When the PSW is subsequently stored, these bit positions contain the new interruption code and the instruction-length code."_

The ILC is in bit position 32-33 (bit 16-31 is the Interruption Code). So apparently, whenever a BC mode PSW is loaded, whatever was specified in storage for bits 16-33 of the PSW being loaded, is ignored, and whatever the _REAL_ ILC and Interruption Code actually are at that moment, are retained in the resulting PSW.

So Hercules is indeed doing things correctly. No fix is needed.
