### ISSUE TITLE
Cosmetic: MIPS/Instruction count skewed when running under SIE

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#335]
When running a debian/s390x system directly under hercules the following command yields the following output: 
```
$ time xz -k -T 0 -v go.tar
go.tar (1/1)
  100 %        36.0 MiB / 105.4 MiB = 0.342   120 KiB/s      15:02

real    15m3.005s
user    46m13.975s
sys     2m0.719s
```

Doing the same under a SIE virtualized environment yields this : 
```
~$ time xz -v --threads=0 go.tar
go.tar (1/1)
  100 %        36.0 MiB / 105.4 MiB = 0.342   107 KiB/s      16:49

real    16m55.218s
user    50m6.000s
sys     2m58.405s
```
Ok, so far it's all peasy and squeezy.. a 5%-10% overhead due to SIE is to be expected..

The problem is the displayed MIPS count.. When running native, the program (running on 4 processors) shows between 300-350 MIPS.. When running under SIE... about 5-10 MIPS... It's as if the instructions executed under SIE are not being taken into account  for the overall system.

Running : Hercules version 4.3.9999.0-SDL-geab6bf3d (4.3.9999.0)

**Comment by Fish-Git** [comment]
Hi Ivan!

Please try the following patch and tell me whether it resolves your problem or not:

```diff
From: "User Name" <user@example.com>
Date: Wed, 25 Nov 2020 12:39:41 -0800
Subject: [PATCH] Short description

Details of change, perhaps spanning...
...multiple...
...lines.

diff -r -a -x .git -x 'msvc.AMD64.*' -x 'msvc.dllmod.*' -x 'msvc.debug.*' -x '*.suo' -x '*.ncb' -x '*.user' -x '*.htm' -x WORK -x DICTS -x FILES -x 'allTests.*' -x '*.rej' -x '*.orig' -x AutoBuildCount.h -x '*.cmp*' -x '*.comp*' -Nu hyperion-1/sie.c hyperion-0/sie.c
--- hyperion-1/sie.c	2020-11-19 07:42:18.245466500 -0800
+++ hyperion-0/sie.c	2020-11-25 12:38:02.737790000 -0800
@@ -894,6 +894,9 @@
 
         PTT_SIE( "run_sie setjmp", 0, 0, 0 );
 
+        /* Establish longjmp destination for program check or
+           RETURN_INTCHECK, or SIE_INTERCEPT, or longjmp, etc.
+        */
         if (!(icode = setjmp( GUESTREGS->progjmp )))
         {
             PTT_SIE( "run_sie run...", 0, 0, 0 );
@@ -1154,6 +1157,19 @@
                 && !SIE_INTERRUPT_PENDING ( GUESTREGS )
             ));
         }
+        else
+        {
+            /* Our above instruction execution loop didn't finish due
+               to a longjmp(progjmp) having been done, bringing us to
+               here, thereby causing the instruction counter to not be
+               properly updated. Thus, we must update it here instead.
+           */
+            GUESTREGS->instcount +=  MAX_CPU_LOOPS/2;    /* (guess) */
+            UPDATE_SYSBLK_INSTCOUNT( MAX_CPU_LOOPS/2 );  /* (guess) */
+
+            /* Perform automatic instruction tracing if it's enabled */
+            do_automatic_tracing();
+        }
 
         PTT_SIE( "run_sie !run", icode, 0, 0 );
 
```

It basically adds to the `run_sie` loop in `sie.c` the same logic that our existing `run_cpu` loop is doing in `cpu.c`.

If it fixes your problem then I'll go ahead and commit it.

Thanks!

_(And sorry about that! It was probably one of my updates to sie.c that caused it!)

**Comment by ivan-w** [comment]
Bummer.. Ok .. a few things...
- I jumped to conclusions too quickly ! The instruction count is always correct*ish*... Around 200B instructions for the test - virtualized or standalone.
- Applying the proposed patch doesn't have any big effect overall
- Something that used to work and now doesn't is when running code under SIE, the PSW shown for any CPU used to be the virtual PSW (with a S indicator in the status) - but now we only get the PSW of the CPU at SIE entry. I have no idea if the 2 are related or not.

**Comment by Fish-Git** [comment]
Your original problem report was that the MIPS rate wasn't right (was too low), which a too low instruction count would certainly affect. Thus my proposed stab at trying to address that oversight. I'm sorry it didn't help. &nbsp; `:(`

Your new problem description however is even more baffling! Can you explain how to reproduce it? I'd like to try and look into it for you, but need a simple and reliable way to "see" the problem in action. I myself of course use my HercGUI to run Hercules with and am not seeing anything unusual regarding the displayed PSW or MIPS rate under SIE (i.e. when I run z/OS under z/VM for example), but then the code that's being executed is likely different from the code that's being executed in your case. My HercGUI is getting its values from `dyngui.c` whereas I'm presuming you're running Herc from the command line (i.e. in normal "panel" mode) and thus getting your values from the code in `panel.c`.

I'll give Herc a try in panel mode as soon as I get a chance and get back to you, but if the problem _is_ somewhere in panel.c, I'm not going to look forward to trying to find where the bug might be. IMHO it is _**WAY**_ more complicated (sloppy?) than it should be. I've made many changes to it over the past years, yes, but they've all been for the most part relatively minor IMO. Given panel.c's complexity however, I wouldn't be surprised that one of them (one of my "tweaks") somehow broke things, thereby causing your current broken behavior.

_You're_ Hercules developer, Ivan! Can't _you_ debug `panel.c` for yourself to discover the cause of the problem?! &nbsp; `;-)`

**Comment by Fish-Git** [comment]
Okay, this is weird! We've likely got a _SERIOUS_ bug somewhere in `panel.c`, most likely introduced by me! (for which I profusely apologize!) I don't know what the bug is, but based on my testing, there is definitely a bug somewhere that is, believe it or not, impacting the execution of the guest.

So far I've only done a few z/OS under z/VM tests (I will next try some z/OS native tests to confirm), but so far, each time I've IPLed z/OS under z/VM _**in panel mode**_ (as opposed to in HercGUI mode), I've experience all sorts of unexplainable weirdness: things crashing _(such as ZFS!)_, hangs _(the initial part of IPL of z/OS gets stuck and never switches over to starting all of the other CPUs!)_, etc. Really weird shit like that. But each time I try the same thing using HercGUI, it works perfectly!

I don't know what the frick I did to break things, but it seems obvious to me that _something_ is broken in `panel.c` that's causing this unusual behavior. I'm going to start digging into it, but I wanted to give the rest of you a "heads up" about what's going on. This bug -- _whatever it is!_ -- might also explain the unusual behavior other people have been having running their TXF tests too. I suspect it might be a PSW issue: `panel.c` is getting a working copy of `regs` and of the current PSW for display purposes, but I'm thinking I might have introduced a bug somewhere wherein doing so is somehow causing some `regs` field(s) in the actual CPU it's getting its copy from to get changed. But that's just a pure 100% guess at this point, but something like that would certainly explain the weirdness.

I'm going to start digging into this ASAP, obviously, but I would appreciate others taking the time to look into this as well. That is to say, I would appreciate all the help I can get with tracking this bug down! Any/all help _greatly_ appreciated!

Thanks!

_(and I'm **very sorry** about all this!!)_

&nbsp; &nbsp; ``:`(``

**Comment by ivan-w** [comment]
For info.... 
Apparently, the problem was introduced by commit 9ceed2cc7261820eef01c55dac9b9a6ae47636b2
(thank you git bisect)

**Comment by ivan-w** [comment]
Also.. I stand corrected.. The 'S' indicator shows in the panel... Just the MIPS estimation that is broken when running code under SIE...

**Comment by Fish-Git** [comment]
> Okay, this is weird! We've likely got a _SERIOUS_ bug somewhere in `panel.c`, most likely introduced by me!

> so far, each time I've IPLed z/OS under z/VM _**in panel mode**_ (as opposed to in HercGUI mode), I've experience all sorts of unexplainable weirdness: things crashing _(such as ZFS!)_, hangs _(the initial part of IPL of z/OS gets stuck and never switches over to starting all of the other CPUs!)_, etc.

Which I'm _NOW_ unable to reproduce!! (SIGH!)

Likely false alarm. (Sorry!) I must have simply done something stupid like forgetting to reset my dasd before each test or something. I've done about a half dozen or so additional tests after posting the above, and it appears everything is working just fine on panel mode. Identical to HercGUI mode. Both modes work identically and work just fine.

Sorry for the false alarm. &nbsp; `:(`

**Comment by Fish-Git** [comment]
> For info....
> Apparently, the problem was introduced by commit [9ceed2c](https://github.com/SDL-Hercules-390/hyperion/commit/9ceed2cc7261820eef01c55dac9b9a6ae47636b2)
> (thank you git bisect)

So we _shouldn't_ be using GUESTREGS in sie.c?! Crap! My bad. &nbsp; `:(`

Can someone explain the rule for when GUESTREGS _should_ be used (and not plain regs) and vice-versa? (i.e. when regs should be used and _not_ GUESTREGS?)

Sie still confuses the hell out of me for some reason! &nbsp; `:(`

So.... can you fix it for me, Ivan? Where should we be using `regs` instead of GUESTREGS in `run_sie`??

**Comment by Fish-Git** [comment]
> Also.. I stand corrected.. The 'S' indicator shows in the panel... Just the MIPS estimation that is broken when running code under SIE...

And my proposed patch didn't help?! Then why is the MIPS rate wrong? Is it the `regs` vs. GUESTREGS issue? Is that what's causing it? Can you fix it for me? In return I promise not to F**K with sie.c code ever again! (since I can't seem to get it right!)

**Comment by Fish-Git** [comment]
Maybe that's where our TXF bug is too? Me using GUESTREGS instead of `regs` (or HOSTREGS?!) or vice-versa in the code related to TXF? It would make sense since, AFAIK, our remaining TXF bug(s) is/are related to running under z/VM whereas native works fine. (At least I _think_ that's true. At this point I'm so freaking confused I don't know which end is up. I'm burning out. I need to step away.)

**Comment by ivan-w** [comment]
Fixed. use regs instead of GUESTREGS in sie.c/run_sie for per CPU instruction count tally

Fixed by d8a549ced25401010e6b29d5b19a6d750e8a12dc

**Comment by Peter-J-Jansen** [comment]
Thanks Ivan, as far as I can tell, the MIPS counter seems now to be working again.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> Use `regs` instead of `GUESTREGS` in `sie.c` `run_sie` for per-CPU instruction count tally.

_(Doh!)_ Yes, that makes perfect sense now. Thank you, Ivan!
