### ISSUE TITLE
Translation-Specification Exception (PIC 12) with z/VSE 6.2 and Hercules 4.3.0

### ISSUE THREAD

**Issue by bbingham839** [SDL-Hercules-390/hyperion#338]
_**Note:** this issue is virtually identical to issue ["z/OS 2.4 continuous PIC 12 (\#275)"](https://github.com/SDL-Hercules-390/hyperion/issues/275), and is likely being caused by the same bug._
___
Previously, my z/VSE 6.2 system worked just fine with SDL Hyperion 4.2.1.

With SDL Hyperion 4.3 however, I am now getting a disabled wait state 1000 shortly after IPL due to a "Translation-Specification Exception" code 00012:
```
14:00:18.977 00000F0C HHC00801I Processor CP00: Translation-specification exception code 0012 ilc 4
14:00:18.977 00000F0C HHC02324I PSW=0705600000000000 0000000000351CA4 INST=50208DC0     ST    2,3520(0,8)            store
14:00:18.978 00000F0C HHC02326I V:0000000000351DC0:K:06=0034FDEE 00000000 00000000 00000000  ................
14:00:18.978 00000F0C HHC02269I R0=000000000060E000 R1=0000000000000001 R2=00000000A068325E R3=0000000000000000
14:00:18.978 00000F0C HHC02269I R4=00000000003575F0 R5=0000000000000000 R6=0000000000357560 R7=00000000006005B8
14:00:18.978 00000F0C HHC02269I R8=0000000000351000 R9=0000000000350000 RA=000000000034F000 RB=000000000060EA80
14:00:18.978 00000F0C HHC02269I RC=0000000000351CA4 RD=0000000000684B00 RE=0000000000000000 RF=0000000000683B00
14:00:18.978 00000F0C HHC02271I C0=000000000D84EE40 C1=0000000001312004 C2=0000000001148580 C3=000000000048000C
14:00:18.978 00000F0C HHC02271I C4=000000000000000C C5=0000000001146300 C6=0000000010000000 C7=0000000001312004
14:00:18.978 00000F0C HHC02271I C8=0000000000010000 C9=0000000000000000 CA=0000000000000000 CB=0000000000000000
14:00:18.978 00000F0C HHC02271I CC=0000000000000000 CD=0000000001312004 CE=00000000C0081144 CF=0000000011F961E8
14:00:18.978 00000F0C HHC02272I AR00=00000000 AR01=00000000 AR02=00000000 AR03=00000000
14:00:18.978 00000F0C HHC02272I AR04=00000000 AR05=00000000 AR06=00000000 AR07=00090006
14:00:18.978 00000F0C HHC02272I AR08=00090006 AR09=00000000 AR10=00000000 AR11=00000000
14:00:18.978 00000F0C HHC02272I AR12=00000000 AR13=00000000 AR14=00000000 AR15=00000000
14:01:22.424 00000F0C HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000001000
```

I have attached my Hercules config file and the log file from the abend.

* [Hercules 4.3.0 GITHub Issue338_File_001.zip](https://github.com/SDL-Hercules-390/hyperion/files/5631353/Hercules.4.3.0.GITHub.Issue338_File_001.zip)

I tried to upload my IPL volumes and other data, but apparently cannot upload any files larger than 10MB. Any ideas?

**Comment by bbingham839** [comment]
I tried to upload my IPL volumes and other data, but apparently cannot upload any files larger than 10MB. Any ideas? I have attached my Hercules config file and the log file from the abend.
[Hercules 4.3.0 GITHub Issue338_File_001.zip](https://github.com/SDL-Hercules-390/hyperion/files/5631353/Hercules.4.3.0.GITHub.Issue338_File_001.zip)

**Comment by bbingham839** [comment]
Closed by mistake.

**Comment by Fish-Git** [comment]
> I tried to upload my IPL volumes and other data, but apparently cannot upload any files larger than 10MB. Any ideas?

1. How large are they? What is the size of your Hercules dasd image files?
2. Are all of the dasd image files truly needed in order to reproduce the problem? Or is only the sysres volume needed? It would be preferable if you could create a minimal system that reproduces the problem without the need of other volumes. Is that possible?
3. Have you tried compressing them? (using e.g. WinZip or 7-Zip, etc?)
4. Do you have a cloud drive account somewhere (such as Google Drive or DropBox, etc) where you could upload them to instead? (and then just provide us the link to them?)
5. Are you sure you are legally _permitted_ to share your dasds with us? z/VSE 6.2 is an IBM License Program Product offering after all!

If push comes to shove, I could allow you to upload them to my FTP site as long as they're not too large. (My FTP site only has limited space.) Let me know. Thanks.

**Comment by bbingham839** [comment]
z/VSE requires a minimum of two volumes to IPL (DOSRES & SYSWK1) . The volumes are 2.8GB and I zipped them down to 244MB. I do not have a cloud drive to upload them to.

Billy

**Comment by Fish-Git** [comment]
> I do not have a cloud drive to upload them to.

Please FTP upload to my "incoming" folder:

* ftp://www.softdevlabs.com
* ftp://www.softdevlabs.com/incoming/

_**PLEASE NOTE:**_ my incoming folder is _write-only_. You will be able to upload file into the folder, but you will _not_ be able to download anything from that folder nor even list its contents, as both actions require _read_ access to the directory and, as explained, the directory only has _write_ access. So don't freak out when you can't "see" the file that you just uploaded. The upload likely worked just fine. You just won't be able to see the results.

Send me an email one the upload completes. My email address is "fish" at softdevlabs (.com of course).

Thanks.

**Comment by Fish-Git** [comment]
Fixed by commit 7e35ff11043afd16c546246e81aa86df202573c6.

I'd appreciate it, Bill (@bbingham839), if you could confirm the fix for yourself.

It seems to fix the problem with the test dasds you sent me, while at the same time _also_ fixes the original ["z/OS 2.4 continuous PIC 12 (\#275)"](https://github.com/SDL-Hercules-390/hyperion/issues/275) issue as well.

If you're not setup to build Hercules for yourself, I suppose I could upload the fixed version to my FTP site for you to then download and try. Let me know.

I will wait a day or three for you to confirm the fix is good before closing this issue.

**Comment by bbingham839** [comment]
I wouldn't even know where to begin to build Hercules. Sorry.


Billy

**Comment by Fish-Git** [comment]
> I wouldn't even know where to begin to build Hercules. Sorry.

That's okay. I've uploaded the fixed version here:

* http://www.softdevlabs.com/downloads/Billy-Bingham-338-fix/index.html

You only need the binaries. (The PDB files are for me should something goes horribly wrong.) The .md5 file is a checksum/hash file you an use to verify the integrity of your download.

Give it a whirl and let me know whether it works just as well for you as it did for me.

This download is only _extremely_ temporary and will disappear the moment you confirm the fix is good.

Thanks.

**Comment by bbingham839** [comment]
Will do.


Billy

**Comment by bbingham839** [comment]
That seems to have resolved the issue. I've IPLed a couple times with no
issue:

8:26:36.114 0000150C HHC01413I Hercules version
4.4.9999.10299-SDL-g7e35ff11 (4.4.9999.10299)
18:26:36.114 0000150C HHC01414I (C) Copyright 1999-2020 by Roger Bowler,
Jan Jaeger, and others
18:26:36.114 0000150C HHC01417I ** The SoftDevLabs version of Hercules **
18:26:36.114 0000150C HHC01415I Build date: Dec  4 2020 at 23:19:58


Thanks for your effort in resolving this.



Billy

**Comment by Fish-Git** [comment]
> That seems to have resolved the issue.

Thank you.

> Thanks for your effort in resolving this.

You're very welcome. I apologize for introducing the bug in the first place!
