### ISSUE TITLE
CMPSC.txt found in util subdirectory

### ISSUE THREAD

**Issue by wrljet** [SDL-Hercules-390/hyperion#351]
I'm wondering why CMPSC.txt is in the hyperion/util subdirectory.

Is that supposed to be there?

Bill

**Comment by Fish-Git** [comment]
> I'm wondering why CMPSC.txt is in the hyperion/util subdirectory.

The CMPSC.txt file that is in the hyperion/util subdirectory is the source code to the "inline stand-alone machine code" that exists in the cmpsc.rexx script in the scripts subdirectory:

https://github.com/SDL-Hercules-390/hyperion/blob/f4a8b54b07f426420a3fa4a6fda1205c2fcf6d87/scripts/cmpsc.rexx#L689-L699

https://github.com/SDL-Hercules-390/hyperion/blob/f4a8b54b07f426420a3fa4a6fda1205c2fcf6d87/scripts/cmpsc.rexx#L725-L961

The scripts subdirectory also contains a cmpsc.cnf file too that defines the Hercules environment required for the test. You start Hercules using the cmpsc.cnf configuration file, and then issue the `exec cmpsc.rexx (args...)` command to perform the test.

At the time (years ago), it was the only (semi-formal) Hercules test that we had that was able to test our `CMPSC` instruction. It was placed in the util subdirectory since it's not Hercules code per-se. It's mainframe assembler code, much like the cckddump.hla, cckdload.hla and TMOUNT.txt files are.

As the script's comments state, we have (well okay, _**I**_ have!) a much more comprehensive and thorough _offline_ Windows or Linux (both are supported) testing tool that is able to much better test Hercules's CMPSC instruction logic, called "cmpsctst.exe". It's mentioned (some might argue, _buried_) in our [README.CMPSC](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.CMPSC.md) document, at the very end, in the footnote.

> Is that supposed to be there?

_Technically_, yes, as explained.

But I _suppose_ if I transferred ownership of my cmpsctst respository over to the SDL-Hercules-390 organization, we could probably get rid of it (and the other files I mentioned: cmpsc.rexx and cmpsc.cnf in the scripts subdirectory).

As an explanation, it was only created to shut up a former developer who at the time complained that my offline "cmpsctst" program wasn't properly testing the instruction since the test wasn't being run from within Hercules itself.

He refused to accept that that was largely (if not _completely!_) immaterial, since the purpose of the test was to verify the sanity/accuracy of the actual _algorithm_ that Hercules was using to accomplish the instruction's goals. The fact that e.g. the instruction's storage accesses were not being done by Hercules and were instead accessed directly by 'C' language APIs, etc, and therefore irrelevant was largely lost to him. He refused to see that. Hence, what you see was written to make him happy.

Does that answer your question?

**Comment by wrljet** [comment]
> 
> Does that answer your question?

Yes!
