### ISSUE TITLE
Propose eliminating the need to add test files to VisualStudio project files

### ISSUE THREAD

**Issue by wably** [SDL-Hercules-390/hyperion#358]
I'd like to discuss a proposal I am making to consider eliminating the need to add emulator test related files to the various VisualStudio project files that are also part of the entire project.

At present, the various collection of test files, core images, assembly sources, test documentation files, and more (the stuff in the /tests directory) are contained in the various versions of the VisualStudio project files.  When committing new test materials, modifying the project files to add these test materials is a burdensome process that mostly seems unnecessary.  At present, new test materials must be added to six different project-related files.

My justification for eliminating this process is this:  before Hercules was on Github, having everything related to Hercules including test files placed into the project files made sense.  The VisualStudio project file represented the total project.  Now, we have Github.   SDL-Hercules-390/hyperion is now the total project.  Github is tracking everything and maintaining history.  Cloning the repository gets you all the files, regardless of their presence (or lack of it) in a compiler IDE project file.

Further, these tests materials are not required for compilation or to build the executables for the emulator.  Their presence in the compiler IDE project files seems to be more for documentation possibly rather than any real need for them to be there.  This same argument could be made for other types of files such as the READMEs, autoconf, html directories and more - again all stuff not needed for compiling/linking by VisualStudio.  However, for now the test materials are the focus of this proposal.  I'm not proposing to remove any files currently listed in the compiler IDE project files, rather just to cease with adding new ones.

Maybe some members of the team who sometimes commit non-compilation materials could weigh in and let's see if there is any consensus on this.

Regards,
Bob

**Comment by Fish-Git** [comment]
> My justification for eliminating this process is this: before Hercules was on Github, having everything related to Hercules including test files placed into the project files made sense. The VisualStudio project file represented the total project. Now, we have Github. SDL-Hercules-390/hyperion is now the total project. Github is tracking everything and maintaining history. Cloning the repository gets you all the files, regardless of their presence (or lack of it) in a compiler IDE project file.
> 
> Further, these tests materials are not required for compilation or to build the executables for the emulator. Their presence in the compiler IDE project files seems to be more for documentation possibly rather than any real need for them to be there. This same argument could be made for other types of files such as the READMEs, autoconf, html directories and more - again all stuff not needed for compiling/linking by VisualStudio. However, for now the test materials are the focus of this proposal. I'm not proposing to remove any files currently listed in the compiler IDE project files, rather just to cease with adding new ones.

Your argument is flawed.

Technically, _**none**_ of the files currently listed in the IDE's project files are needed to build Hercules. Not even any of the `.c` or `.h` etc. files! This is because the Hercules VC Project is defined as a _makefile_ project and not a regular Win32(*) project. Having _all_ of the Hercules project's files in the IDE's project list is simply a matter of _convenience_, not an actual requirement.

The purpose of an IDE (Integrated Development Environment) is to have a single place where _all_ development activity can take place, including not only editing of files but also building and testing (debugging) as well.

And IMHO, anything that makes Hercules development easier (more convenient) for the user/developer is a Good Thing(tm), and not something to be discouraged.

Using the Visual Studio IDE is the standard, _expected_ way for doing Windows program development, and one which virtually all Windows software developers are familiar with. And having _ALL_ of the given application's files -- even those that are technically not needed in order to build the program -- defined as being part of the Visual Studio project is an important part of that.

My opinion is just my own of course.  I've only been developing software on Windows for close to 30 years now, so others may of course feel differently. &nbsp; `;-)`

p.s. The Visual Studio 2015, 2017 and 2019 project files are all virtually identical, so you once you've added the files to one, the exact same update can be applied to the others. Visual Studio 2008 (which is what I'm still using) is the odd duck however. Its project file format is very different. But to make things easier for you, _none_ of you really have to bother updating _any_ of the Visual Studio project files if you don't want to. I'll take care of that for you. I try to monitor all commits made to the repository (simply out of pure intellectual curiosity; I like to see what others are doing and how they did it; that's how I learn and become a better Hercules developer), and if I see one of you add some new files without also adding them to the VStudio project files, then I typically go ahead and take care of that for you. We're a _TEAM_ after all, right? We all watch each other's backs. We all help each other.
___
(*) Most Windows projects are defined as "Win32" projects, which is just a generic Visual Studio project-type for a regular GUI program. For those type of projects, yes, _all_ of the files needed to build the program _must_ be formally added to the VStudio project so that VStudio knows it needs to build it. But _makefile_ projects are of course different. The building of a makefile project is _not_ controlled (managed) by Visual Studio. Rather, it is controlled via your defined makefile.

Technically, Visual Studio is _not needed at all_ in order to build Hercules. The way the Windows version of Hercules is designed, you open a Command Prompt window rooted at the main Hercules source files directory, and enter the command e.g. `makefile.bat DEBUG-X64 makefile.msvc 64 -a` to build it. But since as I said most Windows developers are used to using the IDE to manage their entire project build cycle with -- from editing files to building and testing (debugging) it as well -- I have configured Hercules's Visual Studio project to automatically do that for you, all from within the IDE itself, with a simple click of Visual Studio's "Rebuild All" toolbar button.

Again, this makes things much easier for the Hercules user/developer since it's the expected way that things are done on Windows.

Convenience it good. Inconvenience is not. Adding new files to the Visual Studio project files may be an inconvenience to us developers, but then that's our job! We frequently do things which may, at the time, be inconvenient to us in order to make it _more_ convenient to the user.

**Comment by wably** [comment]
Fish,

> Your argument is flawed.

It wont be the first time.

> The purpose of an IDE (Integrated Development Environment) is to have a single place where all development activity can take place, including not only editing of files but also building and testing (debugging) as well.

I guess some may use the IDE for developing the test files.  I myself don't use the IDE for that particular purpose.

> And IMHO, anything that makes Hercules development easier (more convenient) for the user/developer is a Good Thing(tm), and not something to be discouraged.

For me, it discourages me from providing these additional materials.  There is a certain pain point and this reaches it.  I am a somewhat nervous committer - I don't make them often and always have a sense of dread when I do it - because this stuff is out of my element (as a life long mainframer).

As for the disposition of this issue, I guess it can be closed.  I was hoping others would weigh in and we could get a feel for whether this indeed is a problem for others or not.  But no one else offered any opinions so it must just be me.

Regards,
Bob

**Comment by Fish-Git** [comment]
> I guess some may use the IDE for developing the test files. I myself don't use the IDE for that particular purpose.

Neither do I. I have a separate SATK Visual Studio project/solution for that, containing all of my runtest tests (.asm, .tst. core, .list and .pdf). But I do use the VStudio editor as my primary editor for just about everything, including editing .asm assembler source files and just about any other file too (such as .html files, .tst files, READMEs, .am files, bash scripts, Windows batch files, etc, etc, etc.) Others might feel more comfortable using different editors for different filetypes, but I prefer to use VStudio for just about everything since I spend so much time in it. It's probably the one app that's open virtually all day every day.

> For me, it discourages me from providing these additional materials.

What additional materials? We're not talking about creating any new files (other than the ones required for a new standalone runtest .tst of course: .asm, and .tst, and the .list and .core output from SATK/ASMA). The only issue you raised in your GitHub Issue was the pain of _adding_ those files to the Visual Studio project files, and as I said, I'm entirely willing to take care of that for you myself (and by "you" I mean not just you specifically but for _any_ member of the Hercules team that adds a new file or files to the repository).

> As for the disposition of this issue, I guess it can be closed. I was hoping others would weigh in and we could get a feel for whether this indeed is a problem for others or not. But no one else offered any opinions so it must just be me.

Unknown since none of them weighed in with their own opinion/thoughts on the matter, but I suspect most of them feel pretty much the same way you do about it. Maybe not as strongly, but I somehow suspect they probably sympathize or agree with your overall sentiment on the matter at least. Most of you are *Nix users, yes? You use *nix as you primary desktop operating system? Or, if Windows is your primary desktop o/s, I suspect it's not to do software development with (i.e. I suspect the members of our team that use Windows (do we even _have_ any besides me?!) are probably like you and only do mainframe software development, and maybe only use Windows for everyday use but not to develop Windows software and thus are also not familiar with using Visual Studio.)

I'll leave this Issue open for another few days maybe, to give others a chance to maybe chime in with their own thoughts if they want. I think maybe they were waiting for me to reply first. and now that you and I have had several back-and-forths, they might feel a bit more comfortable with perhaps jumping in with their own opinion now.

But if no one else offers any thoughtful/helpful/constructive thoughts on the matter, I'll go ahead and close it.

But let's give a few days more, just to be on the safe side. &nbsp;`:)`

**Comment by wably** [comment]
Fish,

> What additional materials? We're not talking about creating any new files (other than the ones required for a new standalone runtest .tst of course: .asm, and .tst, and the .list and .core output from SATK/ASMA). The only issue you raised in your GitHub Issue was the pain of adding those files to the Visual Studio project files, and as I said, I'm entirely willing to take care of that for you myself (and by "you" I mean not just you specifically but for any member of the Hercules team that adds a new file or files to the repository)

Yes, I am referring to the four file types you mentioned:  .tst, .asm, .lst, and .core.  Each of these has to be added to a project file in an XML-style format hopefully without making a typo.  And then there are four of these project files; one of them is in a slightly different format.

All I am saying is, it is a tedious process for no actual benefit.  I don't use the IDE to actually work on these files; I do that outside of the IDE.  You say the same.  If no one else is either, then they serve no purpose being inside the project file except to possibly document the entirety of the project by their existence within it.

Further, none of the four project files that have to be updated do I use myself.  I have the older VS2012.  I don't add the four test file types to the VS2012 project file.  Im still using VS2012 because it works great, and I own it.

I understand that you offered to do the update for us, and that is generous, but I wouldn't be comfortable having you do something for me that I am able to do, just because I want to avoid some extra work.   I certainly went through enough of the process and procedure stuff in software work in my career and I understand that sometimes you just have to do stuff that might seem silly because, well, that is the process and other team members or management are expecting it to be done that way.  I'm simply asking if we can avoid it.  If not, or if you would rather not, that's ok too, and I will plod through it.

You asked about my primary desktop OS, and that is Windows.   I rarely do any C coding and if I do it is always for Hercules purposes.  Otherwise, it is all assembler all of the time, on my Hercules mainframe.  I do have a couple of Raspberry Pi's running *nix that also run Hercules and they are great for testing potential commits in that *nix environment too.

Regards,
Bob

**Comment by wrljet** [comment]
Fish, just a data point, since you asked...

I boot to Windows.  Always have, since version 3.
I'm not a MSFT hater, but I fully appreciate what Unix/Linux has to offer.
I use some CAD and EE programs that are important to me, and simply aren't offered for Windows.

I spend a lot of time at the command line in Windows, and use vi as my go-to editor.

I've used MSVC and Visual Studio professionally and as a hobby since forever.
I currently have VS2010, 2013, and 2017 installed.  Only recently not re-installing VS2008
when I set up a new PC about a year ago.

I have been employed to use Unix and Linux on and off in the past, but at home it has always been on
alternate machines, or, in modern times, on a growing array of VMs.  (and now Raspberry Pis as well).

Bill
