### ISSUE TITLE
not a real issue - yet, but something to meditate about 

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#360]
for historical reasons ( got burned once )
in all my cmake builds I check that the int and int_fast  sizes match 

I just got a raspberry pi and my pickiness got rewarded 
both on the 32 and 64 bits the sizes do not match

here the 32bits arm fast sizes 
signed-fast
(  int_fast8_t) 1
( int_fast16_t) 4
( int_fast32_t) 4
( int_fast64_t) 8

unsigned-fast
the same

here the same for 64bits arm 
signed-fast
(  int_fast8_t) 1
( int_fast16_t) 8
( int_fast32_t) 8
( int_fast64_t) 8

unsigned-fast
the same
 
things might work 
but I feel that people should be aware of what they are doing ...

the same with the softfloat 
why Dr. Hauser has specialized builds for the arm architecture
why the 8086-SSE  hercules test run OK ???

meditate people, meditate :-)

cheers
e

building on the rasperry and running the softfloat test suite
for both specialised builds

**Comment by mcisho** [comment]
C11, 7.20.1.3 Fastest minimum-width integer types
2. The typedef name int_fastN_t designates the fastest signed integer type with a width of at least N. The typedef name uint_fastN_t designates the fastest unsigned integer type with a width of at least N.

There is no guarantee that (u)int_fastN_t will be any specific size on any architecture.

**Comment by 00003481** [comment]
I know that, 
I did not go into too much depth about the usage , but I thought it would be something to think about 
I just run a quick and dirty search for the string int_fast and I saw something  I did not like... ( but I might be wrong 

take the definition of the function 
...
softfloat_countLeadingZeros32( uint32_t a )
...


and then the use of it  
...
int_fast32_t sigDiff;
...
softfloat_countLeadingZeros32( sigDiff )
...
all is well on the raspbian 32 bits

but on manjaro ( arch-linux ) 64bits

uint 32t is still 32 bits
but int_fast32_ is 64 bits 

and I feel a bit uncomfortable about it 

cheers 
e

**Comment by 00003481** [comment]
I just run a quick and dirty test on the pi with a 64bits Linux 

the program used that uses the softFloat logic and the builtins 

#include <stdint.h>
#include <stdio.h>

const uint_least8_t s_clz8[256] = {
    8, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

uint_fast8_t s_clz32( uint32_t a )
{
  uint_fast8_t count;
  count = 0;
  if ( a < 0x10000 ) {
      count = 16;
      a <<= 16;
  }
  if ( a < 0x1000000 ) {
      count += 8;
      a <<= 8;
  }
  count += s_clz8[a>>24];
  return count;
}

int main() {

  uint_fast8_t prevc = 0;

  uint_fast8_t coun1;
  uint_fast8_t coun2;
  uint_fast8_t coun3;

  int_fast32_t sigDiff;

  printf( "sigDiff bits %zu\n", sizeof(sigDiff)*8 );

  for ( sigDiff = 0; sigDiff < 10000 ; sigDiff++ ) {

    coun1 = s_clz32(sigDiff) ;
    coun2 = ( sigDiff == 0 ) ? 32 : __builtin_clz(sigDiff) ;
    coun3 = ( sigDiff == 0 ) ? 64 : __builtin_clzl(sigDiff) ;


    if ( coun1 == prevc )
      continue;
    prevc = coun1 ;
    printf( "RYO/clz/clzl  '%2d'/'%2d'/'%2d', %d\n", coun1, coun2, coun3, sigDiff);

  }

  return (0) ;

}

the results

sigDiff bits 64
RYO/clz/clzl  '32'/'32'/'64', 0
RYO/clz/clzl  '31'/'31'/'63', 1
RYO/clz/clzl  '30'/'30'/'62', 2
RYO/clz/clzl  '29'/'29'/'61', 4
RYO/clz/clzl  '28'/'28'/'60', 8
RYO/clz/clzl  '27'/'27'/'59', 16
RYO/clz/clzl  '26'/'26'/'58', 32
RYO/clz/clzl  '25'/'25'/'57', 64
RYO/clz/clzl  '24'/'24'/'56', 128
RYO/clz/clzl  '23'/'23'/'55', 256
RYO/clz/clzl  '22'/'22'/'54', 512
RYO/clz/clzl  '21'/'21'/'53', 1024
RYO/clz/clzl  '20'/'20'/'52', 2048
RYO/clz/clzl  '19'/'19'/'51', 4096
RYO/clz/clzl  '18'/'18'/'50', 8192

and ... IMO the SoftFloat logic gives the wrong result 
the same as far as __builtin_clz is concerned 

cheers
e

**Comment by Fish-Git** [comment]
I don't understand the problem. I see no bug.

> but on manjaro ( arch-linux ) 64bits
> 
> `uint 32t` is still 32 bits
> but `int_fast32_` is 64 bits
> 
> and I feel a bit uncomfortable about it

Why? Why does that make you feel uncomfortable?

> I just run a quick and dirty test on the pi with a 64bits Linux
> and ... IMO the SoftFloat logic gives the wrong result

Huh?! Why do you say that?! Your test _proves_ that is not true! Your test _proves_ that `s_clz32` is always returning the correct value!

> the same as far as `__builtin_clz` is concerned

Correct! So why do you feel that is wrong?

**Comment by Fish-Git** [comment]
> so that' the reason I judge 32 leading zeros wrong
> but I researched and could not find anywhere any good explanation

&nbsp;
* https://docs.microsoft.com/en-us/cpp/intrinsics/lzcnt16-lzcnt-lzcnt64?view=msvc-160

> _If value is zero, the return value is the size of the input operand (16, 32, or 64)._

&nbsp;
* https://www.felixcloutier.com/x86/lzcnt

> _LZCNT will produce the operand size when the input operand is zero._

**Comment by 00003481** [comment]
I was not talking about the result for the zero 
the first 32 was referring to the supposed __builtin_clz arg type
the second 32 was referring to the fast_int32_t argument 

what makes me uncomfortable is 
that count leading zeroes ( 32 ) gives the right result for a something supposedly declared 32 bits
**but with a real size of ( fast_int32_t ) 64 bits** 

while I was typing this reply I run a q&d check 
and I found that the builtins do not do any argument type checking 
they apply the 16/32/64 bit logic to whatever is passed 

so I do not like the logic mostly because I could not find any docs about this behavior
but at least I got an explanation by testing

the snippet 

```C
#include <stdint.h>
#include <stdio.h>

#define clz16 __builtin_clzs
#define clz32 __builtin_clz
#define clz64 __builtin_clzl

int main() {

  int16_t  i16 ;
  int32_t  i32 ;
  int64_t  i64 ;
  for ( i16=1, i32=1, i64=1; i16 < 10; i16++,i32++,i64++ ) {
    printf( "16 clzs  %3d, '%2d'/'%2d'/'%2d'\n", i16, clz16(i16), clz16(i32), clz16(i64) );
    printf( "32 clz   %3d, '%2d'/'%2d'/'%2d'\n", i16, clz32(i16), clz32(i32), clz32(i64) );
    printf( "64 clzl  %3d, '%2d'/'%2d'/'%2d'\n", i16, clz64(i16), clz64(i32), clz64(i64) );
    printf( "\n");
  }
  return (0) ;
}
``` 
compiled with
``` C
cc  -Werror -Wall builtin_clz.c 
``` 
with NO ERRORS
gave the results
```C 
16 clzs    1, '15'/'15'/'15'
32 clz     1, '31'/'31'/'31'
64 clzl    1, '63'/'63'/'63'

16 clzs    2, '14'/'14'/'14'
32 clz     2, '30'/'30'/'30'
64 clzl    2, '62'/'62'/'62'
``` 

bye for now 

if You are interested I will keep You posted on what happens when using the ARM specialised code 

cheers

e

**Comment by Fish-Git** [comment]
> what makes me uncomfortable is
> that count leading zeroes ( 32 ) gives the right result for a something supposedly declared 32 bits
> **but with a real size of ( fast_int32_t ) 64 bits**

Why does that make you uncomfortable? Your tests have so far illustrated absolutely _correct_ and completely _expected/explainable_ behavior. Both tests are returning the correct value of of 32 because of the width of the value being passed to the function is always only 32 bits wide.

In your first test, variable `sigDiff` is declared as type `int_fast32_t`, which on 64 bit ARM is indeed very likely 64 bits wide (since that's the "fastest" way to represent a value that is _at least_ 32 bits wide), but your code is passing that variable to a function that is declared as taking a single _**32 bit**_ input argument. The `__builtin_clzl` function you are calling takes `unsigned long` for its input, which is _very likely_ a type that is only 32 bits wide.**`(*)`**

Thus, even though you are _trying_ to pass a 64 bit variable, it is being truncated to 32 bits instead, resulting in an absolutely _correct_ (and completely _expected_) return value of 32.

The exact same mistake (bug) exists in your second test as well: you are passing `int64_t` to the _very same **32-bit**_ `__builtin_clzl` function, resulting in the exact same _absolutely CORRECT_ and _completely EXPECTED_ result.

I suspect you mistakenly thought the `__builtin_clzl` function took a 64-bit wide argument as its input, but that is incorrect. The `__builtin_clzl` function takes `unsigned long` as its input, which is only _32 bits_ wide. It is the `__builtin_clzll` function, being defined as `unsigned long long`, which takes a _**64 bit**_ wide value as its input:

* https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
___
**`(*)`** Check the value of `ULONG_MAX` in your `<limits.h>` header to be sure. It should be 2\**32-1. `ULLONG_MAX` on the other hand (i.e. `unsigned long long` (i.e. _two_ longs)) should be 2\**64-1. If you were expecting `ULONG_MAX` to be 64 bits wide instead of only 32, then check to make sure you are using a 64-bit compiler and not a 32-bit compiler. The data model might be different between the two, and that might be where your problem lies. On Windows, a `long` is always 32 bits (LLP64 data model), whereas on most *Nix systems (e.g. Linux), a `long` is _supposed_ to be 64 bits (LP64 data model):

* https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

But again, which data mode the compiler actually uses _MIGHT_ be controlled by which architecture the compiler was designed for (i.e. what its target architecture is), which might very likely be different between the 32-bit version of gcc and the 64-bit version. But I'm no Linux expert either, so I could be wrong about that. I'm just speculating (i.e. guessing, i.e. making an educated guess) based on your test results.
