### ISSUE TITLE
DEADLOCK in Hercules when CTCEs are not connected

### ISSUE THREAD

**Issue by jeff-snyder** [SDL-Hercules-390/hyperion#378]
> The specific version of Hercules you are using (i.e. the output of the Hercules version command).
> The reported version string should look like this:
> <pre>
>  <b>HHC01413I</b> Hercules version 4.3.0.10296-SDL-<b>ga4db8213</b> (4.3.0.10296)
> </pre>
> The <b>ga4db8213</b> portion of the version string is the most important. If your version string only displays a generic "4.3.0.0" version string, then your Hercules was built wrong and you [**should rebuild it**](https://sdl-hercules-390.github.io/html/hercinst.html#install).

```
12:23:53 HHC01413I Hercules version 4.4.9999.0-SDL (4.4.9999.0)
12:23:53 HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
12:23:53 HHC01417I ** The SoftDevLabs version of Hercules **
12:23:53 HHC01415I Build date: Feb 22 2021 at 16:04:44
12:23:53 HHC01417I Built with: Microsoft Visual C (MSVC 192829337 0)
12:23:53 HHC01417I Build type: Windows MSVC AMD64 host architecture build
```

Sorry the version string doesn't match your requirements, but I don't know of another way to compile Hercules that would change it.  The only change I've made to the source since I downloaded it on 2021/02/22 is a one-line change in con1052c.c to comment out the "virtual bell" (i.e. Hercules message HHC00009) on line 494.

> Your _complete_ Hercules configuration file.

See attached zip files.

> Your _**complete**_ Hercules log file.   _(VERY important!)_

See attached zip files:

* [Crash1.zip](https://github.com/SDL-Hercules-390/hyperion/files/6135835/Crash1.zip)
* [Crash2.zip](https://github.com/SDL-Hercules-390/hyperion/files/6135837/Crash2.zip)

> What guest operating system and release level are you running under Hercules? VM? MVS? z/VM? z/OS? Other?

VM/ESA 2.4.0 including VTAM 4.2 with MPC and non-MPC CTC links defined.

> Your complete TCPIP.PROFILE dataset if your problem is networking related.

N/A

> Which host operating system platform are you using? (Windows? Linux? Mac?) Which version is it? Windows 7? CentOS 6.8? Is it 32-bit or 64-bit?

Windows 10 Professional 64-bit.

> Is the problem consistent and repeatable? What procedure can others use to try and re-create your problem?

While the problem has happened twice, I don't know of a way to predictably repeat it.  All I can suggest at this point is start Hercules and the guest OS with idle CTCEs and wait.

> Is there anything else you can think of that might be related to your problem? Do you have any unusual or related software installed on your host? Have you made any recent configuration changes to your host?

The only thing I'm doing differently right now is running the guest OS with no _ACTIVE_ CTCE links.  The links are defined and up in Hercules and VM/ESA, sitting there waiting for incoming connections.  For the last couple days, I have not run another OS that would connect to them; I've been using OSes with other link types.  So far, this crash has happened twice.  Dumps are available for both crashes.

**Comment by Fish-Git** [comment]
Hi Jeff!

> Sorry the version string doesn't match your requirements, but I don't know of another way to compile Hercules that would change it.

Please refer to the provided link!

* https://sdl-hercules-390.github.io/html/hercinst.html#install

Basically the procedure is to build Hercules from a _git CLONE_ instead of from the source code .zip file. Since it looks like you have Visual Studio 2019 installed, it should, I believe, come with git pre-installed. To confirm, simply enter the command "`git --version`" at any Command Prompt. If git is installed, it should report its version.

So with git already installed, simply follow the procedure as explained in the above mentioned build instructions web page. Basically you just build it the exact same way as you already did, except that you build it from the git clone directory and _not_ from the whatever directory you unzipped the .zip file into. You should _delete_ that directory and build from the git clone repository directory instead. That's the only difference, but it's an _important_ difference and will cause a proper version string to get constructed.

> See attached zip files:
> 
> * [Crash1.zip](https://github.com/SDL-Hercules-390/hyperion/files/6135835/Crash1.zip)
> * [Crash2.zip](https://github.com/SDL-Hercules-390/hyperion/files/6135837/Crash2.zip)

Thank you! I have examined both crash logs and am happy to report that the problem you are experiencing is very likely a known problem that was only very recently identified and fixed (just yesterday as a matter of fact!):

(Crash 1):
```
15:11:33 HHC90025S Thread CTCE 060C ConnectThread waiting for lock &dev->lock 0:060C held by thread CTCE 060C ConnectThread
```
(Crash 2):
```
15:03:24 HHC90025S Thread CTCE 060B ConnectThread waiting for lock &dev->lock 0:060B held by thread CTCE 060B ConnectThread
```

So all you need to do is create a git clone the current version of our source code repository and build that and you should be good to go.

I'll keep this issue open until you confirm that doing so does indeed fix your problem. If it doesn't, then there might still be a CTCE bug somewhere. But I suspect it's more than likely my "deadlock false alarm" bug that I just identified and fixed.

**Comment by jeff-snyder** [comment]
Hi Fish,

Thanks for the good news!

> Basically the procedure is to build Hercules from a git CLONE instead of from the source code .zip file. Since it looks like you have Visual Studio 2019 installed, it should, I believe, come with git pre-installed. To confirm, simply enter the command "git --version" at any Command Prompt. If git is installed, it should report its version.

FYI, I couldn't get the "git" command line to work, but VS has menu items for cloning from GitHub.  It may just be a path issue on my part, but this way worked, so I'm not going to futz with it.  :-)

Unfortunately, when I cloned the repository and put my local modification on, VS tried to update the repository.  Since I don't want any accidental updates to get applied, I went back to downloading a copy of the source code.

I have compiled the source code and it runs fine, however since I don't know how to reliably recreate the problem, I can't guarantee the issue is fixed.  I'll let this run overnight and see if anything happens; both times it crashed within 2.5 - 3.5 hours of me "idling" my last MPC link.

I'll update you tomorrow.

**Comment by Fish-Git** [comment]
> Unfortunately, when I cloned the repository and put my local modification on, VS tried to update the repository. Since I don't want any accidental updates to get applied, I went back to downloading a copy of the source code.

There is no possible way that you _can_ update our repository: you don't have R/W access to it. You only have R/O access. Only official Hercules developers are granted R/W access to our repository. So if Visual Studio _tried_ to update our repository, it wouldn't work.

Besides, when you say "VS tried to update the repository", what does that mean? What did VS try to do?

I apologize for my unfamiliarity with Visual Studio's integrated git support. I don't use recent versions of Visual Studio, so I'm not familiar with how Visual Studio deals with git. I myself use a much older and simpler version of Visual Studio (2008!) without git support, and have both git for Windows and TortoiseGit manually installed on my system instead.

(I personally like the idea of having git support integrated directly into the Windows user interface itself. That way I can do anything I need to do from anywhere within Window itself, and not have to deal with some weird specialized git support integrated only into Visual Studio. IMO it's better to have git support integrated directly into Windows itself than to only have it integrated into just one specific application. But then that's just me.)

Since you admit to making only only one tiny change however, I guess in your specific case, building from the downloadable source code .zip file is probably okay. I'd _prefer_ that people git clone the repository and build from that instead, but doing that proves to be too difficult, I guess I can live with building from the .zip file. **(*)**

___
**(*)** _The problem with that though is, we can't tell what fixes your version of Hercules has and which fixes it doesn't have. When you build Hercules from the git clone, the version string tells us **exactly** what fixes you have and which ones you don't. There's no guesswork involved. With just a "generic" version string like yours, we cannot know. We have to guess/presume, which is not good for problem analysis. I prefer dealing with certainties. I don't like guessing._

**Comment by wrljet** [comment]
You could use the command line build instead of VS IDE.

**Comment by Fish-Git** [comment]
> You could use the command line build instead of VS IDE.

Quite true, but I don't think that's his problem. His problem is with "git", The only git he has is the one that comes integrated with Visual Studio, and , if I'm understanding things, whenever he makes any change to any file that is a member of that repository that he cloned, Visual Studio wants to update the repository or something.

I don't fully understand the issue myself since, as I explained, I don't use any of the more modern versions of Visual Studio that come with git builtin, so I'm unable to see/understand what his problem is.

If he can manage to somehow git clone our repository, then yes, he could simply open a Command Prompt window at that directory (where Hercules was cloned to) and build that git clone of Hercules and everything would be great.

But he's having some weird Visual Studio + git issue that I don't fully understand and so has decided it was easier for him to simply work with the raw downloadable source code .zip file instead of trying to use Visual Studio to git clone our repository.

At least that's my current understanding.

But since he claims to have downloaded the latest and greatest .zip file version (doing so is easy enough to do) that _should_ thus have the fix he needs, it's not a real big deal. We just won't be able _verify_ that he has indeed built (and is indeed running) the correct version of Hercules with the fix he needs, that's all. We just have to trust his word.

(Not that he or anyone would lie about such a thing of course! Just that mistakes happen, and without an _exact_ git hash in the version string, we will be unable to know _for sure_ whether he's using the correct version of Herc or not.)

**Comment by wrljet** [comment]
FWIW, the Windows version of my Hercules-Helper builder thing is ready for alpha/beta testing.
(I have a couple people lined up, but haven't sent it out to them yet)

And it does provide an option to not (re)clone the repos, for situations just like this,
where you have local modifications.

It works with VS2017 or VS2019.  It will install VS and the required "workloads" if any are missing,
and will not remove any existing extra workloads that may already be present.  No dialog boxes
to click through.  Creates those stupid `.prop` files, sets the environment variables, etc. automatically.

Bill

**Comment by jeff-snyder** [comment]
Fish,

First, Hercules remained up over night with idle CTCs and no sign of a deadlock or other problem, so I think the original issue is resolved.

As for the git clone issue, what I experienced was the following:
1. I cloned the repository from within VS
2. I exited VS and updated con1052c.c with my local mod
3. When I reentered VS to build Hercules, it put up a window, prompting me for my name and email address to be added to a commit of my change to the repository.  I do not know if it would have actually performed (or tried to perform) the commit had I provided the information, I assumed it would and cancelled out of the window.

Bill,

If you've got a way for me to work with a clone so I can provide Fish the information he wants as well as have the ability to make minor changes to my local copy, I'm all ears.  I would think that my local changes would invalidate whatever version string was reported though, since Git / VS would have no way of knowing what my local mod(s) hit.

**Comment by Fish-Git** [comment]
@wrljet @jeff-snyder 

> FWIW, the Windows version of my Hercules-Helper builder thing is ready for alpha/beta testing.

That's fantastic, Bill! THANK YOU!

Jeff? Are you interested? It sounds like it's just the thing you need and would probably be a very good test of Bill's script too if you would give it a try!

**Comment by jeff-snyder** [comment]
Fish,

Yes, I have already volunteered in a previous message thread to be a tester for Bill when he's ready for that phase.  Sounds like that will be very soon.

**Comment by wrljet** [comment]
Jeff,

> 
> As for the git clone issue, what I experienced was the following:
> 
>     1. I cloned the repository from within VS
> 
>     2. I exited VS and updated con1052c.c with my local mod
> 
>     3. When I reentered VS to build Hercules, it put up a window, prompting me for my name and email address to be added to a commit of my change to the repository.  I do not know if it would have actually performed (or tried to perform) the commit had I provided the information, I assumed it would and cancelled out of the window.

That's just because you hadn't yet configured your name and email to Git.
It's not going to try to push anything up to the repo at that point.

It will continue you nag you to death, though, if you don't fill it in.

For Fish's benefit, I've (tried to anyway) attached a screen shot below, showing VS2019
with the Git feature installed, and a change to the code.

Top right, you can see where it's telling me I haven't configured Git.

Bill

![vs2019-with-git-changes](https://user-images.githubusercontent.com/3638124/111084560-6152e100-84e9-11eb-9c17-3e86aa95a811.jpg)

**Comment by jeff-snyder** [comment]
Thanks, Bill.  I wasn't sure it was going to try to update the repository, but I cancelled out just to be sure.  That's not my puddle to splash around in.

FYI, I did a little poking around and found a git.exe installed in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin but that directory was not added to my path.  Also, using VS's Tools -> Command Line -> Developer Command Prompt, the opened command window does not have GIT in the path either.  So, it looks like they give it to you but hide it away so you won't use it. :)

**Comment by wrljet** [comment]
If it was that easy to damage things accidentally, every hacker on the planet would have done so intentionally long ago. :-)

**Comment by Fish-Git** [comment]
> First, Hercules remained up over night with idle CTCs and no sign of a deadlock or other problem, so I think the original issue is resolved.

Fantastic! I'll go ahead and close this issue then.

Note that you can continue to post comments to closed GitHub issues, so you and Bill (and me too possibly) can continue to "talk" about (discuss) this silly unrelated Visual Studio issue in the hope of shedding some light on it. So my closing this issue shouldn't be a problem.

> I would think that my local changes would invalidate whatever version string was reported though, since Git / VS would have no way of knowing what my local mod(s) hit.

Nope. Not at all. The Hercules version string would still be valid and still be very helpful. Whenever local modifications are made (which would be the situation in your case), the string "-modified" is simply appended:

(unmodified as-is clone):
<pre>
        HHC01413I Hercules version 4.4.9999.10437-SDL-<b>gbe319de4</b> (4.4.9999.10437)
</pre>

(clone with local modifications):
<pre>
        HHC01413I Hercules version 4.4.9999.10437-SDL-gbe319de4<b>-modified</b> (4.4.9999.10437)
</pre>

That's the only difference there would be.

But the important thing is the "**gbe319de4**" string. _THAT_ is what we're ultimately interested in seeing, and as explained, that wouldn't change. It should always be accurate and reflect _exactly_ what specific version of Hercules you're using.

**Comment by jeff-snyder** [comment]
Well, at this point, I can't even get an unmodified git clone to build with the long version string.  I cloned the repository and then immediately built it with no modifications, and all I get is:

HHC01413I Hercules version 4.4.9999.0-SDL (4.4.9999.0)

You know, VS just started telling me my free trial is up in 7 days and I think I'll be glad to see it go.  I thought the Community edition was supposed to be free but if they want it back, they can have it.  Help says, "Microsoft Visual Studio Community 2019" and the license terms call that "Free Visual Studio", but I've still got a license status of "30 day trial (for evaluation purposes only)".

**Comment by Fish-Git** [comment]
> Well, at this point, I can't even get an unmodified git clone to build with the long version string. I cloned the repository and then immediately built it with no modifications, and all I get is:
> 
> HHC01413I Hercules version 4.4.9999.0-SDL (4.4.9999.0)

It's failing because, as you already discovered earlier, Microsoft doesn't add the directory where "git.exe" exists to your path. Hercules needs to be able to execute "git.exe" in order to retrieve the git hash of the cloned repository. (That's what the e.g. **gbe319de4** part of the extended version string is: it's the letter 'g' (which indicates the repository is a git repository) followed by the first 8 digits of the git hash of the repository.)

Try adding the directory where "git.exe" lives to your Windows PATH _before_ attempting to build Hercules:

```
   cd "C:\jeff\hercules"        (or wherever you git clone of Hercules is)
   set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
   git --version
   makefile.bat RETAIL-X64 makefile.msvc 64 -a
```

(The "git --version" command is just to verify that you updated your path correctly)

A much faster test to verify my above suspicion however, is to simply execute the "_dynamic_version" command _directly_ both before and after adding the "git.exe" directory to your path (which is the script that Hercules calls as part of its build process to obtain the values needed to construct its version string):

```
   cd "C:\jeff\hercules"        (or wherever you git clone of Hercules is)
   set DEBUG=1
   _dynamic_version.cmd
   set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
   git --version
   _dynamic_version.cmd
```

The first "_dynamic_version.cmd" should report a "generic" version string (because required "git.exe" program wasn't found anywhere), whereas the _second_ execution of "_dynamic_version.cmd", now that the directory where git.exe lives is in your path, should cause a proper _extended_ version string to get constructed.

You might want to do that first, and then if that works, then try actually _building_ Hercules (via the makefile.bat command).

THAT _should_ get you a version of Hercules with a proper version string.

> You know, VS just started telling me my free trial is up in 7 days and I think I'll be glad to see it go.

I feel your pain. `:(`



> I thought the Community edition was supposed to be free but if they want it back, they can have it. Help says, "Microsoft Visual Studio Community 2019" and the license terms call that "Free Visual Studio", but I've still got a license status of "30 day trial (for evaluation purposes only)".

(sigh) Typical fucking Microsoft...&nbsp; `:(`

**Comment by wrljet** [comment]
> 
> You know, VS just started telling me my free trial is up in 7 days and I think I'll be glad to see it go. I thought the Community edition was supposed to be free but if they want it back, they can have it. Help says, "Microsoft Visual Studio Community 2019" and the license terms call that "Free Visual Studio", but I've still got a license status of "30 day trial (for evaluation purposes only)".

Did you "sign in" to a MSFT account inside VS?
That will get you off the trial.

Bill

**Comment by jeff-snyder** [comment]
Fish,

Thanks, that was the missing bit.  Once I added git to my path, the version string is correct both before
HHC01413I Hercules version 4.4.9999.10438-SDL-g51915e1a (4.4.9999.10438)
and after 
HHC01413I Hercules version 4.4.9999.10438-SDL-g51915e1a-modified (4.4.9999.10438)
my local modification.

So far I've only done the batch makefile, because this is not a good time for me to logoff and back on.  Once I do that, I expect this will work in the VS GUI as well.

Bill,

Thanks for the heads up, I hadn't interpreted "unlock the IDE" to mean "enable the product license for a free product."  There is nothing in their license terms that require you to maintain a Microsoft account, though they do provide the standard "we collect data about you" disclaimers.  At this point, I think I'll wait it out and see if the git command and batch compiles still work after the license expires.  If not, then I may sign in and activate the product.  I don't particularly care for their GUI anyway.

Thanks for all your help guys,
Jeff
