### ISSUE TITLE
When working with mvs/hercules, the terminal suddenly stands-by and it spits me out of the SPF...

### ISSUE THREAD

**Issue by carsantello** [SDL-Hercules-390/hyperion#388]
when trying reconnecting, the console says as follows:
```
HHC01018I 0:00C0 COMM: client 127.0.0.1 devtype 3270: connected
00.15.06 TSU   30  IKT108I HERC01   RECEIVE ERROR,RPLRTNCD=04,RPLFDB2=03,SENSE=00000200,WAITING FOR RECONNECT CUU0C0
00.15.11           LGN001I TSO logon in progress at VTAM terminal CUU0C0 
```

I really appreciate the support to fix this, and thank you so much in advance!

![IKT108I](https://user-images.githubusercontent.com/32203681/113980045-a8dc3c80-980b-11eb-9e17-dfa466505f3f.png)

**Comment by Fish-Git** [comment]
This does _not_ appear to be a Hercules problem.

This appears to be a problem with the guest operating system you are running under Hercules. &nbsp;_(TK4-?)_

Please ask for help with your problem in an appropriate Hercules support forum _first._ **`[1]`**

If and _only _ if the people there then believe your problem is indeed due to an actual Hercules bug, then we will be happy to look into it for you. But based on the complete _lack_ of information **`[2]`** you have provided, this honestly does _not_ appear to be a problem with Hercules. Sorry!

I am closing this issue as "Invalid" at this time.

Please resubmit with more information but only  _AFTER_ you have first discussed your "problem" with the people in the appropriate Hercules Support Forum to confirm beforehand that this is indeed a Hercules bug. **`[3]`**

Thank you.

&nbsp;

______
**`[1]`** For a comprehensive list of our many Support Forums, please refer to our "[**Technical Support**](https://sdl-hercules-390.github.io/html/hercsupp.html)" web page. If your problem is with "TK4-" for example, then you should probably ask your question in either the "[H390-MVS](https://groups.io/g/H390-MVS)" and/or the "[Turnkey-MVS](https://groups.io/g/Turnkey-MVS)" group.

**`[2]`** _Did you bother to read the "[**Submitting problem reports**](https://github.com/SDL-Hercules-390/hyperion/issues/373)" document before submitting this "bug" report? I'm guessing you didn't since you failed to provided the minimum amount of required information._

**`[3]`** _(see footnote <span>#</span>1 above)_
