### ISSUE TITLE
Please provide an alternate means to signal EOF to the card reader from within the data stream

### ISSUE THREAD

**Issue by PoC-dev** [SDL-Hercules-390/hyperion#409]
As discussed in the [Turnkey-MVS group](https://groups.io/g/turnkey-mvs), it would be beneficial to have some in-band "data" signaling the card reader that processing may start.

Optionally, the card reader might decide to keep the fd open for more jobs to arrive on the same fd. This is most interesting when the fd is a (type INET) socket.

Discussion is required about the data sequence to be used in hindsight about the different OS's being run in Hercules.

For further details, see the [_VERY LONG_ discussion thread](https://groups.io/g/turnkey-mvs/topic/84634999#1318) with the subject `"nc -w1 127.0.0.1 3505 <%f" #TK4-` starting on 2021-08-03.

**Comment by Fish-Git** [comment]
> As discussed in the [Turnkey-MVS group](https://groups.io/g/turnkey-mvs), it would be beneficial to have some in-band "data" signaling the card reader that processing may start.

It is up to the guest operating system that is reading from the card reader -- _not Hercules_ --  to decide when "processing may start".

When the guest issues a read from the card reader, Hercules will satisfy that read with whatever data it already has in its buffer. If/when the buffer is empty, Hercules reads more data into its buffer from the card reader's defined input file, or in the case of a socket reader, from the currently connected client.

If, in the case of a socket reader, there is no one currently connected, you will get an "intervention required" I/O error. If the socket client is still connected however, then it issues a read from the socket to read the next chunk of data from the connected client. This read is a blocking read. It will not complete until either it receives some data from the connected client, end-of-file is signaled, or an error occurs.

When using certain buggy netcats, after transmitting the data it was told to transmit (i.e. upon reaching EOF on the file it was asked to read and send to the server), it fails to close the connection it has with the server. This causes the Hercules's card reader's read to "hang", waiting for more data from netcat (which, for broken implementations of netcat, will never occur). Thus the problem.

Hercules documentation even makes this clear on its "[Socket Reader](https://sdl-hercules-390.github.io/html/hercrdr.html)" web page:

> _**Using the netcat program**_
>
> _... It is important to use the -N option to prevent the Hercules card reader from hanging due to netcat failing to close its connection. The -N option tells netcat to close the socket connection once EOF is reached on stdin (i.e. once the entire file has been sent to Hercules)._
> 
> _If your version of netcat does not support the -N option, then, as an alternative, the -q option should be used. If your version of netcat does not support either option, then you should probably not be using netcat to submit jobs to Hercules._

Using some type of "in-band data pattern" to indicate end-of-file -- other than EOF itself (i.e. ASCII X'04' = EOT (END-OF-TRANSMISSION) or, on Windows, X'1A' = Ctrl+D) -- will not correct the problem. The problem is in _netcat_, not Hercules. You need to replace your buggy netcat implementation with an implementation without said bug.

This is a known issue that has been around for many years, and one which most implementations have since corrected by adding additional options to netcat to properly close the connection once the data (file) has been sent. See below for some examples:
___
**[redhat/ubuntu man page for netcat](http://manpages.ubuntu.com/manpages/jammy/en/man1/ncat.1.html)**:

> ```
> --send-only            Only send data, ignoring received; quit on EOF
> ```

> ```
> --send-only (Only send data)
>     If this option is passed, then Ncat will only send data and will ignore anything
>     received. This option also causes Ncat to close the network connection and terminate
>     after EOF is received on standard input.
> ```

&nbsp;
___
"**[How to send only data (ignore receiving) with nc command (equivalent to --send-only option on redhat)?](https://askubuntu.com/questions/970746/how-to-send-only-data-ignore-receiving-with-nc-command-equivalent-to-send-o)**":

> As @muru said in the comment, the ncat software from the nmap has the option that you are searching for (`--send-only`).
> 
> Anyway, `echo "TEST" | nc localhost 1234 > /dev/null` will have the same effect, since you have no way to tell the remote machine you don't want it's data.

&nbsp;
____
"**[Linux – Sending text file contents to server using netcat](https://itectec.com/superuser/linux-sending-text-file-contents-to-server-using-netcat/)**":

> If you are using the GNU version of netcat then you can use the -c flag to close the connection on EOF.
> ```
>   -c, --close close connection on EOF from stdin
> ```
> If you are using the original version of the tool then you can use the -q flag.
> ```
>   -q secs quit after EOF on stdin and delay of secs
> ```
> An example for the original version is:
> ```
>   cat file.txt | nc -u -q 0 127.0.0.1 5144
> ```
> I have add "-q 0" to your original command. This closes the connection after the file has been sent.
___

What this all means as far as this GitHub Hercules enhancement request goes is this: After careful and serious consideration (as well as after reviewing Hercules code), I am going to have to reject your enhancement request. IMHO Hercules is fine as it is, and does not need to be fixed _**nor enhanced**_ to accommodate known buggy implementations of netcat.

Of course this is only _MY_ personal opinion on the matter. Some other (or several other) Hercules developers may feel differently, and might be willing to implement your desired change.

But it won't be me, that's for sure.

Sorry! &nbsp; `:(`

**Comment by PoC-dev** [comment]
> When the guest issues a read from the card reader, Hercules will satisfy that read with whatever data it already has in its buffer. If/when the buffer is empty, Hercules reads more data into its buffer from the card reader's defined input file, or in the case of a socket reader, from the currently connected client.

We've been through this discussion before. My request was twofold. This is from my memory, without re-reading through the whole discussion for a refresh. At last, you've already rejected the change.

- As far as I remember, a physical card reader has a button you press for it to start processing. My request was to have a "button" in the Hercules sense, to start reading.

- We have talked about ways how to "work around" the issue of stock netcat not closing the connection on EOF by default. I've proposed to Hercules should close the connection by itself when receiving a EOF character. You argued that the client must always close the connection, but we clearly could prove that this isn't the normal way (in Linux, at least). Examples were telnet and ssh, where you quit the shell (e. g. with `exit`, `logout`, or even an EOF character, and the server itself closes the connection to the client.

At this point you started to understand my intentions and asked to create an issue on Github, which I did. Sadly, some facts might have slipped because of Months have passed.

Btw, we agreed upon netcat not closing the local socket to the peer on a local EOF by default most likely not being a bug, but an intentional behavior. Since we never asked the original author, we don't know the intention(s), and they are also not related to Hercules.

> Sorry!   `:(`

I have no right to tell you what do to and what not. Thus, no need to be sorry. :-)

:wq! PoC

**Comment by Fish-Git** [comment]
> * As far as I remember, a physical card reader has a button you press for it to start processing. My request was to have a "button" in the Hercules sense, to start reading.

That's what the socket connection is. It's the start button. Whenever a client -- whether that client is netcat or some other program (such as my HercRdr utility on Windows -- connects to a Hercules socket reader, an unsolicited interrupt is presented to the guest to notify it "the card reader has something to say to you!" This is the same as pressing the Start button on a real card reader. The guest then issues a read (ccw opcode X'02') for the card reader device to start reading cards.

Once the guest starts reading the cards, it is up to the guest to decide _when_ to begin "processing" the cards it is reading (where by "processing" I mean "start running the job(s) the user is submitting", since the deck of cards loaded into a read can consist of several "jobs").

> * I've proposed to Hercules should close the connection by itself when receiving a EOF character.

We can absolutely do that. As far as I know that is no problem.

What _**is**_ the problem however, is when the client (netcat in this particular case, but the same thing can certainly happen with _any_ client -- even with my HercRdr utility if it contained such a bug -- is when:

1. The "EOF character" is never sent.
2. The client simply stops sending data.

When THAT happens, the connection becomes "hung". The connection still exists (it hasn't been closed by netcat) and Hercules gets "stuck" waiting for more data to arrive. It has issued a "read" on the socket, but the read is never satisfied. It never completes.

So how is Hercules supposed to magically "know" that _**it** (instead of the client) should close the connection?

Your answer to this is to use some type of special "data pattern" as a signal to Hercules's reader logic that, when received, triggers _Hercules_ to close the connection (instead of the client (netcat) which is the way things normally work today).

But what should that "signal" (data pattern) be, Patrik? I say it should be the "EOF character" (i.e. the EOT = END-OF-TRANSMISSION character, or, on Windows, the X'1A' character). You however, seem to feel it should be something else? And _THAT_ is what I am objecting to.

> * You argued that the client must always close the connection, but we clearly could prove that this isn't the normal way (in Linux, at least). Examples were telnet and ssh, where you quit the shell (e. g. with `exit`, `logout`, or even an EOF character, and the server itself closes the connection to the client.

As explained, having Hercules close the connection is not the problem.

Somehow letting Hercules _KNOW_ that it should close the connection _**IS**_ the problem.

There needs to be some way of "notifying" Hercules that "no more data will be forthcoming", so that it can then close the connection. But netcat is never sending that notification!

There are two ways of notifying Hercules that "no more data will be arriving" so that it can know to close the connection:

1. The closing of the connection by the client.
2. Receipt of "EOF" (i.e. either EOT or X'1A')

But in the netcat case, _neither_ is occurring. Hence the problem.


> At this point you started to understand my intentions and asked to create an issue on Github, which I did. Sadly, some facts might have slipped because of Months have passed.

I don't think so. I just had more time to think about it is all. &nbsp; `;-)`

Initially, at the time we were discussing the matter, yes, I was thinking the receipt of some type of special "data pattern" from the client (such as the 5-character string "$EOF$" or something similar) could maybe be used to trigger Hercules to close the connection, but now, after having thought the matter through, I have decided to reject that idea.

What if the file you submitted to Hercules via netcat was missing that special data pattern? We'd end up right back in the same place where we are today! And besides that, the idea of using a special data pattern to signal EOF is dumb in the first place IMHO. (Yes I'm calling Windows using the X'1A' character to signal EOF on a text file DUMB!)

> Btw, we agreed upon netcat not closing the local socket to the peer on a local EOF by default most likely not being a bug, but an intentional behavior.

I still agree. That still doesn't change the fact that it purposely doing so wrecks havoc with Hercules's socket reader logic. It also doesn't change the fact that others have recognized that such behavior by netcat is highly undesirable in most situations either, thus leading to the introduction of new options to prevent such undesirable behavior.

> I have no right to tell you what do to and what not. Thus, no need to be sorry. `:-)`

Thanks.

If you can manage to convince someone else (some other Hercules user or developer) to implement your proposed change, I, along with the rest of the Hercules team, will certainly _reconsider_ implementing it. (i.e. you are free to appeal your case to a higher court so to speak.)

But given the facts of the case I certainly won't be holding my breath waiting for some higher court to overturn my decision.&nbsp;`;-)`

**Comment by PoC-dev** [comment]
> That's what the socket connection is. It's the start button. Whenever a client -- whether that client is netcat or some other program (such as my HercRdr utility on Windows) -- connects to a Hercules socket reader, an unsolicited interrupt is presented to the guest to notify it "the card reader has something to say to you!" This is the same as pressing the Start button on a real card reader. The guest then issues a read (ccw opcode X'02') for the card reader device to start reading cards.

Aha! Thanks for elaborating.

> > * I've proposed that Hercules should close the connection by itself when receiving a EOF character.
> 
> We can absolutely do that. As far as I know that is no problem.
> 
> What _**is**_ the problem however, is when the client (netcat in this particular case, but the same thing can certainly happen with _any_ client -- even with my HercRdr utility if it contained such a bug):
> 
> 1. Never sends the "EOF character".
> 2. Simply stops sending data.

How is this different considering how Hercules and Netcat (with default settings) don't come along well, today? :-) It *might* be possible that Netcat even (transparently) handles an EOF character, and sends it through the TCP pipe, instead of acting on it.

> When THAT happens, the connection becomes "hung".

Same as now, apparently.

> So how is Hercules supposed to magically "know" that _**it**_ (instead of the client) should close the connection?

It's just a secondary way. If Hercules receives an EOF char on the reader, it shall close the connection itself. No replacement of functionality, but an extension. Any client should be still perfectly allowed to close the connection themselves.

> Your answer to this is to use some type of special "data pattern" as a signal to Hercules's reader logic that, when received, triggers _Hercules_ to close the connection (instead of the client (netcat) which is the way things normally work today).

I honestly can't recall. And for reasons already described, I think it's moot to invest the time to reiterate through the discussion.

> Somehow letting Hercules _KNOW_ that it should close the connection _**IS**_ the problem.

Understood.

I guess this is a good documentation of if and why for your rejection, which I of course accept. Thanks for taking time to elaborate.

:wq! PoC
