### ISSUE TITLE
Problems with compile on AIX 7.2.5.2

### ISSUE THREAD

**Issue by hurgler** [SDL-Hercules-390/hyperion#414]
Hi,

I've been trying to compile SDL Hyperion on AIX for a very long time now, but I have never been able to successfully do so. Yesterday, after a long break, I gave it another try.

I downloaded the source from https://github.com/sdl-hercules-390/hyperion/archive/master.zip, so the source code should be relatively recent.

My environment is as follows:

What | Value
------------ | -------------
**Machine:** | pSeries S822
**AIX version:** | 7.2.5.2
**Configure options:** | `./configure --disable-ipv6` 

&nbsp;
I have also tried `./configure --disable-ipv6 --disable-cckd-bzip2 --disable-het-bzip2` too, but unfortunately there was no change in the errors.

I used recent Freeware Tools from AIX Toolbox from IBM. See further below for RPMs I have installed.

I tried to compile it either with the xlc compiler or with the gcc. Also with the AIX make and with gmake. I was not sure which one to prefer. But it all lead to errors.

Maybe I need to set the `LD_LIBRARY_PATH` or the `LIBPATH` to something like `/opt/freeware/lib`? Or maybe I should set it to something like?:

      LIBPATH=/opt/freeware/lib64:/opt/freeware/lib:/lib:/usr/lib:/usr/lib64

But then afterwards, neither `yum update` nor `yum install` works until I unset  `LIBPATH` back to its original value again.

This is the error I get when trying to build Hercules:

<pre>
<b># gmake</b>

gmake  all-recursive
gmake[1]: Entering directory '/export/software/OpenSource/hyperion-master'
Making all in m4
gmake[2]: Entering directory '/export/software/OpenSource/hyperion-master/m4'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/hyperion-master/m4'
Making all in util
gmake[2]: Entering directory '/export/software/OpenSource/hyperion-master/util'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/hyperion-master/util'
Making all in html
gmake[2]: Entering directory '/export/software/OpenSource/hyperion-master/html'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/hyperion-master/html'
Making all in man
gmake[2]: Entering directory '/export/software/OpenSource/hyperion-master/man'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/hyperion-master/man'
Making all in .
gmake[2]: Entering directory '/export/software/OpenSource/hyperion-master'
  CC       cckdcdsk.o
In file included from hercules.h:80,
                 from cckdcdsk.c:14:
clock.h:638:26: error: conflicting types for 'thread_cputime'
 extern              TOD  thread_cputime(const REGS*);       /* Thread real CPU used (TOD)*/
                          ^~~~~~~~~~~~~~
In file included from /usr/include/sys/ptrace.h:28,
                 from /usr/include/sys/proc.h:43,
                 from /usr/include/sys/pri.h:43,
                 from /usr/include/sys/sched.h:38,
                 from /usr/include/sched.h:51,
                 from hstdinc.h:130,
                 from cckdcdsk.c:13:
/usr/include/sys/thread.h:1197:5: note: previous declaration of 'thread_cputime' was here
 int thread_cputime(tid_t, thread_cputime_t *);
     ^~~~~~~~~~~~~~
In file included from hercules.h:102,
                 from cckdcdsk.c:14:
hexterns.h:437:102: warning: 'struct option' declared inside parameter list will not be visible outside of this definition or declaration
 GOP_DLL_IMPORT int   getopt_long ( int nargc, char * const *nargv, const char *options, const struct option *long_options, int *idx );
                                                                                                      ^~~~~~
gmake[2]: *** [Makefile:2504: cckdcdsk.o] Error 1
gmake[2]: Leaving directory '/export/software/OpenSource/hyperion-master'
gmake[1]: *** [Makefile:2568: all-recursive] Error 1
gmake[1]: Leaving directory '/export/software/OpenSource/hyperion-master'
gmake: *** [Makefile:1903: all] Error 2
</pre>

&nbsp;
I really hope there is someone out there who can guide me or who has already successfully compiled Hercules on AIX.

Thank you all.

___
The RPMs I have installed are:
<pre>
<b>bash-4.3# rpm -qa | sort</b>

AIX-rpm-7.2.5.1-8.ppc
autoconf-2.71-1.noarch
automake-1.16.2-1.noarch
bash-5.1.4-2.ppc
bzip2-1.0.8-2.ppc
bzip2-devel-1.0.8-2.ppc
ca-certificates-2020.06.01-2.ppc
cmake-3.16.0-2.ppc
cmake-data-3.16.0-2.ppc
coreutils-8.32-1.ppc
curl-7.76.1-1.ppc
cyrus-sasl-2.1.26-5.ppc
db-5.3.28-1.ppc
expat-2.2.9-2.ppc
flex-2.6.4-1.ppc
gawk-5.0.1-1.ppc
gcc-8-1.ppc
gcc-cpp-8-1.ppc
gcc8-8.3.0-5.ppc
gcc8-cpp-8.3.0-5.ppc
gdb-8.1.1-3.ppc
gdbm-1.19-1.ppc
gettext-0.20.2-1.ppc
glib2-2.56.1-3.ppc
gmp-6.1.2-1.ppc
grep-3.4-1.ppc
info-6.7-1.ppc
krb5-libs-1.18.3-1.ppc
less-557-1.ppc
libffi-3.2.1-3.ppc
libgcc-8-1.ppc
libgcc8-8.3.0-5.ppc
libgomp-8-1.ppc
libgomp8-8.3.0-5.ppc
libiconv-1.16-1.ppc
libmpc-1.1.0-1.ppc
libnghttp2-1.41.0-1.ppc
libssh2-1.9.0-1.ppc
libstdc++-8-1.ppc
libstdc++8-8.3.0-5.ppc
libtasn1-4.16.0-1.ppc
libtextstyle-0.20.2-1.ppc
libunistring-0.9.10-1.ppc
libxml2-2.9.10-1.ppc
logrotate-3.18.0-1.ppc
m4-1.4.18-1.ppc
make-4.3-1.ppc
mpfr-4.0.2-2.ppc
ncurses-6.2-2.ppc
openldap-2.4.58-1.ppc
p11-kit-0.23.22-1.ppc
p11-kit-tools-0.23.22-1.ppc
pcre-8.44-2.ppc
perl-5.30.3-2.ppc
popt-1.18-1.ppc
pysqlite-2.8.3-2.ppc
python-2.7.18-3.ppc
python-devel-2.7.18-3.ppc
python-iniparse-0.4-1.noarch
python-pycurl-7.43.0-1.ppc
python-tools-2.7.18-3.ppc
python-urlgrabber-3.10.1-1.noarch
readline-8.1-1.ppc
screen-4.7.0-1.ppc
sed-4.8-1.ppc
sqlite-3.35.5-1.ppc
unzip-6.0-3.ppc
wget-1.21.1-1.ppc
xz-libs-5.2.5-1.ppc
yum-3.4.3-8.noarch
yum-metadata-parser-1.1.4-2.ppc
zlib-1.2.11-2.ppc
</pre>

**Comment by joemonk64** [comment]
This seems to be a known issue...

https://community.ibm.com/community/user/power/communities/community-home/digestviewer/viewthread?GroupId=6211&MessageKey=7af2f62f-f23f-40cb-aa87-048625dad735&CommunityKey=10c1d831-47ee-4d92-a138-b03f7896f7c9&tab=digestviewer

**Comment by marXtevens** [comment]
Do see the link Joe posted. Seems there is a solution, if you get the correct gcc build.

I'm not usually one to be a downer, but if you are an IBMer, or contractor, and Corp finds out, you'll get swatted. We desperately wanted to provide this (Hercules) to our team, to support various clients for health checking, and it got to the point we were told if we were caught with it on our systems, laptop or server, during a scan, we would be walked out the door. If it is your/your company's system, you'll not get any help from IBM.

Again, sorry to be a downer, but I don't want you getting in trouble, either.

**Comment by racingmars** [comment]
After getting Hyperion building on Solaris, I moved on to attack AIX. You will run into many hurdles, but in the end I got a build that should mostly work (I just kinda hacked around some LCS code and don't know that code the depends on /dev/random will work right... but neither affects my goal of running MVS 3.8).

Other priorities came up before I was able to put together notes and a write-up like I did for the Solaris support. But... here's what I can remember looking at my notes and my source diffs:

1. The first problem you're seeing: thread_cputime and thread_cputime_us are system functions in AIX, so Hercules' use of the names conflict with the AIX functions. I just renamed them throughout the Hercules code to avoid the conflict.
2. AIX does not allow $ in symbol names, apparently. GCC on AIX enforces this restriction. This affects names in the command tables... for example, $runtest_cmd_desc, $runtest_cmd_help, etc defined in cmdtab.h. There are several examples of these. I had to rename all instances of names with $ in them to avoid the compiler errors about illegal symbol names.
3. The configure script doesn't detect that it's a 64-bit system (similar problem as sparcv9). Bill's suggested solution on the Solaris case of manually specifying the target and including "64" in the architecture name should work here too, but I just hacked the generated configure script. (see #406)
4. I disabled some code in ctc_lcs.c (it was guarded by ifdefs on SIOCGIFHWADDR, but apparently that's defined on AIX but the data structures that Hercules then uses aren't the same).
5. Some other hacks in ctc_ptp.c.
6. In hcrypto.h, the code didn't have a case to select a random source for AIX. I made it use /dev/random, but I'm not sure if the ioctl values in the code are applicable to AIX. 
7. ltdl.c needs <errno.h> included, but that #include is guarded by `#if HAVE_ERRNO_H`. Despite errno.h being present on the system, it doesn't look like the configure script is actually setting HAVE_ERRNO_H.
8. Some headers from AIX that were being pulled in appear to #define values for ip_v, ip_hl, ip_tos, ip_len, th_off, th_x2, th_flags, th_win. Hercules uses these names in data structures, but they were being replaced with who-knows-what by the preprocessor resulting in invalid code. This seems really strange to me, but I didn't want to try to understand what was happening, so I just renamed these structure member names throughout the Hercules code to avoid conflicts with however AIX is defining them.
9. As with Solaris, the name "regex" is present in older versions of POSIX, and Hercules' use of the name in panel.c conflicts with it. Renamed in the Hercules code to regexp.

I have attached a patch against Hyperion commit b8a26cfd. [aixbuild-b8a26cfd.patch.gz](https://github.com/SDL-Hercules-390/hyperion/files/7029482/aixbuild-b8a26cfd.patch.gz) This will cause conflicts if you try to apply against the current HEAD since a couple of these changes have already been applied as a result of the Solaris changes. If you apply this patch against b8a26cfd, you should have the version of the code with my random hacks to get it to compile successfully with GCC on AIX.(I'm running AIX 7.2 on a Power S822 as well!)

*RPM packages*: you will need to install libtool-ltdl-devel (if that doesn't pull in libtool and libtool-ltdl, maybe grab them too for safety). Make sure you do NOT have GNU bintools installed... you must use the native AIX ld, nm, ar, etc. I don't see it in your list, so you should be good. 

**ANOTHER IMPORTANT NOTE**: the scripts that build the extpkgs do not correctly build 64-bit versions of the libraries on AIX. They build libraries that have "64" in the name, but if you examine the archive files that get produced, they actually contain 32-bit libraries. These, of course, don't link successfully against Hercules during the build. You need the flag `-maix64` when building with GCC, and you need `-X64` when calling ar and ranlib. I could change the cflags.txt files in the individual extpkgs projects for the gcc 64-bit flag, but I could not for the life of me figure out how to get cmake to correctly call ar and ranlib with `-X64` so I had to manually change some files after cmake generated the build scripts... for example, in SoftFloat64.Release/CMakeFiles/SoftFloat64.dir/link.txt I added the `-X64` flag as needed. Needless to say, building the four extpackages was a pretty manual process to be able to make the change after running CMake but before running the build.

**Comment by racingmars** [comment]
If you don't want to try to fight with building the extpkgs to get the 64-bit versions to build correctly, here are mine: https://mattwilson.org/filedrop/aix-ppc-extpkgs.tar.gz (GitHub wouldn't allow the file as an attachment for some reason....)

**Comment by Fish-Git** [comment]
> (GitHub wouldn't allow the file as an attachment for some reason....)

I'm sure it would if you'd give it a .zip file extension instead of .gz:

* https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by hurgler** [comment]
Hi,
first I tried the solution of Joe. I installed all the relevant rpms for gcc10-10.3.0-4 from bullfrog:

gmp-6.2.1-1.aix7.1.ppc.rpm
libgcc8-8.5.0-2.aix7.2.ppc.rpm
libstdc++8-8.5.0-2.aix7.2.ppc.rpm
ncurses-6.2-2.aix6.1.ppc.rpm
gcc10-10.3.0-4.aix7.2.ppc.rpm
info-6.8-1.aix7.1.ppc.rpm
libiconv-1.16-5.aix6.1.ppc.rpm
libtextstyle-0.21-1.aix7.1.ppc.rpm
sed-4.8-1.aix6.1.ppc.rpm
gcc10-cpp-10.3.0-4.aix7.2.ppc.rpm
libgcc-8-4.aix7.2.ppc.rpm
libmpc-1.2.1-1.aix6.1.ppc.rpm
libunistring-0.9.10-4.aix7.1.ppc.rpm
zlib-1.2.11-5.aix6.1.ppc.rpm
gettext-0.21-1.aix7.1.ppc.rpm
libgcc10-10.3.0-4.aix7.2.ppc.rpm
libstdc++-8-4.aix7.2.ppc.rpm
mpfr-4.1.0-1.aix6.1.ppc.rpm

but when I do the configure (again with  --disable-ipv6) it also leads to tons of errors...
...
"hstdinc.h", line 18.3: 1506-191 (E) The character # is not a valid C source character.
"hstdinc.h", line 18.1: 1506-046 (S) Syntax error.
"hstdinc.h", line 18.4: 1506-166 (S) Definition of function define requires parentheses.
"hstdinc.h", line 111.33: 1506-234 (W) Expecting a new-line character on #include directive.
"/usr/include/stdio.h", line 166.3: 1506-273 (E) Missing type in declaration of FILE.
"/usr/include/stdio.h", line 184.8: 1506-166 (S) Definition of function FILE requires parentheses.
"/usr/include/stdio.h", line 184.17: 1506-276 (S) Syntax error: possible missing '{'?
"/usr/include/sys/inttypes.h", line 59.9: 1506-045 (S) Undeclared identifier intmax_t.
"/usr/include/sys/inttypes.h", line 61.3: 1506-273 (E) Missing type in declaration of imaxdiv_t.
"/usr/include/sys/inttypes.h", line 79.8: 1506-166 (S) Definition of function intmax_t requires parentheses.
"/usr/include/sys/inttypes.h", line 79.17: 1506-276 (S) Syntax error: possible missing '{'?
"/usr/include/sys/types.h", line 345.3: 1506-273 (E) Missing type in declaration of sigset_t.
"/usr/include/sys/types.h", line 359.9: 1506-046 (S) Syntax error.
"/usr/include/sys/types.h", line 394.9: 1506-046 (S) Syntax error.
...
and so on and so on... hundreds of errors
I will try the solution of racingmars... Hope I will understand which things to change. But after all I am a bit confused if I am the first one trying to get it run in AIX... In Linux it compiles smooth... is it something about my setting? Or is it a problem with the configure not working like it is supposed to...

The warning or notice of marXtevens I did not understand well. Probably because of English is not my native language. What do you want to say with your lines? That IBM wont support my compile? Yes I think so but I wouldn't have opened an case because of that. Or do you mean that I am not allowed to compile the emulator? Why not? And why shouldn't I do it on AIX but on Linux? Sorry but your lines confused me a bit...

Thank you all so long... I am an holidays with my little children so probably the test of racingmars will take some days. I will report...

**Comment by racingmars** [comment]
Hi @hurgler,

Those errors looks like they're from the xlc compiler; you'll want to use GCC along with my patches (in addition to the --disable-ipv6 configure flag, you'll also need `--enable-extpkgs=/path/to/extpkgs` pointing to the external packages that I linked to).

marXtevens' warning was that if you are an IBM employee or contractor, they apparently have a strict policy about not allowing use of Hercules. If you don't work for IBM and/or you're not doing this on an IBM-owned system, the warning does not apply to you

**Comment by hurgler** [comment]
Hi racingmars,

oh yeah you are right. CC was still directing to xlc... Thanks for the hint.
Thank you for explaining the warning. No I don't work for IBM. It is my own machine. And I do it just for fun...
Thanks I will go on trying...

**Comment by hurgler** [comment]
Hi racingmars...

aehem... I am just a sysadmin not dealing very much with developing... What have I to do exactly to get the  b8a26cf version from github (to use your patches)? How do I download the correlating entire version?

Thanks and sorry...

**Comment by hurgler** [comment]
Ok. Forget about b8a26cf - I downloaded it. Will now try to patch it and follow your instructions 1-9...

**Comment by racingmars** [comment]
> Ok. Forget about [b8a26cf](https://github.com/SDL-Hercules-390/hyperion/commit/b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed) - I downloaded it. Will now try to patch it and follow your instructions 1-9...

My patch takes care of the changes in 1-9 for you. *Theoretically* if you apply the patch and `./configure --disable-ipv6 ----enable-extpkgs=/path/to/extpkgs --prefix=/opt/sdl-hyperion`, then `make`, it *should* build. Emphasis on *theoretically* :-)

**Comment by hurgler** [comment]
Hmmm hi racingmars.... No sorry it does not work like this (but maybe because of my lack of knowledge in developing)...

I did after applying successfully your patches and putting your extpkgs to ./extpkgs/lib/ppc:
```
./configure --disable-ipv6 --enable-extpkgs=./extpkgs/lib/ppc/
gmake
```
but I still ran in problems with Header Libraries being in subfolders where they weren't searched. Like e.g. the following:
```
version.c:836:10: fatal error: crypto_version.h: No such file or directory
  836 | #include "crypto_version.h"
      |          ^~~~~~~~~~~~~~~~~~
```
I linked all the problematic Headerfiles to the main folder of Hyperion and so the compile started at least. But after all it terminated with a problem not related to the header files...
```
bash-5.1# gmake
gmake  all-recursive
gmake[1]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed'
Making all in m4
gmake[2]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/m4'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/m4'
Making all in util
gmake[2]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/util'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/util'
Making all in html
gmake[2]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/html'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/html'
Making all in man
gmake[2]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/man'
gmake[2]: Nothing to be done for 'all'.
gmake[2]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed/man'
Making all in .
gmake[2]: Entering directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed'
  CC       version.lo
In file included from hercules.h:103,
                 from version.c:19:
hexterns.h:437:102: warning: 'struct option' declared inside parameter list will not be visible outside of this definition or declaration
  437 | GOP_DLL_IMPORT int   getopt_long ( int nargc, char * const *nargv, const char *options, const struct option *long_options, int *idx );
      |                                                                                                      ^~~~~~
  CC       ltdl.lo
ltdl.c: In function 'rpl_memcpy':
ltdl.c:410:11: warning: dereferencing 'void *' pointer
  410 |       dest[i] = src[i];
      |           ^
ltdl.c:410:20: warning: dereferencing 'void *' pointer
  410 |       dest[i] = src[i];
      |                    ^
ltdl.c:410:15: error: invalid use of void expression
  410 |       dest[i] = src[i];
      |               ^
ltdl.c: In function 'rpl_memmove':
ltdl.c:435:9: warning: dereferencing 'void *' pointer
  435 |     dest[i] = src[i];
      |         ^
ltdl.c:435:18: warning: dereferencing 'void *' pointer
  435 |     dest[i] = src[i];
      |                  ^
ltdl.c:435:13: error: invalid use of void expression
  435 |     dest[i] = src[i];
      |             ^
ltdl.c:438:25: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
  438 |     for (i = size -1; i >= 0; --i)
      |                         ^~
ltdl.c:440:9: warning: dereferencing 'void *' pointer
  440 |     dest[i] = src[i];
      |         ^
ltdl.c:440:18: warning: dereferencing 'void *' pointer
  440 |     dest[i] = src[i];
      |                  ^
ltdl.c:440:13: error: invalid use of void expression
  440 |     dest[i] = src[i];
      |             ^
ltdl.c: At top level:
ltdl.c:875:39: error: 'LTDL_OBJDIR' undeclared here (not in a function); did you mean 'LT_OBJDIR'?
  875 | static  const char  objdir[]        = LTDL_OBJDIR;
      |                                       ^~~~~~~~~~~
      |                                       LT_OBJDIR
ltdl.c:2170:9: error: unknown type name 'FILE'
 2170 | static  FILE   *find_file         LT_PARAMS((const char *search_path,
      |         ^~~~
ltdl.c: In function 'tryall_dlopen_module':
ltdl.c:2505:3: warning: implicit declaration of function 'sprintf' [-Wimplicit-function-declaration]
 2505 |   sprintf (filename, "%.*s/%s", (int) dirname_len, dirname, dlname);
      |   ^~~~~~~
ltdl.c:2505:3: warning: incompatible implicit declaration of built-in function 'sprintf'
ltdl.c:1067:1: note: include '<stdio.h>' or provide a declaration of 'sprintf'
 1066 | #  include <dlfcn.h>
  +++ |+#include <stdio.h>
 1067 | #endif
ltdl.c: In function 'find_file_callback':
ltdl.c:2750:3: error: unknown type name 'FILE'
 2750 |   FILE       **pfile    = (FILE **) data2;
      |   ^~~~
ltdl.c:2750:3: note: 'FILE' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?
ltdl.c:2750:28: error: 'FILE' undeclared (first use in this function)
 2750 |   FILE       **pfile    = (FILE **) data2;
      |                            ^~~~
ltdl.c:2750:28: note: 'FILE' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?
ltdl.c:2750:28: note: each undeclared identifier is reported only once for each function it appears in
ltdl.c:2750:35: error: expected expression before ')' token
 2750 |   FILE       **pfile    = (FILE **) data2;
      |                                   ^
ltdl.c:2750:33: error: invalid operands to binary * (have 'const char *' and 'int')
 2750 |   FILE       **pfile    = (FILE **) data2;
      |                            ~~~~ ^
      |                            |
      |                            const char *
ltdl.c:2750:27: warning: initialization of 'int **' from incompatible pointer type 'const char *' [-Wincompatible-pointer-types]
 2750 |   FILE       **pfile    = (FILE **) data2;
      |                           ^
ltdl.c:2757:17: warning: implicit declaration of function 'fopen' [-Wimplicit-function-declaration]
 2757 |   if ((*pfile = fopen (filename, LT_READTEXT_MODE)))
      |                 ^~~~~
ltdl.c:2757:17: note: 'fopen' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?
ltdl.c:2757:15: warning: assignment to 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 2757 |   if ((*pfile = fopen (filename, LT_READTEXT_MODE)))
      |               ^
ltdl.c:362:21: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  362 | #    define strrchr rpl_strrchr
      |                     ^~~~~~~~~~~
ltdl.c:2759:22: note: in expansion of macro 'strrchr'
 2759 |       char *dirend = strrchr (filename, '/');
      |                      ^~~~~~~
ltdl.c:2747:13: warning: unused parameter 'data2' [-Wunused-parameter]
 2747 |      lt_ptr data2;
      |             ^~~~~
ltdl.c: At top level:
ltdl.c:2772:8: error: unknown type name 'FILE'
 2772 | static FILE *
      |        ^~~~
ltdl.c: In function 'find_file':
ltdl.c:2778:3: error: unknown type name 'FILE'
 2778 |   FILE *file = 0;
      |   ^~~~
ltdl.c:2778:3: note: 'FILE' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?
ltdl.c: In function 'try_dlopen':
ltdl.c:3108:13: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3108 |   base_name = strrchr (canonical, '/');
      |             ^
ltdl.c:3135:7: error: unknown type name 'FILE'
 3135 |       FILE *    file     = 0;
      |       ^~~~
ltdl.c:3135:7: note: 'FILE' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?
ltdl.c:3161:13: warning: implicit declaration of function 'isalnum' [-Wimplicit-function-declaration]
 3161 |         if (isalnum ((int)(base_name[i])))
      |             ^~~~~~~
ltdl.c:3211:12: warning: assignment to 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 3211 |       file = fopen (filename, LT_READTEXT_MODE);
      |            ^
ltdl.c:3227:7: warning: implicit declaration of function 'fclose'; did you mean 'close'? [-Wimplicit-function-declaration]
 3227 |       fclose (file);
      |       ^~~~~~
      |       close
ltdl.c:3233:15: warning: implicit declaration of function 'feof' [-Wimplicit-function-declaration]
 3233 |       while (!feof (file))
      |               ^~~~
ltdl.c:3235:12: warning: implicit declaration of function 'fgets' [-Wimplicit-function-declaration]
 3235 |       if (!fgets (line, (int) line_len, file))
      |            ^~~~~
ltdl.c:3303:28: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3303 |           && (last_libname = strrchr (dlname, ' ')) != 0)
      |                            ^
ltdl.c: In function 'lt_dlopenext':
ltdl.c:3481:7: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3481 |   ext = strrchr (filename, '.');
      |       ^
gmake[2]: *** [Makefile:2511: ltdl.lo] Error 1
gmake[2]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed'
gmake[1]: *** [Makefile:2561: all-recursive] Error 1
gmake[1]: Leaving directory '/export/software/OpenSource/Hercules/hyperion-b8a26cfd6bf70c46898d39bc8370e5d81c1e5eed'
gmake: *** [Makefile:1897: all] Error 2

```

and now I am lost again...

**Comment by racingmars** [comment]
Hi @hurgler,

For the `--enable-extpkgs=/path/to/extpkgs` I think you need just the base extpkgs directory path, not the `lib/ppc` part -- the build will look for the lib/ppc folder on its own. So in your case, `--enable-extpkgs=./extpkgs`, but I'm not sure if relative paths are supported; might want to use the full path just to be safe (`--enable-extpkgs=/export/software/OpenSource/Hercules/.../extpkgs`)

It also looks like libtool-ltdl-devel might not be installed -- please make sure you install that RPM package first (it's in the IBM repository so should easily install with yum)

**Comment by hurgler** [comment]
@racingmars I also have /opt/freeware/bin at the top of my PATH...
I'll try settung CFLAGS and LDFLAGS

**Comment by hurgler** [comment]
@racingmars Cool. With CFLAGS and LDFLAGS it compiled. Today I will try if it also works ... but at least it looks very good. Thank you very much...

**Comment by hurgler** [comment]
@racingmars Hi... VICTORY!!! Hercules starts (but with errors) - so it seems fine. But it does not start like in Linux - so I hope you can help me also with two starting issues in AIX:

1.) the missing TUN/TAP device: is it possible to use network with AIX? What have I to do to do so? Here is the hercules error:
```
HHC00137E Error opening TUN/TAP device /dev/net/tun: No such file or directory
HHC00007I Previous message from function 'TUNTAP_CreateInterface' at tuntap.c(241)
HHC01463E 0:0E21 device initialization failed
...
HHC00137E Error opening TUN/TAP device /dev/net/tun: No such file or directory
HHC00007I Previous message from function 'TUNTAP_CreateInterface' at tuntap.c(241)
HHC01463E 0:0E21 device initialization failed
HHC00007I Previous message from function 'attach_device' at config.c(1331)
```
2.) also I have some issues with some CCKD (just 2) which I hadn't in LINUX..
```
HHC00368W 0:0AA3 CCKD file /lager/hercules/CCKDs/CCKD12: free space errors detected
HHC00007I Previous message from function 'cckd_chkdsk' at cckdutil.c(1769)
```

But after all: Thank you very much!!!

**Comment by racingmars** [comment]
@hurgler - Excellent, glad you got it compiled!!

> 1.) the missing TUN/TAP device: is it possible to use network with AIX? What have I to do to do so?

It may not be possible... I did some quick searching, and I don't think AIX has a TUN/TAP driver. Also...some of the workarounds I did in the code to get around some compilation problems in the networking code would probably need to be revisited if networking were needed.

> 2.) also I have some issues with some CCKD (just 2) which I hadn't in LINUX..
> 
> ```
> HHC00368W 0:0AA3 CCKD file /lager/hercules/CCKDs/CCKD12: free space errors detected
> HHC00007I Previous message from function 'cckd_chkdsk' at cckdutil.c(1769)

I'm not sure about this one.

> 3.) and in Starting hercules there are some Warnings:
> 
> ```
> HHC00109E set_thread_priority( 5 ) failed: Not owner
> HHC00110W Defaulting all threads to priority 0
> HHC90020W 'hthread_setschedparam()' failed at loc=impl.c:1011: rc=22: Invalid argument
> ```

I'd just ignore thread priority errors and warnings :-)

**Comment by Fish-Git** [comment]
> 2.) also I have some issues with some CCKD (just 2) which I hadn't in LINUX..
> 
> ```
> HHC00368W 0:0AA3 CCKD file /lager/hercules/CCKDs/CCKD12: free space errors detected
> HHC00007I Previous message from function 'cckd_chkdsk' at cckdutil.c(1769)
> ```

Free space errors are indicative of serious dasd image file corruption. I would _strongly_ suggest that you run a **[`cckdcdsk -3 /lager/hercules/CCKDs/CCKD12`](https://sdl-hercules-390.github.io/html/cckddasd.html#utilities)** to fix the problem. &nbsp; _(**IMPORTANT!** never do a `-4` check!)_

Free space errors (i.e. _any_ type of reported file damage) typically occur when your guest is unexpectedly terminated. Try to ensure that both your guest (and Hercules itself too!) are always shutdown _gracefully._ This means shutting down your guest normally, such as for z/OS, waiting until the `s shutdown` command reaches "All available functions complete" and the `quiesce` command completes (reaches a disabled wait). Then and _only_ then is it safe to close (exit) Hercules.

If you experience frequent "hangs" in Hercules or with AIX itself (or power failures where you live for example), you should always do a `cckdcdsk` on all of your Hercules dasds (before starting Hercules) to repair any possible damage that may have occurred.

If you frequently experience such error messages from Hercules and do not know why they are occurring, then that _might_ be indicative of a bug in Hercules, but is IMO unlikely. Hercules's dasd file logic is quite well tested, so if Hercules complains about free space errors for example, you can trust that it is telling the truth and your dasd image files, for whatever reason, are indeed corrupted and need to be repaired. Always run a `cckdcdsk` in that case. _(make sure Hercules is **not running** when you do too!)_

Finally, you should make sure that you backup your host system (including all Hercules dasd files too) on a regular basis, so that you can restore your dasd images whenever you need to. So many people get lazy and forget to do that. I myself prefer using Hercules **["shadow files"](https://sdl-hercules-390.github.io/html/cckddasd.html#shadowfiles)** since it makes backing up your Hercules systems quite fast and easy.

Hope that helps!

**Comment by Fish-Git** [comment]
> > 3.) and in Starting hercules there are some Warnings:
> > ```
> > HHC00109E set_thread_priority( 5 ) failed: Not owner
> > HHC00110W Defaulting all threads to priority 0
> > HHC90020W 'hthread_setschedparam()' failed at loc=impl.c:1011: rc=22: Invalid argument
> > ```
> 
> I'd just ignore thread priority errors and warnings. `:-)`

These occur due to Hercules not being started "elevated" (i.e. as root), which is required in order for Hercules to be able to properly set the thread priorities for its internal threads.

In order to be able to do this however, you need to make sure Hercules is built with the `--enable-capabilities` configure option, which should be the default (unless you're missing the `sys/capability.h` header of course).

**Comment by Fish-Git** [comment]
Is this issue resolved now? Can it be close?

**Comment by racingmars** [comment]
> Is this issue resolved now? Can it be closed?

I think so. Some of my patch is too much of a hack to suggest we should shoot for out-of-the-box AIX build support at the moment, but if someone's adventurous (they'd have to be if they want to run Hercules on AIX for fun) the notes here can serve to point them in the right direction.

**Comment by Fish-Git** [comment]
Closing.
