### ISSUE TITLE
Clang problem with '-minline-stringops-dynamically'

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#427]
When building with CLANG (v 10.0.0 under Ubuntu 20.04.3) the '-minline-stringops-dynamically' optimization option causes the build to fail : 

```
hercules@pjamdz3a:~/SDL-hyperion$ clang -v
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
Found candidate GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
hercules@pjamdz3a:~/SDL-hyperion$

hercules@pjamdz3a:~/SDL-hyperion$ ./configure CFLAGS="-Wno-unused-result -Wno-cpp" --enable-extpkgs=../SDL-extpkgs --prefix=/usr/local/fish --enable-object-rexx --enable-multi-cpu=16 CC=clang CXX=clang++
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
[...]

hercules@pjamdz3a:~/SDL-hyperion$ make -j 12
make  all-recursive
make[1]: Entering directory '/home/hercules/SDL-hyperion'
Making all in m4
[...]
  CC       hthreads.lo
  CC       logger.lo
  CC       logmsg.lo
  CC       memrchr.lo
clang: error: unknown argument: '-minline-stringops-dynamically'
make[2]: *** [Makefile:2504: cckdcdsk.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
clang: error: unknown argument: '-minline-stringops-dynamically'
make[2]: *** [Makefile:2518: logmsg.lo] Error 1
make[2]: *** [Makefile:2518: hscutl.lo] Error 1
make[2]: *** [Makefile:2518: logger.lo] Error 1
make[2]: *** [Makefile:2518: codepage.lo] Error 1
make[2]: *** [Makefile:2518: hthreads.lo] Error 1
make[2]: *** [Makefile:2518: memrchr.lo] Error 1
make[2]: *** [Makefile:2518: hostinfo.lo] Error 1
make[2]: *** [Makefile:2518: hsocket.lo] Error 1
clangclang: : errorerror: : unknown argument: '-minline-stringops-dynamically'unknown argument: '-minline-stringops-dynamically'

clang: error: unknown argument: '-minline-stringops-dynamically'
make[2]: *** [Makefile:2518: hsys.lo] Error 1
make[2]: *** [Makefile:2518: hexdumpe.lo] Error 1
make[2]: *** [Makefile:2518: hdl.lo] Error 1
make[2]: Leaving directory '/home/hercules/SDL-hyperion'
make[1]: *** [Makefile:2568: all-recursive] Error 1
make[1]: Leaving directory '/home/hercules/SDL-hyperion'
make: *** [Makefile:1903: all] Error 2
hercules@pjamdz3a:~/SDL-hyperion$
```
A simple (but probably not fit as a permanent) solution is to just remove the '-minline-stringops-dynamically' option, twice, from "configure.ac". Then the CLANG build works fine.

Cheers,

Peter

**Comment by Fish-Git** [comment]
I build Hercules on my KDE Neon 5.22.5 system using clang 10.0.0 and it builds just fine. You must be doing something wrong.

What I suspect you are doing wrong is specifying "CFLAGS=" in your configure. If you want to use compiler options that are different from the ones Hercules provides by default, then I believe you need to specify them in your `--enable-optimization=FLAGS` configure option:

<pre>
./configure --enable-optimization="<b><i>-Wno-unused-result -Wno-cpp</i></b> -g -g3 -ggdb3 -O3 -march=native" --enable-extpkgs=../SDL-extpkgs --prefix=/usr/local/fish --enable-object-rexx --enable-multi-cpu=16 CC=clang CXX=clang++
</pre>

As you know, I am _FAR_ from being a Linux expert, but I'm _**guessing**_ that by your having manually specified CFLAGS, the normal ` -g -g3 -ggdb3 -O3 -march=native` options that would _otherwise_ have normally been specified, didn't get specified, resulting in the `-minline-stringops-dynamically` option somehow getting specified when it shouldn't have.

Normally, Hercules's auto-optimization logic tries to automatically determine the correct CFLAGS to use unless you override Hercules's defaults by manually specifying the flags yourself via the `--enable-optimization=yes|no|FLAGS` configure option (which _disables_ Hercules's auto-optimization logic).

Since your ./configure did _NOT_ specify the `--enable-optimization=...` configure option, Hercules's auto-optimization logic did not get get overridden, resulting in incorrect CFLAGS being used.

Basically what ended up happening is your CFLAGS were completely discarded and _replaced_ with Hercules's. To confirm this, take a look at your configure.log. At the end you should see something like:

<pre>
...
...
...
configure: Using External Packages override directory /home/neon/hercules/extpkgs/. 
configure: NOTICE: sizeof(__int128_t) >= 16; max CPU engines = 128 
checking whether getopt wrapper kludge is necessary... no
<b><i>checking for what optimization flags to use ... -g -g3 -ggdb3 -O3 -march=native</i></b>
configure:                                           
configure:  Package destination directory prefixes:  
configure:                                           
configure:     Libraries:  $(libdir)/$(PACKAGE)             
configure:     Data:       $(datadir)/hercules      
configure:     Locale:     ${datarootdir}/locale              
configure:                                           
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
...
...
...
</pre>

Because you never overrode Hercules's default optimization flags, Hercules used it's own flags, which are obviously for clang.

_(Note: I personally always specify `--enable-optimization="-g -g3 -ggdb3 -O3 -march=native"` for both gcc _and_ clang.)

Sooo... Should this be considered a user error? Or a bug in Hercules's auto-optimization logic? I'm thinking a little bit of both.

**Comment by Fish-Git** [comment]
> What I suspect you are doing wrong is specifying "CFLAGS=" in your configure. If you want to use compiler options that are different from the ones Hercules provides by default, then I believe you need to specify them in your `--enable-optimization=FLAGS` configure option:

_**OR...**_ &nbsp;specify `--enable-optimization=no`. By specifying "no", Hercules's auto-optimization logic should end up getting disabled, thereby allowing your CFLAGS to be honored (not overridden). That should work too.

So you basically have two choices:

1. Continue to use CFLAGS like you already are, but add `--enable-optimization=no` to your list of ./configure options (to prevent Hercules from overriding your CFLAGS)
2.  _Remove_ your CFLAGS options and move them into the `--enable-optimization="..."` ./configure option instead.

Your choice.

**Comment by wrljet** [comment]
I already have a configure.ac change "pending" that addresses this issue.
Just haven't gotten around to posting it yet.

It uses the configure mechanism to detect automatically of the compiler rejects that optimization.

Bil

**Comment by Fish-Git** [comment]
> I already have a configure.ac change "pending" that addresses this issue.

Fantastic! &nbsp;I look forward to seeing it. &nbsp;_Thanks_, Bill! &nbsp; `:)`

**Comment by atncsj6h** [comment]
instead of guessing the supported flags for every combination of version/release of the compiler
I find easier/faster  to use   the macros of the familiy 
https://www.gnu.org/software/autoconf-archive/ax_append_compile_flags.html
https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html

e

**Comment by Peter-J-Jansen** [comment]
I tried the 2nd choice as suggested by Fish, that is leaving out my CFLAGS setting altogether, as they were only there to suppress some compiler warnings, but the '-minline-stringops-dynamically' problem still exists : 
```
hercules@pjamdz3a:~/SDL-hyperion$ ./configure --enable-extpkgs=../SDL-extpkgs --prefix=/usr/local/fish --enable-object-rexx --enable-multi-cpu=16 CC=clang CXX=clang++
[...]
hercules@pjamdz3a:~/SDL-hyperion$ make
make  all-recursive
make[1]: Entering directory '/home/hercules/SDL-hyperion'
[...]
  CC       cckdcdsk.o
clang: error: unknown argument: '-minline-stringops-dynamically'
make[2]: *** [Makefile:2504: cckdcdsk.o] Error 1
make[2]: Leaving directory '/home/hercules/SDL-hyperion'
make[1]: *** [Makefile:2568: all-recursive] Error 1
make[1]: Leaving directory '/home/hercules/SDL-hyperion'
make: *** [Makefile:1903: all] Error 2
hercules@pjamdz3a:~/SDL-hyperion$
```
Fish, where you mentioned a  successful Clang build on your KDE Neon 5.22.5 system using clang 10.0.0, were you doing a complete build, like after a "sudo make clean", or just a partial build for some modified sources ? This might explain why you were successful, whereas my complete build was not. I noticed that the error message was for "cckdcdsk" which then stops the "make" altogether. 

Bill, does you fix use the technique @atncsj6h mentions ? I am totally unaware of the internals of "configure" and "autotools" etc., so I am unable to help with this. All I dared doing was just (twice) removing the '-minline-stringops-dynamically' option in "configure.ac" as a temporary successful workaround. And this is important, because the Linux gcc based builds are problematic for me at this point in time (a 2nd level PRG018 crash). So the only Linux build possibility is with Clang and this workaround.

Cheers,

Peter

**Comment by atncsj6h** [comment]
if I had to do it I would extend the checking also to the flags  specified in the --enable-optimization
it would provide  a better and complete error handling 

enrico

**Comment by wrljet** [comment]
> Bill, does you fix use the technique @atncsj6h mentions ? I am totally unaware of the internals of "configure" and "autotools" etc., so I am unable to help with this. All I dared doing was just (twice) removing the '-minline-stringops-dynamically' option in "configure.ac" as a temporary successful workaround. And this is important, because the Linux gcc based builds are problematic for me at this point in time (a 2nd level PRG018 crash). So the only Linux build possibility is with Clang and this workaround.

Yes, it does.

**Comment by Peter-J-Jansen** [comment]
Hi Enrico (@atncsj6h), is that the same Enrico that helped me starting with MacOS's TUN and TAP devices for Hercules some years ago ? How are you doing ? Hope all is well with you !

Cheers,

Peter

**Comment by atncsj6h** [comment]
Yes Peter, that's me
thanks &deity,even with the current COVID confused situation, things go reasonably well, 
I hope the same for You and Your family

enrico
 
PS. feel free to contact me on my email address

**Comment by Fish-Git** [comment]
> I tried the 2nd choice as suggested by Fish, that is leaving out my CFLAGS setting altogether, as they were only there to suppress some compiler warnings, but the '-minline-stringops-dynamically' problem still exists :

You _tried_ to do my 2nd choice, but it appears you _forgot_ to add the `--enable-optimization="..."` option.

> Fish, where you mentioned a successful Clang build on your KDE Neon 5.22.5 system using clang 10.0.0, were you doing a complete build, like after a "sudo make clean", or just a partial build for some modified sources?

I was doing a complete build. _BUT..._ I admit my original response was unintentionally misleading. I failed to mention that whenever I build Hercules (using either gcc _**or**_ clang), I _always_ manually specify the `--enable-optimization="..."` configue option every time, where the "enable-optimization" value that I always use is "-g -g3 -ggdb3 -O3 -march=native":

> > _(Note: I personally **always** specify `--enable-optimization="-g -g3 -ggdb3 -O3 -march=native"` for both gcc _and_ clang.)_

I apologize for that confusion. Apparently Hercules's _default_ "auto-optimization flags" logic is buggy, such that when you fail to specify your own specific flags (and try to let Hercules decide what flags to use), Hercules chooses, at least for Intel, to always (erroneously?) include the `-minline-stringops-dynamically` option, which is the original problem this GitHub Issue describes.

When you _always_ specify `--enable-optimization="-g -g3 -ggdb3 -O3 -march=native"` in your ./configure, then Hercules always builds correctly/cleanly (or at least it does for me anyway).

So... Please try again, using:
<pre>
./configure <b><i>--enable-optimization="-g -g3 -ggdb3 -O3 -march=native"</i></b> --enable-extpkgs=../SDL-extpkgs --prefix=/usr/local/fish --enable-object-rexx --enable-multi-cpu=16 CC=clang CXX=clang++
</pre>

and I'm confident your build will succeed.

**Comment by Fish-Git** [comment]
> ... whenever I build Hercules (using either gcc _**or**_ clang), I _always_ manually specify the `--enable-optimization="..."` configue option every time, ...

I use a simple bash script that I wrote to help me build Hercules, and it is hard-coded to _**always**_ "--enable-optimization="-g -g3 -ggdb3 -O3 -march=native" every single time (for both gcc and clang too).

Manually typing a very long ./configure command with many options each time is too cumbersome and prone to error, so I use a script instead. If I ever want to change my options, I simply edit my script.

But your original opening of this github issue illustrates quite clearly that Hercules's "automatic-optimization" logic in `configure.ac` is buggy and needs fixing/tweaking, so thank you for reporting it.

We'll get it straightened out eventually.

**Comment by Fish-Git** [comment]
> Instead of guessing the supported flags for every combination of version/release/system of the compiler, I find easier/faster to use the macros of the familiy:
> 
> * https://www.gnu.org/software/autoconf-archive/ax_append_compile_flags.html
> * https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html

_VERY_ nice! &nbsp; _Thank you_, Enrico! &nbsp; `:)`

Bill? (@wrljet) &nbsp; Do you want to investigate this for us? Or do you want me to try and take a stab at it?

I don't want to impact (screw up) your existing pending configure.ac changes you are wanting to commit, so I'd rather you look into this for us than me.

Besides, you've become our unofficial "Linux make" go-to person and probably have a lot more experience at it than me and thus would be much less likely to screw things up than someone like me! &nbsp; `;-)`

Thanks. &nbsp;`:)`

**Comment by dasdman** [comment]
Enrico wrote per Fish:

              Instead of guessing the supported flags for every combination of version/release/system of the compiler, I find easier/faster to use the macros of the familiy:

*	https://www.gnu.org/software/autoconf-archive/ax_append_compile_flags.html
*	https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html


FYI. autoconf elements contained within the Hercules build must be brought up-to-date first.

 

Mark
dasdman

**Comment by wrljet** [comment]
> Bill? (@wrljet)   Do you want to investigate this for us? Or do you want me to try and take a stab at it?


Yes, I'll do that.
