### ISSUE TITLE
Incorrect "V=" instruction operand data traced in AR mode

### ISSUE THREAD

**Issue by YossiReichman** [SDL-Hercules-390/hyperion#451]
The trace leaves the first few bytes of either operand-1 or operand-2 (i.e `V=`). When this address is qualified by an ALET in Access Register mode, the `V=` data is erroneous. An example would be better so here goes:

Register 8 is pointing to a data space. Access Register 8 has an ALET, and the code is running in Access Register mode. The traced instruction's displayed `V=` operand data shows the operand's data as being spaces (X'40'), but I know for a fact that's not the actual data in the data space.

```
23:25:21 HHC02324I CP00: PSW=0704400180000000 000000001FA94E08 INST=D203C004800C MVC   4(4,12),12(8)          move_character
23:25:21 HHC02326I CP00: V:000001F059423402:K:06=0000 00000000 00000000 00000000 0000 ................
23:25:21 HHC02326I CP00: V:000000000000CE9F:K:06=40 40404040 40404040 40404040 404040
23:25:21 HHC02269I CP00: R0=0000005000101000 R1=000001F0594233FE R2=000000001FAAA000 R3=000000001FA94608
23:25:21 HHC02269I CP00: R4=000000001FAA9000 R5=000000001FAAA000 R6=000001F059422F68 R7=000000001DF48750
23:25:21 HHC02269I CP00: R8=000000000000CE93 R9=000000001FA03047 RA=000000001FAAA308 RB=0000000000000006
23:25:21 HHC02269I CP00: RC=000001F0594233FE RD=000000001FAAA308 RE=000000001FA94AE3 RF=000001F059423267
23:25:21 HHC02271I CP00: C0=00800002DF9CEE20 C1=000000074350C007 C2=000000007CA79540 C3=0000000300C00021
23:25:21 HHC02271I CP00: C4=0000000300010021 C5=000000007EF46840 C6=00000000FE000000 C7=000000074350C007
23:25:21 HHC02271I CP00: C8=0000000000000000 C9=0000000000000000 CA=0000000000000000 CB=0000000000000000
23:25:21 HHC02271I CP00: CC=0000000100565197 CD=000000074350C007 CE=00000000DF8FEF45 CF=000000007F5EE9D8
23:25:21 HHC02272I CP00: AR00=00000003 AR01=001C0003 AR02=00000000 AR03=00000000
23:25:21 HHC02272I CP00: AR04=00000000 AR05=00000000 AR06=00000000 AR07=00000000
23:25:21 HHC02272I CP00: AR08=00020004 AR09=00000000 AR10=00000000 AR11=00000000
23:25:21 HHC02272I CP00: AR12=001C0003 AR13=00000000 AR14=00000000 AR15=001C0003
```

**Comment by Fish-Git** [comment]
> The trace leaves the first few bytes of either operand-1 or operand-2 (i.e `V=`).

I don't understand what that means. &nbsp; `:(`

> When this address is qualified by an ALET in Access Register mode, the `V=` data is erroneous.

_THAT_ I _do_ understand!

Can we see your Hercules logfile please? What _specific_ version of Hercules are you running? Official 4.3? Or some other version? I'm going to presume it's 4.3.

Therefore, given that the upcoming 4.4 release of Hercules contains some important DAT fixes related to AR mode (see commit e74bec604ee3a46dffe317a4543a49fb216dcc73) that might well resolve your issue, I am going to defer attempting to resolve it until _after_ 4.4 has been released and you have had a chance to try again using 4.4. _(The problem you report _may_ have already been fixed in 4.4!)_

So please wait a few days _(the new 4.4 version of Hercules's scheduled to be released on Saturday, December 18, 2021)_ and then please try your test again using 4.4 once it's released.

If the problem still occurs with Hercules version 4.4 too, _then_ I promise to look into your issue.

Fair enough?

**Comment by YossiReichman** [comment]
﻿What I meant was that if either operand refers to storage it displays the storage 
I guess V= stands for ( virtual address = ) 

Ok thanks you fixed my biggest problem with the stepping 

I’ll try to up load the log file

Thanks

**Comment by Fish-Git** [comment]
Joe has uploaded a partial logfile of the output of an instruction trace to:

* [DBGRABRK.TXT](https://github.com/SDL-Hercules-390/hyperion/files/7723978/DBGRABRK.TXT)

**Comment by Fish-Git** [comment]
Joe: Have you had a chance to try 4.4 yet? Does it display correctly in 4.4?

**Comment by YossiReichman** [comment]
﻿I was trying to build it from source seems it was built using .netframework 4.0 the build failed On my laptop I have Microsoft .NET SDK 5.0.402 think I have to change something in the solution or project file 

Will look at it after work in about an hour and change 

Thanks 


Joe Reichman
Lead Developer Sam Golob Systems Programming 

71-28 163 st apt 1A
Fresh meadows NY 11365

**Comment by wrljet** [comment]
Joe,

This is confusing because the Hercules solution doesn't use or need anything .NET Framework.

Normally I do builds from command prompt, but I just tried it from inside VS2019 and it worked.

Please export your VS2019 configuration and post it here.

You can get that by running Visual Studio Installer.  Should be found off the Start menu.

When that comes up, select the More dropdown menu, and then click Export Configuration.

![1](https://user-images.githubusercontent.com/3638124/147156154-c0e49d15-7985-42f8-8d2d-de15167a2d0d.jpg)

Then in the next dialog, pick a directory location of the file, and click Review Details.

![2](https://user-images.githubusercontent.com/3638124/147156283-c18fa945-3948-4e39-956a-6bfb89813ca7.jpg)

And then when the next dialog, click Export at the bottom.

![3](https://user-images.githubusercontent.com/3638124/147156478-120705ab-7d53-4367-9024-3d489f923f47.jpg)

For comparison, my VS2019.vsconfig contains as seen below.
These are about the minimum workloads needed to build Hercules.
This VS2019 was installed automagically by my Hercules-Helper-Windows thingy.

`
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.Windows10SDK.17763",
    "Microsoft.Component.VC.Runtime.UCRTSDK",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
    "Component.GitHub.VisualStudio",
    "Microsoft.VisualStudio.Component.Git",
    "Microsoft.VisualStudio.Component.WinXP"
  ]
}
`

Bill

**Comment by YossiReichman** [comment]
Ok thanks 

 

Let me re-try downloading the source

**Comment by Fish-Git** [comment]
> I was trying to build it from source

Why are you building it from source?

Is there a reason why you can't just download the official Windows binaries from our Release web page and use them?

* [Official Release_4.4 web page](https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.4)

(Direct download URL of the binaries):

* [Hercules-4.4.0.10631-SDL-gbf377f63-x64.zip](https://github.com/SDL-Hercules-390/hyperion/releases/download/Release_4.4/Hercules-4.4.0.10631-SDL-gbf377f63-x64.zip)

**Comment by wrljet** [comment]
> Why are you building it from source?

I didn't want to ask that myself. :-)

**Comment by YossiReichman** [comment]
here is the .vsconfig file
[vsconfig.txt](https://github.com/SDL-Hercules-390/hyperion/files/7765385/vsconfig.txt)
Ill download the binaries and try it

**Comment by YossiReichman** [comment]
Fish you are great the ALET is qualified I the data in log file can upload it if you want but while I am here I am closing this issue

**Comment by YossiReichman** [comment]
forgot to close

**Comment by YossiReichman** [comment]
Thank you I closed it have the log file 
I can upload it if you want

**Comment by Fish-Git** [comment]
> have the log file I can upload it if you want

Please!

**Comment by YossiReichman** [comment]
Ok I’ll get back on in 5 minutes and upload it 
R8 is referenced by the alet pointing to a dataspace not spaces anymore it’s in a different piece of my code but the trace PSW shows in ar mode and AR8 is populated

**Comment by wrljet** [comment]
Joe,

You're missing this component: C++ Windows XP Support for VS 2017 (v141...)

![10](https://user-images.githubusercontent.com/3638124/147164407-db73be6f-bae1-4e81-b63a-dbf1232af21b.jpg)

Bill

**Comment by YossiReichman** [comment]
Thanks 

I’ll do a repair or modify of vs

**Comment by YossiReichman** [comment]
[RECOVERY.TXT](https://github.com/SDL-Hercules-390/hyperion/files/7765652/RECOVERY.TXT)
here is the log file reference an mvc of r8

**Comment by YossiReichman** [comment]
Log file uploaded :) thank you

**Comment by wrljet** [comment]
> Thanks I’ll do a repair or modify of vs
> […](#)
> On Dec 22, 2021, at 6:00 PM, Bill Lewis ***@***.***> wrote: ﻿ Joe, You're missing this component: C++ Windows XP Support for VS 2017 (v141...) Bill — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.

That will be a Modify.

Bill

**Comment by YossiReichman** [comment]
Thank you was able to rebuild from source :)

**Comment by wrljet** [comment]
God knows why MSFT would give you an error related to .NET Framework, when that has nothing to do with the problem.
