### ISSUE TITLE
Hercules build failure using VS2017 - hercules.exe not found

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#453]
I tried building Hercules today using makefile.bat and the Visual Studio GUI. Both failed the same way, Hercules.exe not found.  Here are a few of the last lines displayed.  The entire log is attached.  Using Windows 7. I ran an old Hercules 4.2 build and that was successful.

* [herclog.txt](https://github.com/SDL-Hercules-390/hyperion/files/7740057/herclog.txt)

**Comment by wrljet** [comment]
That is likely because an anti-virus pgm was scanning the exe just produced when VS was trying to update the manifest.

Configure your anti-virus to keep hands off the directory tree you're building in and try again.

Bill

**Comment by Fish-Git** [comment]
I would agree with Bill. According to your log the build was clean. It was only at the very end when the "hercules.exe" executable itself was being linked that the error occurred. Such errors are not the fault of Hercules since it is not Hercules that is linking (creating) the executable. It's Visual Studio that's doing it.

If it were me I would just try the build again. If it continues to fail (if it keeps consistently failing in the same place in the same way each time), then I would try _temporarily_ disabling your AV to eliminate that variable from the equation. (What AV product are you using BTW?)

**Comment by rgschmi** [comment]
You are correct!   The build was successful using makefile.bat with the antivirus disabled.  Something to keep in mind when I try hercules-helper!

**Comment by Fish-Git** [comment]
> You are correct! The build was successful using makefile.bat with the antivirus disabled.

Fantastic! Closing issue as User Error.

**Comment by rgschmi** [comment]
As this was already closed, as it should be, I'm replying directly to your email that I'm using Avast, and I'm getting less happy with it as time goes on...
