### ISSUE TITLE
              Request for Hercules version of VMFPLC2 to Process Tape Commands

### ISSUE THREAD

**Issue by marXtevens** [SDL-Hercules-390/hyperion#468]
The almost-current version of `vmfplc2` (see below) does not appear to handle tape movement commands, such as: fsf, rew, wtm.

The VM/370 Sysgen manual: [GC20-1801-10 "VM/370 Sysgen (Rel 6)"](http://bitsavers.trailing-edge.com/pdf/ibm/370/VM_370/Release_6/GC20-1801-10_VM370_Sysgen_Rel_6_Jan80.pdf) does not specifically call out all the possibilities, but does make use of such commands through the manual. (See pages 256, 349.)

Oddly, the manual, [GC20-1807-07 "VM/370 System Programmer's Guide"](http://bitsavers.trailing-edge.com/pdf/ibm/370/VM_370/Release_6/GC20-1807-7_VM370_System_Programmers_Guide_Rel_6_4-81.pdf), does not document the command. There does exist documentation on the VM/370 CE V1 release, via `help vmfplc2`.

This enhancement would be useful for extracting files from a VMFPLC2 formatted tape to a Windows/Linux/Mac system, where the individual is attempting to extract and work on, or transfer a few files from a "tape."

 ... Mark S.

```
[xmas@vm370dev tapes]$ vmfplc2 fsf 131 86WTTL.AWS
HHC02499I Hercules utility vmfplc2 - VM/CMS VMFPLC2/TAPE Utility - version 4.4.9999.0-SDL
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar  5 2021 at 16:26:42
HHC02621E Invalid function "fsf"
HHC00007I Previous message from function 'parse_parms' at vmfplc2.c(263)
HHC02620I Usage: vmfplc2 [options] VERB [<ctlfile>] <tapein> | <tapeout>
HHC02620I   VERB      desired action               (DUMP/LOAD/SCAN)
HHC02620I   ctlfile   filename of control file     (DUMP/LOAD only)
HHC02620I   tapein    filename of input tape file  (LOAD/SCAN only)
HHC02620I   tapeout   filename of output tape file (DUMP only)
HHC02620I Options:
HHC02620I   -c cp     desired translation codepage
HHC02620I   -t        read/write tape in CMS 'TAPE' DUMP format
HHC02620I   -v        don't suppress certain informational messages
HHC02620I   -u        create uncompressed .aws output
HHC02620I   -z        create compressed .het using zlib (default)
HHC02620I   -b        create compressed .het using bzip2
HHC02620I   -4        desired compression level (-1, -2 ... -9)
[xmas@vm370dev tapes]$ 
```

**Comment by Fish-Git** [comment]
> The almost-current version of `vmfplc2` (see below) does not appear to handle tape movement commands, such as: fsf, rew, wtm.

Correct. Since there is no real need to support such commands.

> This enhancement would be useful for extracting files from a VMFPLC2 formatted tape to a Windows/Linux/Mac system, where the individual is attempting to extract and work on, or transfer a few files from a "tape."

It is unclear to me what "problem" your change request is attempting to resolve.

To "extract" files from a VMFPLC2 formatted tape, use the "LOAD" function:

* https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.VMFPLC2.md

It appears you are not using the Hercules `vmfplc2` utility correctly. Your command:

```
vmfplc2 fsf 131 86WTTL.AWS
```

is invalid. `fsf` is not a valid verb. The only verbs (actions) that Hercules's `vmfplc2` utility supports are DUMP, LOAD and SCAN. Further, I'm guessing `131` is not a valid ctlfile name either. I suspect such a ctlfile likely does not exist on your system because you failed to create such a control file. Am I right?

From the sounds of it you are unfamiliar with how to use Hercules's `vmfplc2` utility, which it should be pointed out is _not_ designed to be the same as (nor function the same as) VM's utility of the same name. They are completely different programs that just happen to have the same name (since they are used hand in hand with one another).

Tell me what you are trying to do (what you are ultimately trying to accomplish) and I will try to help you.

**Comment by marXtevens** [comment]
The example above was to indicate that I understood what the Hercules `VMFPLC2` program does do and does not do.

It does load, scan, dump, per the online help. It does not position the tape 132 files (tape marks) into an emulated tape. That is the support I am asking for, to position the tape such that I do not have to scan/load through 131 files to get to the 132nd one, which contains the VM files I am looking for ... in this particular example.

As an example a VM Workshop tape contains thousands of files ...

```
FSVIEW: 86TL TAPEMAP D1               Lines 1-39/10451 V80[1-79]  FSVIEW V1.2.5
1TapeMap   (Version 2.3)   University of Kentucky Computing Center
 06/16/86 12:21    VM/SP    CMS        SYSDAVE  TAPEMAP
 Page   1


 Options specified: DISK     NOTERM   TAP2
0The input tape is on a 3420-8 9-track tape drive at address 182.
 The tape was recorded at 6250 bpi and is in  Unlabeled  format.
0No volume name can be determined.
0**** File      1.
      This file is apparently in VM/370  VMFPLC2  format.
0     FileName FileType FM Format LRecL    Records   Date     Time
+     ________ ________ __ ______ _____ __________ ________ ________
      VMWK1986 TOOLS1   A1 V         72        122 06/16/86 12:06:00
      VMWK1986 TAPEMAP1 A1 V         68      10451 06/16/86 09:18:00
      VMWK1986 ATTENDEE A1 V        108        183 06/12/86 16:38:00
      End of file       1 encountered after reading     187 blocks
      containing     710K bytes.  About   16 feet of tape was used.
      The largest block was  4,005 bytes, the last block was
         805 bytes, and the smallest block was     77 bytes.
```
The 132 file contains files I want without having to use SCAN 131 times to get there ...

```
0**** File    131.
      This file is apparently in VM/370  VMFPLC2  format.
0     FileName FileType FM Format LRecL    Records   Date     Time
+     ________ ________ __ ______ _____ __________ ________ ________
      CMSLOG   XEDIT    Z1 V         79         16 11/21/83 16:50:00
      CMSMON   EXEC     Z1 V         72         17 09/02/83 08:16:00
      CMSMON   RTABLE   Z1 V         69         85 10/17/83 08:21:00
      COMMAND  EXEC     Z1 V         70         64 04/13/84 11:18:00
      DMS$CM   ASSEMBLE Z1 F         80        486 11/22/83 10:34:00
      DMS$CM   LOADLIB  Z1 V        260         15 11/22/83 11:05:00
      DMS$CM   MONITOR  Z2 F         80          7 08/16/83 09:21:00
      DMS$CM   SCRIPT   Z1 V         73        267 05/20/84 12:38:00
      DMS$CM   TEXT     Z1 F         80         27 11/22/83 11:04:00
      HOWFULL  ASSEMBLE Z1 F         80         56 09/02/83 10:01:00
      HOWFULL  HELPCMS  Z1 V         68         34 09/02/83 10:01:00
      HOWFULL  MODULE   Z1 V        456          2 09/02/83 10:01:00
1TapeMap   (Version 2.3)   University of Kentucky Computing Center
 06/16/86 12:21    VM/SP    CMS        SYSDAVE  TAPEMAP
 Page  93 Volume Unlabeled

      IDLEUSER EXEC     Z1 V        108         38 11/10/83 08:12:00
      INSTALL  LISTING  Z1 V         79        180 05/22/84 10:34:00
```

Thus I am asking for the Hercules version to be enhanced, to be more like the VM/370 CE version.

```
Help for VMFPLC2                                                  FSHELP V1.2.5
===>

VMFPLC2                                                   CMS Transient command

Use the VMFPLC2 command to dump VMFPLC2-formatted files from disk to tape, load
previously dumped files from tape to disk, and perform various control
operations on a specified tape drive.  Files processed by the VMFPLC2 command
must be in a unique VMFPLC2 format.  The VMFPLC2 command does not process
multivolume files.  Disk files to be dumped can contain either fixed- or
variable-length records.  The format of the VMFPLC2 command is:
+----------+------------------------------------------------------------------+
| TAPE     | DUMP fn|* ft|* [fm|*] [(optionA optionB optionD[)]]              |
|          | LOAD [fn|* ft|* [fm|A]] [(optionB optionC optionD[)]]            |
|          | SCAN [fn|* ft|*] [(optionB optionC optionD[)]]                   |
|          | SKIP [fn|* ft|*] [(optionB optionC optionD[)]]                   |
|          | MODESET [(optionD[)]]                                            |
|          | tapcmd [1|n] [(optionD[)]                                        |
|          |                                                                  |
|          | optionA:  NOWTM|WTM                                              |
|          | optionB:  Term|NOPRint|PRint|DISK                                |
|          | optionC:  EOF 1|EOF n|EOT                                        |
|          | optionD:  TAP1|TAPi|181|cuu [7TRACK|9TRACK] [DEN den] [TRTCH a]  |
+----------+------------------------------------------------------------------+
where:
...
tapcmd [1 | n]
         specifies a tape control function (tapcmd) to be executed n times
         (default is 1 if n is not specified). These functions also work on
         tapes in a non-CMS format.  'tapcmd' may be:
            BSF       Backspace n tape marks
            BSR       Backspace n tape records
            ERG       Erase a defective section of the tape
            FSF       Forward-space n tape marks
            FSR       Forward-space n tape records
            REW       Rewind tape to load point
            RUN       Rewind tape and unload
            WTM       Write n tape marks
```
I Hope This Helps.

 ... Mark S.

**Comment by Fish-Git** [comment]
> It does load, scan, dump, per the online help. It does not position the tape 132 files (tape marks) into an emulated tape. That is the support I am asking for, to position the tape such that I do not have to scan/load through 131 files to get to the 132nd one, which contains the VM files I am looking for ...

> The 132 file contains files I want without having to use SCAN 131 times to get there ...

You don't need to. The Hercules `vmfplc2` utility will LOAD whatever file you want, no matter where it is on the tape. It reads your control file and constructs a list of files that you want to be loaded and reads the tape until it finds them all or it reaches the end of the tape.

The sequence/order that you specify the files in your control file doesn't matter either. It does _not_ need to match the sequence/order that the files actually exist on on tape. As vmfplc2 reads the tape, it checks each file that it encounters on the tape to see if it matches any of the ones specified in your control file. If it does, it loads it. If it doesn't, then it skips it and moves on to the next file on the tape. It does this until either all of the files you specified have been LOADed ("extracted") or the end of the tape is reached, whichever comes first.

If the tape contains multiple copies of the same named file and you want, say, the third one (i.e. you want to skip the first and second occurrence and load the third occurrence), then simply specify that file three times in your control file. Upon encountering the first occurrence of the file on the tape, it will load it to whichever host file you specified in the first occurrence you specified in your control file. When the same file is encountered for the second time on the tape, it will load to whichever host file you specified in the second occurrence you specified in your control file. Etc. (Once a file that you specify in your control file is processed, it is removed from the list.)

I designed vmfplc2 to try and be as easy to use as possible. I admit the documentation probably isn't the greatest however. It doesn't explain atypical use case scenarios such as yours or the ones described above. I simply made minor(?) edits Ivan's existing documentation. I suppose we could probably do better documentation-wise.

Have you _tried_ using vmfplc2 to load your file yet? Because it doesn't sound like you have. Doing a SCAN reads and reports _every file_ found ON THE TAPE, not within a tapemark delimited portion of it like the CMS vmfplc2 does. That is to say, the Hercules vmfplc2 utility SCAN function scans _the entire tape_ (i.e. _all files_, all the way until the physical end of the tape is encountered) and reports each file that it encounters (as well as each tapemark it encounters too).

Please just give it a try. I'm sure it will work just fine for you, with no enhancement necessary.

**Comment by Fish-Git** [comment]
@marXtevens

Hello? Have you tried it yet?

**Comment by Fish-Git** [comment]
Closing due to lack of response and re-categorizing as Invalid (User Error).
