### ISSUE TITLE
dasdinit with -nnn (i.e. negative) size parameter creates a huge file 

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#472]
FBA DASD 3370 has according to the specification  558000 sectors and 512 bytes per sector and result in an file with 272 MB size 

<pre>
$ <b>dasdinit -lfs CMS19E.019E 3370 CMS19E</b>
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.4.1.10647-SDL-gd0ccfbc9-modified
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I YBI-15301-10646
HHC01415I Build date: Jan 31 2022 at 16:10:41
HHC00463I 0:0000 CKD file CMS19E.019E: creating 3370 volume CMS19E: 558000 sectors, 512 bytes/sector
HHC00460I 0:0000 CKD file CMS19E.019E: 558000 sectors successfully written
HHC02423I DASD operation completed
</pre>

Trying to create a DASD with smaller size is possible  with specifying the  sectors as parameter to dasdinit but doing so leads to a huge file: 

<pre>
$ <b>dasdinit -lfs CMS19E.019E 3370 CMS19E -24000</b>
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.4.1.10647-SDL-gd0ccfbc9-modified
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I YBI-15301-10646
HHC01415I Build date: Jan 31 2022 at 16:10:41
HHC00463I 0:0000 CKD file CMS19E.019E: creating 3370 volume CMS19E: <b>4294943296 sectors, 512 bytes/sector</b>
</pre>

Which I had to interrupt as it fills up the filesystem. Seems there is a bug in calculating the FBA size. 

Small additional remark: `HHC00463I` should state that according to 3370 device type it allocates a FBA file and not an CKD.

**Comment by wrljet** [comment]
`-24000` is getting scanned as a negative value, which is then as an unsigned value 4294943296.

Try it without the `-` sign.

**Comment by Fish-Git** [comment]
_**FYI:**_

> <pre>
> HHC02499I Hercules utility <i>......</i> version 4.4.1.10647-SDL-gd0ccfbc9<b><i>-modified</i></b>
> </pre>

I happened to notice your reported version has "_**-modified**_" appended to it. I'm guessing this is probably because you did a `./autogen.sh` before you did your `./configure` and `make`. &nbsp; Am I correct?

Presuming I am, I should inform you that autogen is no longer needed when building Hercules. The repository should always contain a valid pre-generated `configure` script that you can use directly to build Hercules with. There is no need to "generate" (via autogen.sh) a new configure script. The configure script that Hercules comes with should be good enough.

You will still always need to _run_ configure of course. You will still need to do a `./configure ...` before doing your `make`. That has not changed. But you do _not_ need to do _(and indeed **should NOT do!**)_ a separate ./autogen.sh beforehand.

When you build Hercules _without_ doing an autogen, your version string should say just "**4.4.1.10647-SDL-gd0ccfbc9**" _(i.e. without "-modified" appended)_, indicating your Hercules is a _pristine, unmodified_ version of Hercules.

When we see someone using a "-modified" version of Hercules, we cannot be sure _what_ they modified. We cannot be 100% sure they didn't make their own custom modifications to Hercules.

When the version is reported _without_ the "-modified" string _(as it should be)_, then we can be 100% sure the user is indeed running the version of Hercules that we think they are.

Does that make sense?

**Comment by fbi-ranger** [comment]
Hi Fish,

That makes absolutely sense. Indeed in my automation script for building
Hyperion I have a autogen.sh as it was needed. I will remove it and rebuild
it.

BR Florian

Fish-Git ***@***.***> schrieb am Do., 10. Feb. 2022, 20:29:
