### ISSUE TITLE
S0C4 pic4

### ISSUE THREAD

**Issue by YossiReichman** [SDL-Hercules-390/hyperion#478]
Hi I just got a S0C4 pic4 meaning the psw key bits 8 - 11 doesn't match the storage key
the PSW key I can clearly tell by doing LISTPSW or tracing the instruction and storage key I verified by doing an IVSK instruction both the PSW and storage key are key 8 yet I get a S0C4 pic 4 please tell me what proof to recreate did this all under TSO TESTAUTH

**Comment by Fish-Git** [comment]
> Hi I just got a S0C4 pic4 meaning the psw key bits 8 - 11 doesn't match the storage key
> the PSW key ...

... _or the storage is fetch protected._

> I can clearly tell by doing LISTPSW or tracing the instruction

Show me.

> and storage key I verified by doing an IVSK instruction

Show me.

> both the PSW and storage key are key 8 yet I get a S0C4 pic 4

As I said, an Access Exception does not occur _only_ when the Access Keys don't match. It can also occur when the Fetch Protect bit is on.

> did this all under TSO TESTAUTH

I have no idea what TSO TESTAUTH is, and I'm not interested in learning.

> please tell me what proof to recreate

The _best_ thing would be seeing the actual Hercules logging of the Access Exception.

However, since `OSTAILOR z/OS` normally suppresses logging of Access Exceptions, you would need to temporarily _enable_ their logging before running your test. You can easily do this via the `pgmtrace` command:

      pgmtrace +04          # Enable logging of PIC 0004

Then after you run your test, disable them again:

      pgmtrace -04          # Disable logging of PIC 0004

Do that and then upload your Hercules logfile so we can see the actual PIC 4 from Hercules's point of view.

Otherwise, the only other way to definitively determine who's at fault is to do a Hercules instruction trace (`t+` command), but I would save that as a very last resort.

**Comment by Fish-Git** [comment]
> Otherwise, the only other way to definitively determine who's at fault is to do a Hercules instruction trace (`t+` command), but I would save that as a very last resort.

_Unless_ ... can you maybe trace _only_ your program's instructions leading up to the PIC 4? Is that possible?  That is to say, a specialized _(focused)_ instruction trace. That would certainly help.

Basically what I would need to see as "proof" that Hercules was buggy, would be what _Hercules **itself**_ was seeing that caused it to throw the PIC 4.

I would like to believe that Hercules would not throw an access exception unless an access violation truly existed!

**Comment by YossiReichman** [comment]
Will do

**Comment by YossiReichman** [comment]
Just tried to re-create it wasn’t able to will close out later today so sorry ☹

**Comment by YossiReichman** [comment]
Sorry about this had an oversight

**Comment by wrljet** [comment]
Is it actually explained, or was it a "random" thing?

**Comment by YossiReichman** [comment]
I re-ran the code trying to re-create and was unable to everything looks ok 

I ran this code multiple times tonite and it looks ok
