### ISSUE TITLE
Won't run (not a helpful title but also true)

### ISSUE THREAD

**Issue by JoeKnowsThings** [SDL-Hercules-390/hyperion#483]
Windows 11
Both Hercules 4.4.1 and Hercules 4.4.0
Guest OS - What comes with Hercules?

Log files and run files for both versions attached.
[4.4.1 log.txt](https://github.com/SDL-Hercules-390/hyperion/files/8419970/4.4.1.log.txt)
[4.4.1 run.txt](https://github.com/SDL-Hercules-390/hyperion/files/8419971/4.4.1.run.txt)

[4.4.0 log.txt](https://github.com/SDL-Hercules-390/hyperion/files/8419984/4.4.0.log.txt)
[4.4.0 run.txt](https://github.com/SDL-Hercules-390/hyperion/files/8419985/4.4.0.run.txt)

**Comment by Fish-Git** [comment]
Closing as "Invalid (User Error)". Please ask the support group for help.

**Comment by JoeKnowsThings** [comment]
Thanks for the "HELP"!

**Comment by Fish-Git** [comment]
> Thanks for the "HELP"!

GitHub Issues is for reporting Hercules bugs or potential bugs, not as a place to get help learning how to use it. If you are new to Hercules and are having trouble using it, then you need to ask the Hercules support group for help. That's what it's for. But that is _not_ what the GitHub Issues BUG REPORTING feature is for.

You obviously did not even bother to read our "**[SUBMITTING PROBLEM REPORTS](https://github.com/SDL-Hercules-390/hyperion/issues/373)**" document before posting your question because you failed to include a copy of your configuration file.

Even your your question _"Guest OS - What comes with Hercules?"_ tells us you are not even slightly familiar with what Hercules is or how to use it nor have read _any_ of our documentation, since this is one of the questions that is answered in our [F.A.Q.](https://sdl-hercules-390.github.io/html/hercfaq.html)

For help with how to _USE_ Hercules, ask our support group.

For reporting improper Hercules functionality (i.e. bugs), then this is the correct place.

You're in the wrong place.

**Comment by Fish-Git** [comment]
> 1) I did read about posting and it seemed to me there is a bug because Hercules would not start.

If you _think_ there may be a bug, then you ask the product support group for help _first_, since the problem could simply be that you are using the product incorrectly or are misunderstanding how the product is used.

If, after investigation, the members of the product's support group agrees there is likely a bug in the product, _then_ you should officially report the bug here, in GitHub Issues (which is our product's bug reporting mechanism).

> 2) I could send the config file because I do not have one. I could not find in the online docs anywhere it said I had to create a config file before I started Hercules THE FIRST TIME!

* "[Installation and Operation](https://sdl-hercules-390.github.io/html/hercinst.html)"
* "[Operating Procedure](https://sdl-hercules-390.github.io/html/hercinst.html#operating)"
* "[Configuration](https://sdl-hercules-390.github.io/html/hercinst.html#config)"
* "[Configuration File](https://sdl-hercules-390.github.io/html/hercconf.html)"
* "[Command line arguments](https://sdl-hercules-390.github.io/html/hercinst.html#arguments)"

> 3) Yes I am not familiar with SDL's version of Hercules. I am trying to learn but your denegrating, demeaning treatment has truely soured my experience with SDL.

I am truly sorry if my response came across as denigrating and/or demeaning. It was not meant to be. My intent was to _instruct_ you, not to ridicule you. The majority of a developer's time is spent investigating and correcting bugs and adding/enhancing new/existing features, not instructing new users how to use the product. That is the responsibility of the support group. That is the only point I was trying to get across.

> 4) IF YOU EVER SEND ME THIS TYPE OF HARSH EMAIL AGAIN, YOU WILL BE REPORTED TO GIT HIB, SDL, AND ANYWHERE I CAN FIND. I WILL NOT BE TREATED THIS WAY BY YOU. YOU ARE NO BETTER THAT I AM DAVID.

(me: rolls eyes)

I'm shaking in my boots.

**Comment by Fish-Git** [comment]
Commit fd955da4ab06fc3420184918ec338e61db19e184 (made on Apr 6, the same day as the above revert) added logic to ensure an error message is always properly issued when no config file is specified.
