### ISSUE TITLE
Default values are taken always - PLANT and MANUFACTURER

### ISSUE THREAD

**Issue by venjoa** [SDL-Hercules-390/hyperion#516]
I have updated `PLANT` and `MANUFACTURER` values instead of default values in Hercules configuration file and I did IPL.

```
PLANT      EC
MANUFACTURER HTC
```

After, I have added new volume using `DASDINIT` and `ATTACH`  and run `PGM=ICKDSF` to initialize dasd volume.

The INIT job return code is ZERO. The problem is `PLANT` and `MANUFACTURER` values are not updated and taking default values only.

The ICKDSF JOB OUTPUT

```
003990.000.HRC.ZZ.000000000001
003390.00A.HRC.ZZ.000000000001
```

Could you please someone throw light on these values.

Thanks,
Venjoa

**Comment by Fish-Git** [comment]
First of all, you obviously failed to read our "[**SUBMITTING PROBLEM REPORTS**](https://github.com/SDL-Hercules-390/hyperion/issues/373)" document that I asked you to please read before creating your new GitHub Issue. You failed to identify which _specific version_ of Hercules you are using, as well as failed to attach other needed information _(such as your Hercules **configuration file** and, most importantly, your **Hercules log file**)._

You also failed to identify what guest operating system you are running _(although based on what little information you did provide, I can only presume is z/OS)_, as well as failed to provide the needed details regarding the _exact steps_ needed to reproduce your problem.

Nor did you explain what it is you are trying to do and why either. The only information you did provide was very minimal and quite vague at best.

We need detailed information before we can help you, Venjoa! We are not psychic!

What is it you are attempting to do that requires this information?

What software are you trying to use that won't run?

Or are you simply reporting something that you did not understand or expect?

In Hercules, the [`MODEL`](https://sdl-hercules-390.github.io/html/hercconf.html#MODEL), [`PLANT`](https://sdl-hercules-390.github.io/html/hercconf.html#PLANT) and [`MANUFACTURER`](https://sdl-hercules-390.github.io/html/hercconf.html#MANUFACTURER) settings have always been for the _**CPU only**_, not for devices:

<pre>
<b><i>d m=cpu</i></b>

IEE174I 18.31.20 DISPLAY M           FRAME  1     F      E   SYS=S0W1
PROCESSOR STATUS
ID  CPU                  SERIAL
00  +                     01C01C3931
01  +                     01C01C3931
02  +                     01C01C3931
03  +                     01C01C3931
04  +I                    01C01C3931
05  +I                    01C01C3931

<i>CPC SI = 3931.EMULATOR.<b>HTC</b>.<b>EC</b>.000000000000C01C</i>
CPC NAME = CPC_UNKNOWN_NAME
LP NAME = HERCULES   LP ID = 1
MIF ID  = 1

+ ONLINE    - OFFLINE    . DOES NOT EXIST    W WLM-MANAGED
N NOT AVAILABLE

I        INTEGRATED INFORMATION PROCESSOR (zIIP)
CPC SI  SYSTEM INFORMATION FROM STSI INSTRUCTION
CPC NAME CENTRAL PROCESSING COMPLEX NAME
LP NAME  LOGICAL PARTITION NAME
LP ID    LOGICAL PARTITION IDENTIFIER
MIF ID   MULTIPLE IMAGE FACILITY IMAGE IDENTIFIER
</pre>

&nbsp;
I tried your values, and my system successfully IPLs and runs just fine:
&nbsp;

<pre>
<b><i>d m=dev(0a80)</i></b>

IEE174I 18.55.44 DISPLAY M           FRAME  1     F      E   SYS=S0W1
DEVICE 00A80   STATUS=ONLINE
CHP                   0A
DEST LINK ADDRESS     00
PATH ONLINE           Y
CHP PHYSICALLY ONLINE Y
PATH OPERATIONAL      Y
MANAGED               N
CU NUMBER             080A
INTERFACE ID          0004
MAXIMUM MANAGED CHPID(S) ALLOWED:  0
DESTINATION CU LOGICAL ADDRESS = 00
SCP CU ND         = 003990.000.<b>HRC</b>.<b>ZZ</b>.000000000001.0000
SCP TOKEN NED     = 003990.000.<b>HRC</b>.<b>ZZ</b>.000000000001.0000
SCP DEVICE NED    = 003390.00C.<b>HRC</b>.<b>ZZ</b>.677617923122.0A80
</pre>

Note however, that I did _not_ run `ICKDSF` on any of my volumes either. But that is only because:

1. I don't know how to do that! _(I'm not a z/OS person. I know very little about z/OS. And besides, I've never had the need.)_
2. You failed to provide the _exact_ `ICKDSF` JCL and parameters (i.e. jobstream) that you ran to initialize your _(problematic?)_ dasd(s) with.

Nevertheless, as I explained, the Hercules `MODEL`, `PLANT` and `MANUFACTURER` settings are only for the `STSI` (Store System Information) instruction, but not for anything else. Setting those values to something other than their defaults will only have an effect on your CPU, but _not_ on any of your dasds.

I hope that helps.

**Comment by venjoa** [comment]
Thank you Fish for such a details information and it answered my question.

"In Hercules, the MODEL, PLANT and MANUFACTURER settings have always been for the CPU only, **not for devices:**".

what is the approach If i want to show MODEL/PLANT/MANUFACTURE for DASD devices as well.

**Comment by Fish-Git** [comment]
> What is the approach If I want to show MODEL/PLANT/MANUFACTURE for DASD devices as well?

There is no approach. Hercules does not currently support that.

**Comment by Fish-Git** [comment]
> What is the approach If I want to show MODEL/PLANT/MANUFACTURE for DASD devices as well?

What is it you are trying to accomplish? Why do you need to do that? Why is doing that important?

**Comment by Fish-Git** [comment]
Closing due to no response from OP.
