### ISSUE TITLE
HHC90508D COMM: pselect() failed: Invalid argument

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#517]
the subject tells  

after that 
a connect attempt from a 3270 emulator is unsuccesfull 

it happens at the current/latest
commit 6a2814412a1a2e2deeb62658d578ad115b09d3f2 ( Nov 2, 2022 )

it does NOT happen at
commit e7ca9106e961a5870cdfab8d246eb29566144dea ( Oct 16, 2022 )

hope that the info provided is enough ...

thank You 

enrico

**Comment by Fish-Git** [comment]
1. Please upload to this GitHub Issue your Hercules configuration and log files,
2. What 3270 emulator client are you using, and to what port are you trying to connect to?

**Comment by Fish-Git** [comment]
Also,  I tested this on my VMware Kubuntu 21.10 system (with kernel 5.13.0-52-generic, gcc 11.2.0 and clang 13.0.0-2) and it worked perfectly. What version of Linux are you using?

**Comment by Fish-Git** [comment]
Also, when the problem occurs, what do your `sysgport` and `qports` Hercules commands report?

**Comment by atncsj6h** [comment]
the title could be changed to something like

SYSGPORT default - SYSGPORT NO  not honored 

rerun the tests and ...

first few runs
sysgport not specified in the configuration  file

the sysgport command returns
HHC17001I SYSG console server NOT listening on any port

got the ( quite a few of them )
HHC90508D COMM: pselect() failed: Invalid argument

few more runs 
"sysgport no" explicitly specified in the configuration  file
in the log there is the message
HHC02204I SYSGPORT       set to NO
the sysgport command returns
HHC17001I SYSG console server NOT listening on any port

as before got the 
HHC90508D COMM: pselect() failed: Invalid argument

umpteen run 
"sysgport 3278" 
and it works


the html doc at https://sdl-hercules-390.github.io/html/hercconf.html#SYSG
SYSGPORT   NO  -or-  3278  -or-  nnnn  -or-  host:port

    Specifies (typically) the port number (in decimal) to which tn3270 and telnet clients should use to connect to a [SYSG](https://sdl-hercules-390.github.io/html/hercconf.html#SYSG) console device or the value NO. The default is NO, meaning no separate listening socket will be created for SYSG console connections. If an invalid value is specified Hercules defaults to port number 3278.

Do You still need the hercules configuration and execution log ??? 

enrico

PS .
I run hercules on an APPLE macmini arm64 using BIG SUR 11.7.1 (20g918)

**Comment by Fish-Git** [comment]
Interesting....

It might be something unusual with Apple, because as I said, I tested this on both Windows _and_ on my Kubuntu system, and it worked perfectly. Weird.

Let me test it again and see if there's something I maybe missed somewhere _(which at this early stage of the investigation seems very likely!)_.

I'll have to get back to you. Thank you for reporting it.

> Do You still need the Hercules configuration and execution log???

No.

**Comment by Fish-Git** [comment]
_**(Doh!)**_ &nbsp;Really stupid/careless bug in pselect() setup logic causing FD_SET to end up being empty! _(Oops!)_

Should be fixed now. Tested on Windows only, but the logic is platform neutral (host o/s shouldn't make any difference).

Please do git pull and rebuild to confirm.

Thanks. &nbsp;_(and sorry about that!)_

**Comment by atncsj6h** [comment]
I just run a quick and dirty check
and everything seems to work

tomorrow I will run more tests

Thank You

enrico

PS.
no reason to be sorry :-)

**Comment by Fish-Git** [comment]
> I can try this here on my Mac Mini.
> 
> But I will need to be told what to set up and try. (config, etc)

Hi Bill! &nbsp; I just committed the fix for this, so you could confirm it for me instead of waiting for Enrico.

Testing scenarios:

SYSG device in config | SYSGPORT in config | 3270 client port attempt | Expected result
------------------------| -----------------------| ---------------------------|-------------------
No | No | 3270 | Should connect okay
No | No | 3278 |  _Connect attempt should fail (port 3278 not listening)_
Yes | No | 3270 | Should connect okay to normal 3270 (i.e. _non-SYSG_) device
Yes | No | 3278 |  _Connect attempt should fail (port 3278 not listening)_
No | Yes | 3270 | Should connect okay to normal 3270 (i.e. _non-SYSG_) device
No | Yes | 3278 |  _Connection should be rejected (no SYSG device in config to connect to!)_
Yes | Yes | 3270 | Should connect okay to normal 3270 (i.e. _non-SYSG_) device
Yes(*) | Yes(*) | 3278(*) | Should connect okay to SYSG device (*)

(*) Trying to connect a second time to port 3278 should fail (even though SYSGPORT defined in config and SYSG device defined in config) because a SYSG device is already attached, and you can only ever have only _one_ SYSG device.

Using `SYSGPORT NO` in config file should also behave identically to not having it in your config at all.

**Comment by Fish-Git** [comment]
> I just run a quick and dirty check
> and everything seems to work

Thanks. I'm going to go ahead and close this issue then.

> tomorrow I will run more tests

10-4. Understood. Let us know if you find any other problems. In the mean time I'm going to close this issue.

Thanks.

_(And I always feel the need to apologize anyway whenever I make a careless programming mistake, even though that's a normal part of any programmer's life. I set rather high standards for myself and HATE it when I miss my mark. I'm somewhat a perfectionist like that. That's why I'm always making cosmetic changes too. That's just who I am.)_
