### ISSUE TITLE
FPR display command when CR0_AFP is off

### ISSUE THREAD

**Issue by salva-rczero** [SDL-Hercules-390/hyperion#543]
___
_**Note:** this issue is closely related to issue [\#546: "Incorrect S/370 Floating Point functionality when FEATURE_370_EXTENSION is #defined"](https://github.com/SDL-Hercules-390/hyperion/issues/546)._
___
Hi guys,

after running a simple test adding two HFP values:
```
DOUBLE1  DC    X'3F393EE5EEDCC20D'            dh'0.013976'
DOUBLE2  DC    X'3FDD15F02C4D65E4'            dh'0.053976'
         LD    R0,DOUBLE1
         LD    R2,DOUBLE2
         ADR   R2,R0
```
CR & FPR command shows:
```
cmdtab.c(685)     HHC01603I cr
hscemode.c(2596)  HHC02271I Control registers
hscemode.c(2597)  HHC02271I C0=0000000000040000 C1=0000000000000000 C2=0000000000000000 C3=0000000000000000 
...
cmdtab.c(685)     HHC01603I fpr
hscemode.c(2491)  HHC02270I Floating point registers
hscemode.c(2492)  HHC02270I FPR0=3F393EE5EEDCC20D FPR2=4011654D61B2A27F
hscemode.c(2492)  HHC02270I FPR1=0000000000000000 FPR3=0000000000000000
...
```
But, if I set CR0_AFP to off:
```
cmdtab.c(685)     HHC01603I cr 0=0
hscemode.c(2596)  HHC02271I Control registers
hscemode.c(2597)  HHC02271I C0=0000000000000000 C1=0000000000000000 C2=0000000000000000 C3=0000000000000000
...
cmdtab.c(685)     HHC01603I fpr
hscemode.c(2491)  HHC02270I Floating point registers
hscemode.c(2492)  HHC02270I FPR0=3F393EE5EEDCC20D FPR2=0000000000000000
hscemode.c(2492)  HHC02270I FPR4=4011654D61B2A27F FPR6=0000000000000000
```
FPR4 becomes FPR2. I found at **display_fregs**:
```
return(snprintf(buf,buflen,
            "%sFPR0=%8.8X%8.8X FPR2=%8.8X%8.8X\n"
            "%sFPR4=%8.8X%8.8X FPR6=%8.8X%8.8X\n"
            ,cpustr, regs->fpr[0], regs->fpr[1], regs->fpr[2], regs->fpr[3]
            ,cpustr, regs->fpr[4], regs->fpr[5], regs->fpr[6], regs->fpr[7]
        ));
```
Should it be...
```
return(snprintf(buf,buflen,
            "%sFPR0=%8.8X%8.8X FPR2=%8.8X%8.8X\n"
            "%sFPR4=%8.8X%8.8X FPR6=%8.8X%8.8X\n"
            ,cpustr, regs->fpr[0], regs->fpr[1], regs->fpr[4], regs->fpr[5]
            ,cpustr, regs->fpr[8], regs->fpr[9], regs->fpr[12], regs->fpr[13]
        ));
```
or am I missing something?

Thanks in advance.

**Comment by Fish-Git** [comment]
From the System/370 Principles of Operation:

> _**Floating-Point Registers**_
> 
> _Four floating-point registers are available for floating-point operations. They are identified by the numbers 0, 2, 4, and 6 and are designated by a four-bit R field in floating-point instructions. Each floating-point register is 64 bits long and can contain either a short (32-bit) or a long (64-bit) floating-point operand. A short operand occupies the leftmost bit positions of a floating-point register. The rightmost portion of the register is ignored in operations that use short operands and remains unchanged in operations that produce short results._
 
Since "short format" floating point instructions operate on only 32 bits (and not the entire 64 bits), the "`fpr`" registers in our `REGS` struct are defined in Hercules as an array of thirty-two 32-bit `U32` values:

https://github.com/SDL-Hercules-390/hyperion/blob/58578601d7a34fc11f050b0ac4fd425a4c0422eb/hstructs.h#L185-L189

Thus each 64-bit floating point register is _actually_ a combination of _two_ adjacent (consecutive) "`fpr`" array entries (the first being the high-order bits and the next being the low-order bits).

Thus to print non-AFP floating point register 0, you would use `fpr[0]` and `fpr[1]`. For FP register 2, you would use `fpr[2]` and `fpr[3]`, etc. There is no FP register 1, 3, 5 or 7-15 in non-AFP mode. Only 0, 2, 4 and 6.

In AFP mode however, since there are 16 registers (0-15), the register number is doubled before accessing the array. Thus in AFP mode, FP register 2 for example, becomes `fpr[4]` and `fpr[5]`, etc. This is because FP register 1 is a valid register number in AFP mode, being the combination of `fpr[2]` and `fpr[3].

Hercules is correct.


> But, if I set CR0_AFP to off:

> FPR4 becomes FPR2.

You're doing things wrong. Your confusion stems from the fact that you loaded and added two _**AFP**_ register values together _(i.e. while AFP mode was active/enabled)_, and are then erroneously expecting your floating point registers to somehow display properly when you manually disable AFP _afterwards!_

Try turning the CR0 AFP bit off in your test program _before_ you actually load your floating point registers and add them together.

Then afterwards -- _with AFP still being off_ -- display your FP registers (`'fpr'` Hercules command), and I'm sure they will display just as you would expect them too.

As I said, Hercules is correct.

You are simply doing things incorrectly/illogically. &nbsp; `;-)`

**Comment by salva-rczero** [comment]
Thanks you @Fish, as always, for your invaluable knowledge and dedication. 

But, I still have doubts about the display (not the Hercules behavior). I run the sample:

```
DOUBLE1  DC    X'3F393EE5EEDCC20D'            dh'0.013976'
DOUBLE2  DC    X'3FDD15F02C4D65E4'            dh'0.053976'
         LD    R0,DOUBLE1
         LD    R2,DOUBLE2
         ADR   R2,R0
```

with CR0_AFP off, and this is the output:

```
06:45:39 HHC02271I Control registers
06:45:39 HHC02271I C0=0000000000000060 C1=0000000000000000 C2=0000000000000000 C3=0000000000000000
...
06:45:39 HHC01603I fpr
06:45:39 HHC02270I Floating point registers
06:45:39 HHC02270I FPR0=3F393EE5EEDCC20D FPR2=0000000000000000
06:45:39 HHC02270I FPR4=4011654D61B2A27F FPR6=0000000000000000
```

Regards, salva.

**Comment by Fish-Git** [comment]
> with CR0_AFP off, and this is the output: 
> ```
> 06:45:39 HHC01603I fpr
> 06:45:39 HHC02270I Floating point registers
> 06:45:39 HHC02270I FPR0=3F393EE5EEDCC20D FPR2=0000000000000000
> 06:45:39 HHC02270I FPR4=4011654D61B2A27F FPR6=0000000000000000
> ```

Hmmm... Yes... I see that now...

It appears I was wrong and you were right: Hercules _does_ appear to have a problem (bug) with displaying the floating point registers correctly, and _possibly_ with processing them as well! _(i.e. the floating point instructions themselves may be functioning incorrectly too!)_

Thank you for noticing and thank you for reporting this problem, and a BIG THANK YOU for your persistence in ensuring the problem does not get swept under the rug by yours truly. _(I apologize sincerely for that!)_

Let me look into the matter further _(more deeply)_ and I will get back to you.

You may well have found a rather serious bug in Hercules's floating point handling!

**Comment by Fish-Git** [comment]
### _FYI:_
Please see GitHub Issue _**#546**: "[Incorrect S/370 Floating Point functionality when FEATURE_370_EXTENSION is #defined](https://github.com/SDL-Hercules-390/hyperion/issues/546)"_.

**Comment by Fish-Git** [comment]
@salva-rczero

I am now closing this issue because commit 14388cc3694350ba08a880c582c835733bb67a5a _should_ have resolved it. You might wish to confirm that. Thanks.

**Comment by salva-rczero** [comment]
@Fish-Git , thank you very much, I can confirm that it works as expected.

I have read your comments about **FEATURE_370_EXTENSION** and while, I am not sure I understand it 100%, I thank you, again for your efforts.

As you may have guessed, I arrived at the `display_fregs` problem by studying how I could solve the architectural requirement for the overlap between the FPRs and part of the SIMD VRs.

My first idea is to double from `U32 regs->fpr[32]` to `U32 regs->fpr[64]`, changing **FPR2I** to multiply by 4. But there are many references to check and test. Any ideas, will be welcome.

Meanwhile, I am still making progress on the vector instructions, with the very expensive method of synchronizing the FPR and VR registers, on each read or update.

Regards, salva.

**Comment by Fish-Git** [comment]
> @Fish-Git , thank you very much, I can confirm that it works as expected.

Great! Thank you.

> I have read your comments about **FEATURE_370_EXTENSION** and while, I am not sure I understand it 100%,

That's okay. You're new to Hercules development. If it helps any, some of the other developers don't understand it 100% either. &nbsp; `:)`

> As you may have guessed, I arrived at the `display_fregs` problem by studying how I could solve the architectural requirement for the overlap between the FPRs and part of the SIMD VRs.
> 
> My first idea is to double from `U32 regs->fpr[32]` to `U32 regs->fpr[64]`, changing **FPR2I** to multiply by 4. But there are many references to check and test. Any ideas, will be welcome.

When you first embarked on this journey (providing zVector support) your efforts inspired me. So much so that I decided to sit down and try to resolve that very conundrum. I believe I may have touched upon a viable solution.

It's still incomplete, but I believe it's close enough that with your help and/or the help of some of the other developers we might be able to turn it into something we can all use. I even went so far as to write a simple test program to prove its approach is sound and that it does indeed work as expected.

Unfortunately I got pulled away to work on other more important things _(which is unfortunately still the case)_ so I'm not quite ready to share it with anyone yet. Hopefully once I finish with what I'm currently working on I'll have time to return to it.

In the mean time, I feel all further communication along these lines should probably be in a separate GitHub Issue. I prefer to keep GitHub Issues "clean". I don't like them to change course _(veer off topic)_ midstream. The topic of this GitHub Issue ("FPR display command when CR0_AFP is off") has now been completed, so we shouldn't "pollute" it by changing the topic and begin discussing something that is not _specifically_ related to this GitHub Issue. Instead, we should create a brand new "generic" GitHub Issue for anything/everything to the z/Architecture Vector Facility effort.

Does that make sense?

In closing, I would like to applaud your efforts salva, and thank you for your efforts thus far. Hercules is an Open Source project and it wouldn't be the product it is today without contributions from dedicated users such as yourself. You and others are what makes Hercules great! &nbsp; `:)`

**Comment by salva-rczero** [comment]
> Hopefully once I finish with what I'm currently working on I'll have time to return to it.
I look forward to it, but take your time!

> Does that make sense?
Absolutely

Regards, salva.

**Comment by Fish-Git** [comment]
> > ... how I could solve the architectural requirement for the overlap between the FPRs and part of the SIMD VRs.
> 
> When you first embarked on this journey (providing zVector support) your efforts inspired me. So much so that I decided to sit down and try to resolve that very conundrum. I believe I may have touched upon a viable solution. ...
> 
> ... I even went so far as to write a simple test program to prove its approach is sound and that it does indeed work as expected. ...

The test program is called "swap128", and I've uploaded to GitHub in the following GitHub comment:

* https://github.com/SDL-Hercules-390/hyperion/issues/77#issuecomment-1449298489
