### ISSUE TITLE
Running Hercules Hyperion under Docker

### ISSUE THREAD

**Issue by carstenSpraener** [SDL-Hercules-390/hyperion#545]
I managed to start Hercules Hyperion as a docker container. It was quite easy to do and I want to ask you to add the Dockerfile and the Start-Script inside the container to your project. Detailed information is available here:

* https://www.spraener.de/2023/02/20/running-hercules-4-x-hyperion-in-a-docker-container/

It makes building and starting under Docker nearly a no-brainer. And having it under docker could bring MVS-Backend services to the Kubernetes world.

Thank you very much for the incredibly good software and for maintaining it. I really appreciate it.

Dockerfile:
* [Dockerfile.gz](https://github.com/SDL-Hercules-390/hyperion/files/10785417/Dockerfile.gz)

Container-start script to start hercules inside the container with `HERCULES_RC` set and config under `conf/hercules.cnf`
* [container-start.gz](https://github.com/SDL-Hercules-390/hyperion/files/10785422/container-start.gz)

The command to start the container with a mounted Volume and the required ports exposed
* [start-docker.gz](https://github.com/SDL-Hercules-390/hyperion/files/10785423/start-docker.gz)

**Comment by atncsj6h** [comment]
IMO lots of things are missing here

no info is provided on how to build the external packages 

running a _configure_ without any parameters will lead nowhere 

no info is provided on how to run the builtin test suite

what has been provided is just a subset of the steps that have to be done

**Comment by Fish-Git** [comment]
I am rejecting this change request because, as far as I know, there are already many(?) Dockers scatter around the web for Hercules/MVS/VM/etc, and I really don't feel we should be getting into the middle of that business.

Others may feel differently of course, so I am adding the "Discussion" label to this issue in case anyone else _(any of the other developers) wishes to chime in with their own opinion on the matter. I don't run this project. My opinion only carries one vote. If the other developers on the team feel differently and wish to out vote me, so be it. We'll do it. Otherwise I don't feel we should.

Sorry! &nbsp; `:(`

**Comment by atncsj6h** [comment]
Hi Fish! 
I agree with You
enrico

**Comment by wrljet** [comment]
Me, too.

Bill
