### ISSUE TITLE
Performance of SDL Hercules 4.2.1 vs. later releases in z/Arch mode

### ISSUE THREAD

**Issue by arfineman** [SDL-Hercules-390/hyperion#556]
I have noticed a little performance degradation that is clearly visible in MIPS rate between version 4.2.1 and later releases when in z/Arch mode.

I complied a little test program that is a simple `SLR R0,R0` and then a `BRCT R0,*` and the results show 4.2.1 is twice as fast as later releases.

Of course this is not a bug, and as features are added, instruction paths get longer and some degradation is expected. But I thought this degradation was a little excessive.

To test, I created 2 binary files. One that switches to z/Arch mode (_loopzarc_) and one that does not (_loop390_). They get loaded using the 3CARD LOADER. I have 2 readers defined and IPL 00B to test in 390 mode and IPL 00C to test z/ARCH mode.

<pre>
 000B    3505    C:/HRC/<b>loop390</b>.bin
 000C    3505    C:/HRC/<b>loopzarc</b>.bin 
</pre>

* [Loop.zip](https://github.com/SDL-Hercules-390/hyperion/files/11155476/Loop.zip)

Of course this is a very low priority issue.

**Comment by Fish-Git** [comment]
Version 4.3.0 introduced support for z/Arch TXF (Transactional Execution Facility), which necessarily introduced a non-insignificant performance impact in instruction execution speed. Prior versions (e.g. 4.2.1 and earlier) did not have TXF support and will likely perform better as a result. _(Over time, as the performance of more and more popular instructions are improved, this difference in performance will hopefully decrease.)_

> I complied a little test program that is a simple `SLR R0,R0` and then a `BRCT R0,*` and the results show 4.2.1 is twice as fast as later releases.

To be brutally honest I'm actually not at all surprised by that, since your _&lt;cough&gt;_"benchmark"_&lt;cough&gt;_ is executing the BRCT _(Branch Relative On Count)_ instruction 100% of the time.

When a constrained transaction is being executed, the BRCT instruction cannot be used _(it is in the set of restricted instructions)_, and executing it causes an immediate transaction abort.

Of course _**WE** (i.e. you and I)_ know that your little test is not executing any type of transaction _(it's not executing in TXF mode)_, but the BRCT instruction certainly doesn't know that.

We did not design our TXF implementation to route instruction execution to a completely different set of instruction functions depending on whether TXF was active/enabled or not. Doing that would very likely introduce an even _more_ severe negative performance impact than what is currently being imposed by our current implementation.

Instead, each instruction impacted by the facility **`(*)`** must test whether a constrained transaction is currently active or not and abort the current transaction if it is. As a result, the path length of the BRCT instruction, due to its having to check for this condition each and every time it is executed, is unsurprisingly _twice_ as long as it was before.

Being such a simple instruction, its original path length was of course very, very short. But now, with the introduction of the requirements being imposed by TXF support, its new longer path length is a much larger percentage of its original path length.

For example, say for the sake of argument, its path length was 1. That is to say, executing the BRCT instruction required the execution of only ONE single host instruction in order to emulate it. But now, in order to support TXF, we now have to execute TWO host instructions. So now, with the introduction of TXF, it now takes _twice_ as long to execute than it did before! _TWICE!_

And since your test is executing this particular instruction 100% of the time, it's hardly surprising that your "benchmark" is reporting the TXF version of Hercules as being twice as slow (or non-TXF versions as being twice as fast).

To perform a fairer apples-to-apples performance comparison _(instead of the apples-to-oranges comparison your silly test performed)_, your benchmark needs to execute a more realistic set/mix of instructions that are executed by typical normal workloads. I'm sure if you did that the performance impact between the two versions of Hercules would be much less. There will still be a performance difference between the two versions of course, but I'm rather confident it will me much, _much_ less than what you are erroneously perceiving it to be today with your poorly designed performance benchmark.

I will leave this GitHub Issue open so that you can respond and others too can comment on it if they wish.

I hope that satisfactorily explains things for you, Aaron.
___
**`(*)`** &nbsp;_See the description of the **Transactional-Execution Facility** in chapter 5 of the "[z/Architecture Principles of Operation](https://publibfp.dhe.ibm.com/epubs/pdf/a227832d.pdf)", especially the section on **Constrained Transactions** which lists the restricted instructions and their corresponding constraints._

**Comment by Fish-Git** [comment]
Closing.
