### ISSUE TITLE
IBM 3270 terminal with 122-key keyboard

### ISSUE THREAD

**Issue by Torinde** [SDL-Hercules-390/hyperion#597]
Which of the emulated machines support IBM 3270 terminals?

I'm interested into finding something where the 122-key keyboards can be tested - related to https://github.com/dosbox-staging/dosbox-staging/pull/2281 and https://github.com/joncampbell123/dosbox-x/issues/4127

Same question elsewhere: open-simh/simh/issues/290, Hercules-Aethra/aethra/issues/10

**Comment by Fish-Git** [comment]
Since no one else has bothered to answer, I will try.

As far as I know, just about every IBM and non-IBM operating system supports 3270 display devices.

If your concern is which of them support _real_ 3270 devices _(i.e. real physical hardware devices)_, the answer is a bit more complicated.

Hercules's 3270 device support is provided via a TCP/IP telnet connection to a tn3270 (telnet) emulator client:

  * https://en.wikipedia.org/wiki/3270_emulator

I believe more than one of our users has managed to connect real physical 3270 devices to Hercules, but I personally do not know how they accomplished it, as it is outside the scope of Hercules.

I believe Jay Maynard, the maintainer of [Hercules Aethra](https://github.com/Hercules-Aethra), may be one of those individuals who has accomplished it, so you might want to contact him.

A quick Google search uncovered the following web page which you may (or may not!) find useful:

  * [Connecting a Real IBM 3270 Terminal to an Emulated Mainframe with OEC](https://www.rs-online.com/designspark/connecting-a-real-ibm-3270-terminal-to-an-emulated-mainframe-with-oec)

Hope that helps!

I am closing this issue as "WON'T FIX" as technically, while _related_ to Hercules, does not really describe any type of issue or problem that needs to be corrected/fixed.

**Comment by Torinde** [comment]
Thanks!

I'm trying to find something that can utilize the 122 keys of the [IBM 3270 PC](https://en.wikipedia.org/wiki/IBM_3270_PC), so that the emulation of those extra keys in DOSBox can be tested.

So far I found the following software to be run inside DOSBox (booting a relevant DOS/Windows version):
- IBM Personal Communications/3270, Version 2.0 (PLET # ZP )
- IBM PC 3270 Emulator Program, Entry Level Version 2.0 (PLET #ZP )
- Oracle (Sun?) JD Edwards World
- Do you have any other examples?

But there is nothing for those programs to connect to, so that's why I'm asking if the Hercules emulator will accept such inputs.
