### ISSUE TITLE
Processor CP00: disabled wait state 0002000080000000 0000000000009064

### ISSUE THREAD

**Issue by geniusmichael** [SDL-Hercules-390/hyperion#605]
Running Hercules 4.1 ~ 4.6.0 on Windows 11 22H2
IPL z/OS V2R1 ADCD, I encountered the following error:
HHC00809I Processor CP00: disabled wait state 0002000080000000 0000000000009064

Searched the closed issued, and set the MAXCPU to 8, but it doesn't work.
[zOS2.1.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/13055209/zOS2.1.cnf.txt)
[Hercules Logfile.001.txt.txt](https://github.com/SDL-Hercules-390/hyperion/files/13055212/Hercules.Logfile.001.txt.txt)

Also tried to IPL z/OS V1R9, the same wait state code.

**Comment by Fish-Git** [comment]
What does "disabled wait state 0002000080000000 0000000000009064" mean? Have you looked up that wait state in the appropriate IBM messages manual?

* [SA38-0665-50 z/OS V2R5 MVS System Codes](https://www-40.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R5sa380665/$file/ieah700_v2r5.pdf)

FWIW, I have z/OS 2.1 ADCD, and it IPLs just fine.

Also, all of my dasds are named A1xxxx (or S1xxxx, because mine are the "Summer" edition of z/OS 2.1), not F1xxxx like yours are.

Are you _sure_ you're running z/OS 2.1? Maybe you're actually running some other version of z/OS?

I also see two unusual things in your config file: ECPSVM should be NO, not YES, and your PGMPRDOS statement should be LICENSED, not RESTRICTED. _(z/OS is an IBM Licensed operating system.)_

Maybe you just need to change those two statements and things will work? If your z/OS is indeed 2.1 that is. I suspect however, that you are using a later (newer) version of z/OS, which has not been tested with Hercules yet. (We've only tested it through z/OS 2.5c. Any version of z/OS newer than 2.5c is untested. Try using an older version of z/OS?)

**Comment by Fish-Git** [comment]
P.S. to @geniusmichael: _Technically_, issues such as this should be reported in the H390-MVS support group, and/or the main Hercules-390 support group, since your issue does not necessarily describe a Hercules problem, but rather describes a likely z/OS problem insomuch as you're probably not running Hercules correctly for z/OS. That is to say, your Hercules configuration file is very likely incorrect (e.g. your PGMPRDOS statement for example).

* Ref: https://sdl-hercules-390.github.io/html/hercsupp.html

If I receive no response in another few days I will be closing this issue as "[PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC/PEBCAK/PICNIC)".

**Comment by Fish-Git** [comment]
No response from user; closing.
