### ISSUE TITLE
Mainframe/Hercules newbie trouble building/running Hercules

### ISSUE THREAD

**Issue by rltbsb** [SDL-Hercules-390/hyperion#611]
Steps to reproduce (following the instructions):
1) create a fresh install of Ubuntu 22.04.3 LTS and update
2) give root powers to user in /etc/sudoers
3) git clone  https://github.com/SDL-Hercules-390/hyperion.git hercules
4) cd hercules
5) apt-get -y install git wget time build-essential cmake flex gawk m4 autoconf automake libtool-bin libltdl-dev libbz2-dev zlib1g-dev libcap2-bin libregina3-dev
6) ./util/bldlvlck (results: everything OK)
7) ./configure
8) make
9) make install
10) export LD_LIBRARY_PATH=/usr/local/lib
11) cd ..
12) hercules -f none

Result:
![image](https://github.com/SDL-Hercules-390/hyperion/assets/20867593/dedbf18e-c1c5-4c68-a0d2-c984847213fb)

**Comment by wrljet** [comment]
What is the actual problem you're reporting.  Your output looks as expected.

Bill

**Comment by rltpoa** [comment]
Sorry, I'm new to the mainframe world and I thought there was an error.
The reasons I assumed there was something wrong are the following:
1) There's no "ready" message (or any message showing the listening host/port).
2) There's this menacing red bar at the bottom with undocumented hieroglyphs (sorry for the joke).
3) There is a "Without Regina REXX support" message, even if I have already installed it.
4) I can't connect to localhost:3270 (or 127.0.0.1:3270)
![image](https://github.com/SDL-Hercules-390/hyperion/assets/20867593/19ed38d4-2ec8-445b-9d81-30bd64e0710e)

I'd appreciate if somebody could explain how do I get to this welcome screen:
https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.HERCLOGO.md

PS: I have an old Z/OS 1.10 image I'd like to install on Hercules.

Thanks in advance.

**Comment by wrljet** [comment]
Welcome, Rafael

You should get subscribed to one of more of the mailing lists related to Hercules on Groups.io.
Such as the [Hercules Hyperion](https://hercules-390.groups.io/g/group) list.
That will be the best place to ask questions about configuring and operating Hercules.

There is also a very active and friendly group on Discord.
Here is an [invitation](https://discord.gg/QWJdNmRU)

Some documentation exists in this repo that will help you get started:

[Hercules Installation and Operation](https://sdl-hercules-390.github.io/html/hercinst.html)
(I'm sure you've already read at least part of that, because you found the list of required packages to install.)

Let me try to address some of your points.

1a) The `herc =====>` above the red status bar is the prompt for Hercules commands.

1b) You need a command like this: `CNSLPORT  3270` in your config file.
Then you'll get a message at startup similar to:
```
HHC01024I Waiting for console connections on port 3270
```

Since you don't have a config file, that is probably why you don't see that message and cannot connect.
You could start off with the default example `hercules.cnf` that may be found in the main source code directory.

2) The menacing red bar is the status line.  It shows you the CPU PSW, tally of executed instructions, and I/O operations.

3) For Regina support, try adding `--enable-regina-rexx` to your `configure` command line.

4) Cannot connect the 3270... See (1) above about CNSLPORT.

Bill

**Comment by rltpoa** [comment]
Now it's becoming clearer. Thank you very much, Bill. Your answer helped a lot.

**Comment by wrljet** [comment]
OK, good!

**Comment by Fish-Git** [comment]
I agree that our documentation could be better in regards to better explaining how Hercules actually works, for the benefit of mainframe newbies _(and especially Hercules newbies!)_ such as Rafael.

I believe I saw a (long-ish?) thread on this very topic in the main Hercules forum recently (yes?), so can only presume that _someone_ is working on this issue and we will hopefully (eventually) have a "fix" for it.

Until then however, I suggest newbies to please post their questions to our primary support forum so that other Hercules users can help you. Posting a new issue to GitHub is, IMO, not the appropriate way to ask for such help/guidance. GitHub Issues is meant for reporting bugs in the product, not for asking for help with how to _use_ the product.

Thanks.

I will keep this issue open and mark it as "OnGoing". I will also change the title to b a bit more appropriate as well.

**Comment by wrljet** [comment]
Fish, there's really nothing to fix here (other than perhaps a bit more detail in our build doc).

**Comment by Fish-Git** [comment]
> (other than perhaps a bit more detail in our build doc)

Which is why I marked it "OnGoing". But I guess you're right. I'll go ahead and close this issue, but keep it marked as "DOC BUG". Cool?

**Comment by wrljet** [comment]
Yeah, cool.

I just didn't like to close things myself until the "customer" has mentioned they're happy and done.

**Comment by Fish-Git** [comment]
Well, as explained to the "customer", such should be directed to our support forum, so I personally don't, in this particular case, expect nor require any type of confirmation before closing.

For other more normal/typical GitHub Issues that report bona-fide bugs (whose fix would need confirming), yes. But for ones like this? Nah.

(At least IMO anyway.)

**Comment by rltpoa** [comment]
Hello Bill and Fish. Thank you for your support and sorry for the inconvenience of opening this issue here. Next time I'll post in the appropriate channel. Bill, I'm "happy and done". Thanks again.

**Comment by wrljet** [comment]
Fish, I meant perhaps waiting for you to close in those situation. :)

**Comment by wrljet** [comment]
> Hello Bill and Fish. Thank you for your support and sorry for the inconvenience of opening this issue here. Next time I'll post in the appropriate channel. Bill, I'm "happy and done". Thanks again.

No inconvenience at all.  That's why we're here.

Bill

**Comment by Fish-Git** [comment]
> Fish, I meant perhaps waiting for you to close in those situation.  `:)`

Chicken. &nbsp;`>;-)`
