### ISSUE TITLE
question about the __SSE2__ intrinsics ( x86intrin.h )

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#639]
how crucial is from a performance point of view the  __SSE2__  stuff ?

found this ....
https://github.com/DLTcollab/sse2neon

sse2neon
A C/C++ header file that converts Intel SSE intrinsics to Arm/Aarch64 NEON intrinsics.

is it worth investigating ?

out of curiosity I downloaded it and the test suite was successfull

SSE2NEONTest Complete!
Passed:  519
Failed:  0
Ignored: 4
Coverage rate: 99.23%

**Comment by Fish-Git** [comment]
> how crucial is from a performance point of view the **SSE2** stuff ?

I really have no idea since I am unfamiliar with x86/x64 instructions/assembly, so I have no idea how many SSE2 instructions end up being compiled into Hercules.

If you know which x86/x64 instructions are SSE2 instructions, I suppose you could compile Hercules with the option to produce assembler output, and then examine the assembler output to see how many SSE2 instructions the compiler decided to use.

Then I suppose you could compile Hercules again with some options that requests that SSE2 instructions _not_ be used, and then compare the performance of the two. That should answer your question.

Without having to go through all that effort however, based on just what Wikipedia says about SSE2:

  * https://en.wikipedia.org/wiki/SSE2

I would venture a guess that SSE2 support is very important for performance.

Unless someone else decides to jump into this discussion with their own thoughts on the subject within the next day or two, I'm going to close this issue due to lack of interest.

**Comment by atncsj6h** [comment]
hi Fish!
after one month without any interest, no need to wait, go ahead and close it
e

**Comment by wrljet** [comment]
There is interest.  Can't we leave it open?

**Comment by Fish-Git** [comment]
> There is interest. Can't we leave it open?

Sure. I'm just curious as to _why?_ I mean, virtually all modern x86/x64 processors support SSE2 these days, yes? So virtually all compilers also support them too, yes? Agreed? So what is there to discuss really? Whether we should allow compilers to use them?? That seems silly, doesn't it? Of course we should! What we _shouldn't_ do is anything that would _prevent_ their use! Yes? So again, what's to discuss? The question has essentially been answered: Yes, SSE2 instructions (intrinsics) _are_ important to performance.  _HOW_ important (to performance) they are is largely immaterial IMO, They certainly do not _harm_ performance that's for sure. And there's not much (if anything!) that we can do to _prevent_ a compiler from using them, so again, what's to discuss?

I'm confused! Why do we need to keep this issue open? Please explain.

**Comment by atncsj6h** [comment]
forgive me for the poor presentation of the issue in my initial post  ( I am just a poor old E3L )

I meant to open a discussion about ...
 
**if** SSE2 are giving a performance boost for the amd64/x86_64 
**then**  the ARM_NEON equivalents might  do the same for the arm/arm64 

the question is a moot point now ...
I  implemented  the ARM_NEON ifrastructure and now all I have to do is to measure the performange gain ( if any )
pretty intrusive change , 
the softfloat types have to be amended to avoid clashes with the types defined in the arm_neon.h header

I will close the issue now, no reason to keep it open
