### ISSUE TITLE
Enhancement of 3390-108 Support

### ISSUE THREAD

**Issue by Vf58** [SDL-Hercules-390/hyperion#648]
___
_**Note:** this issue is closely related to issue [\#686: "EAV Volumes"](https://github.com/SDL-Hercules-390/hyperion/issues/686)._
___
Hi,

As 3390-54 are becoming too small I'm using more and more 3390-108.
It would help but of course, it is a nice to have...

Vincent

**Comment by Fish-Git** [comment]
Show us evidence that such a dasd model actually exists, and we will consider it.

**Comment by Vf58** [comment]
Hi Fish,

is it ok for you ?

 Command ===>                                                          …
                                                                       …
 Unit . . : 3390               Free Space                              …
                                                                       …
  VTOC Data                    Total              Tracks         Cyls  …
  Tracks  . :     1,469        Size  . . :       920,779       61,384  …
  %Used . . :         2        Largest . :       904,395       60,293  …
  Free DSCBS:    72,091        Free                                    …
                               Extents . :       5                     …
                                                                       …
  Volume Data                  Track Managed      Tracks         Cyls  …
  Tracks . :     1,803,060     Size  . . :       916,999       61,132  …
  %Used  . :            48     Largest . :       904,395       60,293  …
  Trks/Cyls:            15     Free                                    …
                               Extents . :       4                     …

**Comment by Vf58** [comment]
<img width="305" alt="MOD108" src="https://github.com/SDL-Hercules-390/hyperion/assets/12208929/ad18d00d-0064-4f4f-bfab-485442365fa3">

**Comment by Fish-Git** [comment]
> I made a print screen showing 1.800.000 tracks = 2 x mod 54

I have no idea what I'm looking at.

**Comment by Vf58** [comment]
It was a print vtoc. 

In fact 3390-108 is a misuse of language as 3390-54 is. 
We should speak about 3390-A which has a capacity from 1 to 262668 cylinders 
https://www.ibm.com/docs/en/ds8870/7.1?topic=storage-ckd-extended-address-volumes-3390-model

If a 3390-54 is 65520 cylinders then we could define a 3390-108 as 131040 cylinders, approximately half of the max capacity of a 3390-A

**Comment by Fish-Git** [comment]
> https://www.ibm.com/docs/en/ds8870/7.1?topic=storage-ckd-extended-address-volumes-3390-model

Hercules does not currently support the new  CC CC cc cH Track Address format required accessing EAV (Extended ADDRESS Volume) dasds, and it is unlikely that it ever will, given that it would require an almost complete rewrite of our existing CKD dasd support. Sorry!

I am closing this issue as "WON'T FIX".

**Comment by Vf58** [comment]
Hi Fish,


sorry for this late answer, wasn't home.
I'm only interested in very larged DASD :-)

Thank you for having reopened the case.

Vincent

**Comment by Vf58** [comment]
Hi Fish,


sorry for this late answer, I wasn't home
Unfortunatly I was interested in very large CKD dasd, not FBA.

Thank you for having reopend the case.


Vincent

**Comment by Fish-Git** [comment]
> Unfortunately I was only interested in very large _**CKD**_ dasd, not FBA.

Oh well. I tried. &nbsp;`:(`

Very large CKD dasds are not possible as this time due to the EAV requirement in order for the guest to be able to address cylinders greater than cylinder 65535 _(which as already explained is unlikely to be supported given the current Hercules design)._

Nevertheless, even though _you_ are currently uninterested in support for very large _FBA_ dasds, I have already begun working on the changes necessary to support them anyway, in the hope that perhaps _others_ might find such support to be useful to them.

The code is already written and _seems_ to work okay, but it still needs a simple test program that proves that. Once the test program is written and tested, I will be committing it to Hercules, so I very much appreciate your inspiration for this enhancement. &nbsp;`:)`

 Even though it ultimately didn't work out the way you were hoping it would. &nbsp;`:-(`

**Comment by Vf58** [comment]
Hi FIsh,

Thank you for having reopened the case.
Good luck

**Comment by Fish-Git** [comment]
> The code is already written and _seems_ to work okay, but it still needs a simple test program that proves that. Once the test program is written and tested, I will be committing it to Hercules,

FYI: The mentioned test program has now been written and used to verify expected proper/correct Hercules behavior/functionality regarding extremely large CFBA/CFBA64 dasds. For those interested, it is possible to create e.g. a 300GB _(or larger!)_ CFBA64 dasd via dasdinit64 and Hercules can access any/all blocks of it just fine.

I did _not_ bother to check whether the same is true or not with respect to CCKD/CCKD64 dasds, since that would require adding EAV (Extended Address Volumes) support to Hercules, which is unlikely to occur any time soon _(if ever!)_, as it would require completely redesigning and rewriting _ALL_ of Hercules's existing emulated dasd functionality, which I seriously doubt is _ever_ going to happen in my lifetime.

Re-closing Issue as now complete.
