### ISSUE TITLE
Hyperion keeps crashing with segmentation fault

### ISSUE THREAD

**Issue by therazorgirl** [SDL-Hercules-390/hyperion#683]
Hi

I'm running  ubuntu 18.04 under latest git pull of Hyperion and it keeps crashing randomly, especially when I'm compiling. I tried to compile openssl 1.1.1g and well into the compilation this happens:

```
    +++ OOPS! +++

Hercules has crashed! (Segmentation fault)

Crash dump NOT created due to ulimit setting...
```

I've tried various memory configurations and it seems the more memory I add the sooner Hyperion crashes. It seems most stable with 4096 mb but still crashes.

Is this a known problem or am I missing something in my hercules.cnf?

**Comment by agadsby** [comment]
Check your Linux memory and swap space.    free -hI suspect you have run out of Linux memory. You probably have an out of memory process killed warning in your Linux logs. Try add more Linux swap. AndyOn 10 Sep 2024, at 14:39, therazorgirl ***@***.***> wrote:﻿
Hi
Im running  ubuntu 18.04 under Hyperion and it keeps crashing randomly, especially when Im compiling. I tried to compile openssl 1.1.1g and well into the compilation this happenes,
+++ OOPS! +++

Hercules has crashed! (Segmentation fault)
Crash dump NOT created due to ulimit setting...
Ive tried various memory configurations and it seems the more memory I add the sooner Hyperion crashes. It seems most stable with 4096 mb but still crashes.
Is this a known problem or am I missing something in my hercules.cnf

**Comment by therazorgirl** [comment]
Hi Andrew

Thank you for the reply. Indeed the swap was far to small so I increased it and gave the linux vm 12 Gb of memory, booted and tried to compile. The compilation went on for some time and then hercules segfaulted. The last recorded memory usage was 125 mb of ram and 0k in swap so does not seem to be memory related. I rebooted the vm and then hercules segfaulted again without any activity on the linux vm. I have tried to recompile hyperion with posix threads and do the openssl compilation  but it doesnt change anything, hercules still segfaults.
Maybe its unrelated but I had lots of problems installing ubuntu on the hyperion. It kept segfaulting during install until I gave the profile 1024 mb and then it installed (it segfaulted on 4096 mb and 2048 mb).
Right now while Im writing this the hercules segfaults again without any actity on the linux vm. It seems the more memory I give it the more unstable it becomes.

**Comment by agadsby** [comment]
Ok so what are you running Hercules on ? OS and hardware size. AndyOn 10 Sep 2024, at 18:27, therazorgirl ***@***.***> wrote:﻿
Hi Andrew
Thank you for the reply. Indeed the swap was far to small so I increased it and gave the linux vm 12 Gb of memory, booted and tried to compile. The compilation went on for some time and then hercules segfaulted. The last recorded memory usage was 125 mb of ram and 0k in swap so does not seem to be memory related. I rebooted the vm and then hercules segfaulted again without any activity on the linux vm. I have tried to recompile hyperion with posix threads and do the openssl compilation  but it doesnt change anything, hercules still segfaults.
Maybe its unrelated but I had lots of problems installing ubuntu on the hyperion. It kept segfaulting during install until I gave the profile 1024 mb and then it installed (it segfaulted on 4096 mb and 2048 mb).
Right now while Im writing this the hercules segfaults again without any actity on the linux vm. It seems the more memory I give it the more unstable it becomes.

**Comment by Fish-Git** [comment]
#### _General FYI regarding email replies:_

I would very much appreciate it if you would _**not**_ respond/reply to GitHub Issues via email.

I would much prefer that you instead respond/reply _directly_ via the GitHub Issues web page itself:

* **[ht<span>tps</span>://github.com/SDL-Hercules-390/hyperion/issues/XXX](https://github.com/SDL-Hercules-390/hyperion/issues/XXX)**

When you reply **directly** via their web page, I can make minor edits to your reply so it is more readable (prettier) by editing the fonts being used, formatting of log messages, etc.

When you reply via email however, I cannot edit your reply (GitHub does not allow editing of emails), so oftentimes it is much harder (more difficult) to read.

GitHub also does not allow attachments in their email replies either, making it impossible to receive a file that may have been requested from you.

It is up to you whether or not you want to take the time to reply via their web page or continue to reply via email, but it is generally preferable that you reply directly via their web page instead. Especially if you need to attach a file that was requested from you.

Thanks for understanding.

**Comment by Fish-Git** [comment]
FYI:
* https://github.com/SDL-Hercules-390/hyperion/issues/373

**Comment by therazorgirl** [comment]
Hercules is running under ubuntu 22.04 in a vbox with 16 GB of RAM and a 50 GB vda. The host is a win 11. Hercules was compiled with the standard ubuntu tool chain. I do have successfully run different types of hercules installations in a vbox through the years.
I tried with a 2048 mb profile and different workload and the same happened, approx 100 min after workload is started, hercules segfaults and the about 105 mb of ram are utilized and 0k of swap. Ive done a time trace on the vbox guest and prior to hercules announcing it has segfaulted the ticker freezes and there are timestamp gaps so the whole guest freezes at the same time and after the segfault the guest becomes unusable and needs restart.
Ill try other versions of hercules and see if they work so closing ticket.

**Comment by therazorgirl** [comment]
Hi Andrew

I feel very uncomfortable with sharing any additional information as Mr. Fish is watching. If you want you can contact me on r a z o r g i r l AT n i g h t c i t y dot j p and I can can supply you with lots more details and results of additional tests Ive been making.

**Comment by Fish-Git** [comment]
> I feel very uncomfortable with sharing any additional information as Mr. Fish is watching.

?!

Why do you feel uncomfortable with me? What have I done to make you feel uncomfortable? I'm simply trying to HELP you!

In order to be able to help you, it is important to provide specific information about the problem you are having, as explained in "[SUBMITTING PROBLEM REPORTS](https://github.com/SDL-Hercules-390/hyperion/issues/373)" link that I provided [earlier](https://github.com/SDL-Hercules-390/hyperion/issues/683#issuecomment-2341836509). 

Enabling Crash dumps (core files) on your system and then analyzing them when they are created (i.e. obtaining a backtrace) is also important, as explained in "[How to analyze a Linux "core" file (i.e. crash dump)](https://github.com/SDL-Hercules-390/hyperion/issues/199)".

As our "SUBMITTING PROBLEM REPORTS" document explains, we are not psychic! If you want our help, you need to provide enough helpful information as possible so that we are _able_ to help you!

Why does respectfully requesting such information make you feel uncomfortable? I don't understand! Do you want our help or not? &nbsp; _&lt;me: confused!&gt;_
