### ISSUE TITLE
Excessive Messages HHC01312I, HHC01315I, and HHC00801I.  NOT affecting the running Systems

### ISSUE THREAD

**Issue by desertwiz** [SDL-Hercules-390/hyperion#691]
While running z/VM, and z/OS as a virtual guest, receiving many `HHC01321I` and `HHC01315I` messages for DASD devices.

It's typical to see these for devices defined to Herc, but not yet in use (such as 3270 console devices). It's typical to see these messages the first time a DASD device is accessed.  In the past, this dd not occur so frequently.  Also receiving SIE error messages (should this be a separate issue?).

These messages indicate INTREQ on the device.  Usually only see it one time but getting many of these messages that repeat.

Example for 3270s:
```
15:59:39.825 0x00000D08 HHC01315I 0:090F CHAN: ccw 0B600001 00AA4C62=>7F                                  "
15:59:39.825 0x00000D08 HHC01312I 0:090F CHAN: stat 0200, count 0001
15:59:39.825 0x00000D08 HHC01315I 0:090D CHAN: ccw 0B600001 00000000=>7F                                  "
15:59:39.825 0x00000D08 HHC01313I 0:090F CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
15:59:39.825 0x00000D08 HHC01312I 0:090D CHAN: stat 0200, count 0001
15:59:39.825 0x00000D08 HHC01314I 0:090F CHAN: sense INTREQ
15:59:39.825 0x00000D08 HHC01313I 0:090D CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
15:59:39.825 0x00000D08 HHC01314I 0:090D CHAN: sense INTREQ
15:59:39.825 0x00000D08 HHC01315I 0:090E CHAN: ccw 0B600001 00000000=>7F                                  "
15:59:39.825 0x00000D08 HHC01312I 0:090E CHAN: stat 0200, count 0001
15:59:39.825 0x00000D08 HHC01313I 0:090E CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
15:59:39.825 0x00000D08 HHC01314I 0:090E CHAN: sense INTREQ
```

Example for DASD:
```
16:03:43.106 0x00000D08 HHC01315I 0:0ACE CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.106 0x00000D08 HHC01312I 0:0ACE CHAN: stat 0020, count 0000
16:03:43.112 0x00000D08 HHC01315I 0:0AED CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.112 0x00000D08 HHC01312I 0:0AED CHAN: stat 0020, count 0000
16:03:43.120 0x00000D08 HHC01315I 0:0A90 CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.120 0x00000D08 HHC01312I 0:0A90 CHAN: stat 0020, count 0000
16:03:43.126 0x00000D08 HHC01315I 0:0A92 CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.126 0x00000D08 HHC01312I 0:0A92 CHAN: stat 0020, count 0000
16:03:43.135 0x00000D08 HHC01315I 0:0AAF CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.135 0x00000D08 HHC01312I 0:0AAF CHAN: stat 0020, count 0000
16:03:43.140 0x00000D08 HHC01315I 0:0A8F CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.140 0x00000D08 HHC01312I 0:0A8F CHAN: stat 0020, count 0000
16:03:43.199 0x00000D08 HHC01315I 0:0A91 CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.199 0x00000D08 HHC01312I 0:0A91 CHAN: stat 0020, count 0000
16:03:43.200 0x00000D08 HHC01315I 0:0AB1 CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.200 0x00000D08 HHC01312I 0:0AB1 CHAN: stat 0020, count 0000
```

Example for `HHC00801I` SIE errors:
```
09:30:07.118 0x00000D08 HHC00801I Processor CP04: SIE: Region-second-translation exception interruption code 003A ilc 6
09:30:07.119 0x00000D08 HHC02269I CP04: R0=000200FFFFFFFFFF R1=000000007FF65B10
09:30:07.119 0x00000D08 HHC02269I CP04: R2=0000000002533000 R3=0000000002DE9498
09:30:07.119 0x00000D08 HHC02269I CP04: R4=00000000000000D0 R5=0000000002533000
09:30:07.119 0x00000D08 HHC02269I CP04: R6=0000000000000002 R7=0000000002DE3198
09:30:07.119 0x00000D08 HHC02269I CP04: R8=000000007FF65A30 R9=0000000004ECA7C0
09:30:07.119 0x00000D08 HHC02269I CP04: RA=0000004000000000 RB=0002000000000000
09:30:07.119 0x00000D08 HHC02269I CP04: RC=00000000000001A0 RD=000000007FF656BC
09:30:07.119 0x00000D08 HHC02269I CP04: RE=0000000000000001 RF=0002003FFFFFFFFF
09:30:07.119 0x00000D08 HHC02271I CP04: C0=008200029F98EE20 C1=00000004EC19400B
09:30:07.119 0x00000D08 HHC02271I CP04: C2=000000007C225B40 C3=0000000180400005
09:30:07.119 0x00000D08 HHC02271I CP04: C4=0000000100010005 C5=000000007EF4B140
09:30:07.119 0x00000D08 HHC02271I CP04: C6=0000000000000000 C7=00000004EC19400B
09:30:07.119 0x00000D08 HHC02271I CP04: C8=0000000000000000 C9=0000000000000000
09:30:07.119 0x00000D08 HHC02271I CP04: CA=0000000000000000 CB=0000000000000000
09:30:07.119 0x00000D08 HHC02271I CP04: CC=00000001116E9A4B CD=00000004EC19400B
09:30:07.119 0x00000D08 HHC02271I CP04: CE=00000000DF8FEE96 CF=000000007FF67138
09:30:07.119 0x00000D08 HHC02324I SIE: CP04: PSW=0704100180000000 0000000004EC80A0 INST=D73FB000B000 XC    0(64,11),0(11)         exclusive_or_character
09:30:07.119 0x00000D08 HHC02326I SIE: CP04: V:0002000000000000: Translation exception 003A (Region-second-translation exception)
09:30:07.119 0x00000D08 HHC02326I SIE: CP04: V:0002000000000000: Translation exception 003A (Region-second-translation exception)
```

Again, does not impact the systems.

Related info:

* Hercules Version-  **HHC01413I Hercules version 4.8.0.11339-SDL-DEV-g93248b13**
* Herc GUI Version-  **Hercules x64 Windows GUI -- Version 1.19.0.5966**
* Windows Version-  **10.0.22631, Build 22631**

Attachments:

* Hercules Logfile.225
[Hercules Logfile.255.txt](https://github.com/user-attachments/files/17708411/Hercules.Logfile.255.txt)

* Hercules Config File
[zos31a on zvm730 config 2024-10-31.txt](https://github.com/user-attachments/files/17708419/zos31a.on.zvm730.config.2024-10-31.txt)

* Hercules RC File
[RC-310.txt](https://github.com/user-attachments/files/17708421/RC-310.txt)

* z/VM Directory for Shared DASD and Guest
[MVSSHARE and WIZZ1 Direct.txt](https://github.com/user-attachments/files/17708430/MVSSHARE.and.WIZZ1.Direct.txt)

* STFLEFIX Rexx
[STFLEFIX.txt](https://github.com/user-attachments/files/17708433/STFLEFIX.txt)

* Profile Exec for Guest
[profile.txt](https://github.com/user-attachments/files/17708460/profile.txt)

* IPL Rexx for Guest
[iplwiza.txt](https://github.com/user-attachments/files/17708436/iplwiza.txt)

**Comment by Fish-Git** [comment]
> It's typical to see these for devices define to Herc, but not yet in use (such as 3270 console devices).

Correct. 3270 devices that are defined to Hercules (but which do not have any 3270 client connected yet) behave identically to a local 3270 display terminal device on a real physical machine but that is not turned on (i.e. is currently turned off): from the machine's (hardware's) point of view, there is a device there, so it tries writing to it (mostly likely to display the z/VM banner/logo) but encounters an Intervention Required error. Connecting a 3270 client session to that device address is like turning the power on for a real physical 3270 display device: an unsolicited device interrupt occurs, letting the system (i.e. z/VM in this case) the device is now ready, so z/VM then tries sending the z/VM banner/logo to it, and voila! From then on, that terminal functions normally.

> It's typical to see these messages the first time a DASD device is accessed. In the past, this dd not occur so frequently.

> ```
> 16:03:43.106 0x00000D08 HHC01315I 0:0ACE CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
> 16:03:43.106 0x00000D08 HHC01312I 0:0ACE CHAN: stat 0020, count 0000
> ...(etc)...
> ```

CCW opcode X'70' is an invalid opcode. Thus the **Channel Program Check** (CSW Unit/Channel status `0020`: 00 = Unit status = none;  20 = Channel status = "Program Check") being reported by Hercules.

After doing some research (Googling), it appears z/VM occasionally does this on purpose in order to interrupt (stop) a guest's channel program that is currently running (executing) on/by the device/channel, so that it (z/VM) can then do something that _IT_ needs to do that it deems to be more important than what _was_ being done on the device (i.e. has higher priority in its opinion).

I'm basing this on the Problem Summary that I found for z/VM APAR [_**VM66734**_](https://www.ibm.com/support/pages/apar/VM66734):

* _**VM66734: MESSAGES GTD2330E AND GTD2362I INDICATING INVALID CCW OPCODE (70) TDMF/K**_

> CP may insert certain invalid CCW opcodes into a channel program
> in order to regain control and perform some special operations.
> This is an intentional function of VM and TDMF can safely ignore
> these invalid CCW opcodes without terminating a volume
> migration

So it looks like you may need to apply the recommended PTF? _(I know VERY little about modern z/VM so I don't know what you might have been doing on your system that might have caused z/VM to purposely interrupt your devices' I/Os, so I'm just guessing here. But it seems logical given the way the APAR is worded.)_

I have no idea why they appear to be happening more often than before. Ask someone else. I know nothing about z/VM internals nor why z/VM behaves the way it does or whether its current behavior is considered normal or not.

If it is considered normal and occurs frequently enough to be a nuisance, I suppose we could consider providing some means of suppressing such messages, but I am personally in _strong favor_ of _**not**_ doing that. I strongly encourage _**not **_ suppressing _any_ messages that Hercules might issue for _any_ reason, as doing so hides what might be important information for support personnel to be aware of during problem determination. But if you insist on having such an ability, I suggest you create a GitHub Issue specifically asking for such a feature.

> Also receiving SIE error messages

The **`HHC00801I`** "SIE: Region-second-translation exception interruption code 003A" and associated **`HHC02326I `** "Translation exception 003A (Region-second-translation exception)" messages _appear_ to be completely normal. That is to say, there doesn't appear to be any indication that they were issued erroneously by Hercules.

Is there a reason you are concerned with these messages? What makes you believe they're not normal or a possible bug in Hercules? Do they happen a lot? Continuously/frequently? If they do, then they _might_ be cause for concern, but it's difficult to say. Maybe they happen all the time in the background but z/VM doesn't bother reporting them since it expects them to occur? _(whereas Hercules has no idea whether the guest (z/VM) considers them normal or not and thus _always_ reports them when they occur)_.

Again, while I  _strongly discourage_ doing so, you can easily suppress such messages by simply adjusting your `pgmtrace` setting:

```
HHC01603I *
HHC01603I *
HHC01603I pgmtrace
HHC02281I * = Tracing suppressed; otherwise tracing enabled
HHC02281I 0000000000000001111111111111111222222222222222233333333333333334
HHC02281I 123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0
HHC02281I                **    *     *                                   *
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I help pgmtrace
HHC01603I
HHC01602I Command               Description
HHC01602I ----------------      -------------------------------------------------------
HHC01602I pgmtrace             *Trace program interrupts
HHC01603I
HHC01603I Format: "pgmtrace [-]intcode" where 'intcode' is any valid program
HHC01603I interruption code in the range 0x01 to 0x40. Precede the interrupt
HHC01603I code with a '-' to stop tracing of that particular program
HHC01603I interruption.
HHC01603I
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I pgmtrace -3a
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I pgmtrace
HHC02281I * = Tracing suppressed; otherwise tracing enabled
HHC02281I 0000000000000001111111111111111222222222222222233333333333333334
HHC02281I 123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0
HHC02281I                **    *     *                             *     *
HHC01603I *
HHC01603I *
```
> (should this be a separate issue?).

Only if you feel it's a bona fide problem (bug) that needs to be looked into. Otherwise, no.

&nbsp;
Have your questions/concerns been addressed/resolved now? Do I have your permission to close this GitHub Issue? Or do you have additional questions or concerns?

Thanks.

**Comment by desertwiz** [comment]
Just read the APAR.  TDMF is an add on program that allowscopying a volume that has datasets/files open and in use.  The70 OpCode is something it uses.  I don’t have TDMF.  Maybesomething to do with the virtual Reserve/Release VM simulateswhen multiple guests use the same volumes.  Definitely not aHerc thing…zNOn Dec 9, 2024, at 1:25 AM, Fish-Git ***@***.***> wrote:﻿

It's typical to see these for devices define to Herc, but not yet in use (such as 3270 console devices).

Correct. 3270 devices that are defined to Hercules (but which do not have any 3270 client connected yet) behave identically to a local 3270 display terminal device on a real physical machine but that is not turned on (i.e. is currently turned off): from the machine's (hardware's) point of view, there is a device there, so it tries writing to it (mostly likely to display the z/VM banner/logo) but encounters an Intervention Required error. Connecting a 3270 client session to that device address is like turning the power on for a real physical 3270 display device: an unsolicited device interrupt occurs, letting the system (i.e. z/VM in this case) the device is now ready, so z/VM then tries sending the z/VM banner/logo to it, and voila! From then on, that terminal functions normally.

It's typical to see these messages the first time a DASD device is accessed. In the past, this dd not occur so frequently.


16:03:43.106 0x00000D08 HHC01315I 0:0ACE CHAN: ccw 7000000C 8FFFFF02=>0000D5D6 E3C90000 00000000          ..NOTI......
16:03:43.106 0x00000D08 HHC01312I 0:0ACE CHAN: stat 0020, count 0000
...(etc)...


CCW opcode X'70' is an invalid opcode. Thus the Channel Program Check (CSW Unit/Channel status 0020: 00 = Unit status = none;  20 = Channel status = "Program Check") being reported by Hercules.
After doing some research (Googling), it appears z/VM occasionally does this on purpose in order to interrupt (stop) a guest's channel program that is currently running (executing) on/by the device/channel, so that it (z/VM) can then do something that IT needs to do that it deems to be more important than what was being done on the device (i.e. has higher priority in its opinion).
I'm basing this on the Problem Summary that I found for z/VM APAR VM66734:

VM66734: MESSAGES GTD2330E AND GTD2362I INDICATING INVALID CCW OPCODE (70) TDMF/K


CP may insert certain invalid CCW opcodes into a channel program
in order to regain control and perform some special operations.
This is an intentional function of VM and TDMF can safely ignore
these invalid CCW opcodes without terminating a volume
migration

So it looks like you may need to apply the recommended PTF? (I know VERY little about modern z/VM so I don't know what you might have been doing on your system that might have caused z/VM to purposely interrupt your devices' I/Os, so I'm just guessing here. But it seems logical given the way the APAR is worded.)
I have no idea why they appear to be happening more often than before. Ask someone else. I know nothing about z/VM internals nor why z/VM behaves the way it does or whether its current behavior is considered normal or not.
If it is considered normal and occurs frequently enough to be a nuisance, I suppose we could consider providing some means of suppressing such messages, but I am personally in strong favor of not doing that. I strongly encourage **not ** suppressing any messages that Hercules might issue for any reason, as doing so hides what might be important information for support personnel to be aware of during problem determination. But if you insist on having such an ability, I suggest you create a GitHub Issue specifically asking for such a feature.

Also receiving SIE error messages

The HHC00801I "SIE: Region-second-translation exception interruption code 003A" and associated HHC02326I  "Translation exception 003A (Region-second-translation exception)" messages appear to be completely normal. That is to say, there doesn't appear to be any indication that they were issued erroneously by Hercules.
Is there a reason you are concerned with these messages? What makes you believe they're not normal or a possible bug in Hercules? Do they happen a lot? Continuously/frequently? If they do, then they might be cause for concern, but it's difficult to say. Maybe they happen all the time in the background but z/VM doesn't bother reporting them since it expects them to occur? (whereas Hercules has no idea whether the guest (z/VM) considers them normal or not and thus always reports them when they occur).
Again, while I  strongly discourage doing so, you can easily suppress such messages by simply adjusting your pgmtrace setting:
HHC01603I *
HHC01603I *
HHC01603I pgmtrace
HHC02281I * = Tracing suppressed; otherwise tracing enabled
HHC02281I 0000000000000001111111111111111222222222222222233333333333333334
HHC02281I 123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0
HHC02281I                **    *     *                                   *
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I help pgmtrace
HHC01603I
HHC01602I Command               Description
HHC01602I ----------------      -------------------------------------------------------
HHC01602I pgmtrace             *Trace program interrupts
HHC01603I
HHC01603I Format: "pgmtrace [-]intcode" where 'intcode' is any valid program
HHC01603I interruption code in the range 0x01 to 0x40. Precede the interrupt
HHC01603I code with a '-' to stop tracing of that particular program
HHC01603I interruption.
HHC01603I
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I pgmtrace -3a
HHC01603I *
HHC01603I *
HHC01603I *
HHC01603I pgmtrace
HHC02281I * = Tracing suppressed; otherwise tracing enabled
HHC02281I 0000000000000001111111111111111222222222222222233333333333333334
HHC02281I 123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0
HHC02281I                **    *     *                             *     *
HHC01603I *
HHC01603I *


(should this be a separate issue?).

Only if you feel it's a bona fide problem (bug) that needs to be looked into. Otherwise, no.
 
Have your questions/concerns been addressed/resolved now? Do I have your permission to close this GitHub Issue? Or do you have additional questions or concerns?
Thanks.

**Comment by Fish-Git** [comment]
Closing w/OP's permission
